### ISSUE TITLE
Does not enable after cordova-background-geolocation stop function called

### ISSUE THREAD

**Issue by dbowmanDT** [transistorsoft/cordova-plugin-background-fetch#100]
## Your Environment
* Plugin version: 5.3.0
* Geolocatino Plugin Version: 2.11.0
* Platform: iOS
* OS version:11.4.1
* Device manufacturer / model: Apple iPhone 7
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): ~4.5.1
* Plugin config

## Expected Behavior
I expected to be able to be able to disable the geolocation plugin and then call the appropriate function
with this plugin so that my mobile app will still process background tasks.

## Actual Behavior
Inside the success callback of the BackgroundGeolocation.stop() function, I enable this plugin and the background task I setup never runs.

## Steps to Reproduce
1. Enable  BackgroundGeoLocation plugin (config below).
2. Disable BackgroundGeoLocation plugin
4. Enable BackgroundFetch plugin by calling configure function.
5. Background function never is called.
LOC_CONFIG = {
    desiredAccuracy: 0,
    stationaryRadius: 25,
    activityRecognitionInterval: 8000,
    foregroundService: true,
    notificationTitle: lang('datatracForDrivers'),
    notificationText: lang('gps_background_desc'),
    notificationColor: '#1b5fa3',
    notificationSmallIcon: 'drawable/notif_icon',
    notificationLargeIcon: 'drawable/notif_icon',
    fastestLocationUpdateInterval: 2000,
    locationAuthorizationRequest: 'Always',
    preventSuspend: true,
    debug: false,
    stopOnTerminate: true,
    startOnBoot: false,
    heartbeatInterval: 5 * 60,
    locationAuthorizationAlert: {
        titleWhenNotEnabled: lang('gps_authalert_not_enabled'),
        titleWhenOff: lang('gps_authalert_off'),
        instructions: lang('gps_authalert_inst'),
        cancelButton: lang('gps_authalert_cancel'),
        settingsButton: lang('gps_authalert_settings'),
    },
};

## Context
  var fetchCallback = function() {
    console.log('[js] BackgroundFetch event received');
    BackgroundFetch.finish();
  };

  var failureCallback = function(error) {
    console.log('- BackgroundFetch failed', error);
  };
const bgGeo = window.BackgroundGeolocation;
bgGeo.stop(() => {
    BackgroundFetch.configure(fetchCallback, failureCallback, {
        minimumFetchInterval: 15,
    });
}, () => {
    console.log('failed to stop');
});

## Debug logs
No errors are thrown by either plugin

**Comment by christocracy** [comment]
- What do the XCode logs show?   You will see `[BackgroundFetch stop]` if the plugin stopped.  If you don't see that, `BackgroundFetch` is **not** stopped.
- Are you simulating iOS bacgkround-fetch events?

**Comment by dbowmanDT** [comment]
That answers my question of Geolocation turning it off, but my problem still remains. If you call stop() on the BackgroundGeolocation, the phone will no longer run a task in the background for the app. 

Do I need to make a different issue since you answered my initial theory of what I thought was going wrong?

**Comment by dbowmanDT** [comment]
The answer is that when you stop subscribing to location updates in iOS, your app will not be run in the BackgroundTask nearly as often.
