### ISSUE TITLE
Android: asynchronous code not executed when device is locked

### ISSUE THREAD

**Issue by kfrederix** [transistorsoft/cordova-plugin-background-fetch#101]
## Your Environment
* Plugin version: 5.3.0
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: Moto G5s plus
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0

## Expected Behavior
Asynchronous code in fetchCallback (e.g. ajax http requests) should execute on android also when device is locked.

## Actual Behavior
Asynchronous code in fetchCallback() executes fine when app is running in foreground.
When app is in background it also seems to run fine at first.
(triggered by `adb shell cmd jobscheduler run -f <my.app.id> 999`)

The problem is: after +/- 5 minutes I can still see the background fetch event coming in, but now the asynchronous code is no longer executed.

## Steps to Reproduce
Here's my (simplified) fetchCallback fn:
```
private fetchCallback() {
  this.log('[js] BackgroundFetch event received');  // can still see this log when device is locked
  this.log('starting async job'); // can still see this log when device is locked
  setTimeout(() => {
    // this part is no longer executed when device is locked (after +/- 5 minutes)
    this.log('async job done.');
    (<any>window).BackgroundFetch.finish();
    this.log('[js] BackgroundFetch finished');
  }, 1000);
}
```

I found [this issue on stackoverflow](https://stackoverflow.com/questions/51769237/async-code-is-not-executed-when-app-is-in-the-background) which seems to describe exactly the same problem, but unfortunately no answers (yet).

Any idea what could be causing this behaviour?

**Comment by christocracy** [comment]
You can't use `setTimeout` in a fetch-callback.  It doesn't work.

**Comment by kfrederix** [comment]
@christocracy I don't need a timeout but I would like to make a few http requests and handle the response... Is that possible in any way?
Do you have somewhere a quick example for this?

**Comment by christocracy** [comment]
Sure, do an HTTP request.  Just don't try and *simulate* that with `setTimeout`.

**Comment by kfrederix** [comment]
I am experiencing the same problem with http requests...
Using chrome inspector I can see the http requests appear with status "pending"....
As soon as I bring the app to foreground, the request finally comes through and callback gets executed.

```
private fetchCallback() {
    console.log('[js] BackgroundFetch event received');
    axios.get('https://jsonplaceholder.typicode.com/todos/1')
    .then(res => {
      console.log('got data from background: ', res.data); // working at first, but not anymore after +/- 5 minutes
      (<any>window).BackgroundFetch.finish();
      console.log('[js] BackgroundFetch finished');
    });
  }
```

**Comment by christocracy** [comment]
Show me corresponding ` adb logcat -s TSBackgroundFetch`

**Comment by kfrederix** [comment]
// 1. launch app + move app to background by tapping "home" button
// 2. trigger background fetch event a few times...
```
09-18 16:45:50.524 11670 11670 D TSBackgroundFetch: - Background Fetch event received
09-18 16:45:50.602 11670 11753 D TSBackgroundFetch: - finish
09-18 16:45:50.602 11670 11753 D TSBackgroundFetch: - jobFinished
09-18 16:46:59.354 11670 11670 D TSBackgroundFetch: - Background Fetch event received
09-18 16:46:59.422 11670 11753 D TSBackgroundFetch: - finish
09-18 16:46:59.422 11670 11753 D TSBackgroundFetch: - jobFinished
09-18 16:47:09.272 11670 11670 D TSBackgroundFetch: - Background Fetch event received
09-18 16:47:09.375 11670 11753 D TSBackgroundFetch: - finish
09-18 16:47:09.375 11670 11753 D TSBackgroundFetch: - jobFinished
09-18 16:47:15.080 11670 11670 D TSBackgroundFetch: - Background Fetch event received
09-18 16:47:15.123 11670 11753 D TSBackgroundFetch: - finish
09-18 16:47:15.123 11670 11753 D TSBackgroundFetch: - jobFinished
```
// 3. wait at least 5 minutes
// 4. now trigger background fetch again
```
09-18 16:56:02.916 11670 11670 D TSBackgroundFetch: - Background Fetch event received
```
// 5. log stops here
// 6. unlock devices: nothing happens
// 7. bring app to foreground
```
09-18 16:56:56.666 11670 11753 D TSBackgroundFetch: - finish
09-18 16:56:56.666 11670 11753 D TSBackgroundFetch: - jobFinished
```

**Comment by christocracy** [comment]
```javascript
// A public url
let url = 'http://tracker.transistorsoft.com/devices?company_token=transistor-ionic'

let fetchCallback = () => {
  console.log('[BackgroundFetch] - Received fetch event');
  
  this.http.get(url, {}, {}).then(response => {
    console.log('*** HTTP response: ' + response.status);
    BackgroundFetch.finish();
  });
}
```

With the app running in background & phone powered off, I run this every 5 min for 20 min.
```
$ adb shell cmd jobscheduler run -f com.my.app.id 999
```

```
09-18 11:38:12.694 17718 17718 D TSBackgroundFetch: - Background Fetch event received
09-18 11:38:12.708 17718 17718 I chromium: [INFO:CONSOLE(1836)] "[BackgroundFetch] - Received fetch event"
09-18 11:38:12.834 17718 17934 D TSBackgroundFetch: - finish
09-18 11:38:12.834 17718 17934 D TSBackgroundFetch: - jobFinished
09-18 11:38:12.836 17718 17718 I chromium: [INFO:CONSOLE(1839)] "*** HTTP response: 200"
.
.
.
09-18 11:44:17.093 17718 17718 D TSBackgroundFetch: - Background Fetch event received
09-18 11:44:17.105 17718 17718 I chromium: [INFO:CONSOLE(1836)] "[BackgroundFetch] - Received fetch event"
09-18 11:44:17.604 17718 17718 I chromium: [INFO:CONSOLE(1839)] "*** HTTP response: 200"
09-18 11:44:17.606 17718 17934 D TSBackgroundFetch: - finish
09-18 11:44:17.606 17718 17934 D TSBackgroundFetch: - jobFinished
.
.
.
09-18 11:49:43.026 17718 17718 D TSBackgroundFetch: - Background Fetch event received
09-18 11:49:43.040 17718 17718 I chromium: [INFO:CONSOLE(1836)] "[BackgroundFetch] - Received fetch event"
09-18 11:49:43.883 17718 17934 D TSBackgroundFetch: - finish
09-18 11:49:43.884 17718 17934 D TSBackgroundFetch: - jobFinished
09-18 11:49:43.886 17718 17718 I chromium: [INFO:CONSOLE(1839)] "*** HTTP response: 200"
.
.
.
09-18 11:54:41.444 17718 17718 D TSBackgroundFetch: - Background Fetch event received
09-18 11:54:41.453 17718 17718 I chromium: [INFO:CONSOLE(1836)] "[BackgroundFetch] - Received fetch event"
09-18 11:54:42.352 17718 17934 D TSBackgroundFetch: - finish
09-18 11:54:42.352 17718 17934 D TSBackgroundFetch: - jobFinished
09-18 11:54:42.354 17718 17718 I chromium: [INFO:CONSOLE(1839)] "*** HTTP response: 200"
.
.
.
09-18 11:59:41.539 17718 17718 D TSBackgroundFetch: - Background Fetch event received
09-18 11:59:41.551 17718 17718 I chromium: [INFO:CONSOLE(1836)] "[BackgroundFetch] - Received fetch event"
09-18 11:59:41.972 17718 17934 D TSBackgroundFetch: - finish
09-18 11:59:41.973 17718 17934 D TSBackgroundFetch: - jobFinished
09-18 11:59:41.974 17718 17718 I chromium: [INFO:CONSOLE(1839)] "*** HTTP response: 200"
```

**Comment by kfrederix** [comment]
Thank you @christocracy for running this test!

Which android version where you running on? Could this issue be android-version related?

Or could it be some setting on my device that you can think of?

**Comment by christocracy** [comment]
Pixel @ Android 9.0.  No, it's not android-version related.  More likely your manufacturer's *flavour* of Android.

Investigate "white listing apps background" for you device

**Comment by Caperious** [comment]
I have the exact same issue, if the app is in foreground, the code executes just fine, but when the app is "freezed" it does not run. If I then open the app again after an event (or events) has been executed in the background, i can see the code run for every event.

The first thing i do in the function is the console log, which is also output, when opening the app. Any ideas on how to tackle this? 
`console.log("[BackgroundFetch] EVENT:", taskId);`
