### ISSUE TITLE
Not running on 5 minutes interval

### ISSUE THREAD

**Issue by rravindranaik111** [transistorsoft/cordova-plugin-background-fetch#102]
Hello, i am trying this plugin on android version and it works after every 15 minutes but when I am trying to set this on every 5 minutes it is not possible.

Is there any way to do this ?

Thanks in advanced

**Comment by christocracy** [comment]
No possible.  Minimum is `15` minutes.  This is described in the first paragraphs of the [`README`](https://github.com/transistorsoft/cordova-plugin-background-fetch).

>There is no way to increase the rate which a fetch-event occurs and this plugin sets the rate to the most frequent possible — you will never receive an event faster than 15 minutes. The operating-system will automatically throttle the rate the background-fetch events occur based upon usage patterns. Eg: if user hasn't turned on their phone for a long period of time, fetch events will occur less frequently.
