### ISSUE TITLE
Error initializing background fetch – "plugin_not_installed"

### ISSUE THREAD

**Issue by ShafiqEssani** [transistorsoft/cordova-plugin-background-fetch#103]
## Your Environment
* Plugin version: 5.4.1
* Platform: iOS
* OS version: macOS High Sierra
* Device manufacturer / model: iPhone 6s version 11.4.1
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ios 4.5.5
* Plugin config:

```
<plugin name="cordova-plugin-background-fetch" spec="^5.4.1" />
"cordova-plugin-background-fetch": "^5.4.1",
```

## Expected Behavior

App should run successfully with the installed plugin. When I switch my app to background it should execute the callbackFn.

## Actual Behavior

Its running only the error function which says 
![screen shot 2018-11-12 at 12 16 29 pm](https://user-images.githubusercontent.com/24293253/48332210-d4778e80-e674-11e8-823b-43eaf3c026dc.png)

## Steps to Reproduce
Simply create a new application and install the plugin with these two commands:
**ionic cordova plugin add cordova-plugin-background-fetch
npm install --save @ionic-native/background-fetch** 

## Context

I just want to run my app in background and perform some tasks using this plugin background Fetch.
As Background mode plugin wont run in ios for more than 30 seconds.
```
    const config: BackgroundFetchConfig = {
      stopOnTerminate: false, // Set true to cease background-fetch from operating after user "closes" the app. Defaults to true.
    };
  
    this.backgroundFetch.configure(config)
       .then(() => {
           console.log('Background Fetch initialized');
            this.performTasks();
           this.backgroundFetch.finish();
  
       })
       .catch(e => console.log('Error initializing background fetch', e));
  
    this.backgroundFetch.start();
    this.backgroundFetch.stop();
```
## What I have already done:

- created new project
- re created project
- rm/add node_modules
- rm/add ios platform
- rm/add plugin several times

## Debug logs

- ios XCode logs, 

> 2018-11-12 12:22:26.036701+0500 bkLoc[489:25575] Apache Cordova native platform version 4.5.5 is starting.
> 2018-11-12 12:22:26.037479+0500 bkLoc[489:25575] Multi-tasking -> Device: YES, App: YES
> 2018-11-12 12:22:26.048538+0500 bkLoc[489:25575] CDVWKWebViewEngine: trying to inject XHR polyfill
> 2018-11-12 12:22:26.085128+0500 bkLoc[489:25575] CDVWKWebViewEngine will reload WKWebView if required on resume
> 2018-11-12 12:22:26.085210+0500 bkLoc[489:25575] Using Ionic WKWebView
> 2018-11-12 12:22:26.085759+0500 bkLoc[489:25575] [CDVTimer][console] 0.087976ms
> 2018-11-12 12:22:26.085932+0500 bkLoc[489:25575] [CDVTimer][handleopenurl] 0.096083ms
> 2018-11-12 12:22:26.088243+0500 bkLoc[489:25575] [CDVTimer][intentandnavigationfilter] 2.271056ms
> 2018-11-12 12:22:26.088364+0500 bkLoc[489:25575] [CDVTimer][gesturehandler] 0.071049ms
> 2018-11-12 12:22:26.088465+0500 bkLoc[489:25575] [CDVTimer][backgroundfetch] 0.077963ms
> 2018-11-12 12:22:26.088651+0500 bkLoc[489:25575] CDVIonicKeyboard: resize mode 1
> 2018-11-12 12:22:26.089521+0500 bkLoc[489:25575] [CDVTimer][keyboard] 0.974894ms
> 2018-11-12 12:22:26.105596+0500 bkLoc[489:25575] [CDVTimer][splashscreen] 16.021013ms
> 2018-11-12 12:22:26.112107+0500 bkLoc[489:25575] [CDVTimer][statusbar] 6.441951ms
> 2018-11-12 12:22:26.112167+0500 bkLoc[489:25575] [CDVTimer][TotalPluginStartup] 26.576996ms
> 2018-11-12 12:22:27.519619+0500 bkLoc[489:25575] Ionic Native: deviceready event fired after 873 ms

**Comment by christocracy** [comment]
I have nothing to do with `@ionic/native`.

The instructions for installing the plugin in the README are *very clear* and nowhere does it instruct you to have do anything related to `@ionic/native`.

If you have `@ionic-native/background-fetch` installed get rid of it.

The *only* thing you need to do is:
```
$ ionic cordova plugin add cordova-plugin-background-fetch
```
That's it.

**Comment by Jetro223** [comment]
I had the same error. Try configure() after platform.ready().

**Comment by ShafiqEssani** [comment]
Hey, @Jetro223 thanks it worked and the error of plugin not installed fade away.
Well, brother, I want to achieve such functionality in which my iOS app is running in the background and it communicates or coordinates with the server and some data to it. I also want to perform some tasks in the background.

Is there a way to do this using Ionic. I have tried the background mode plugin but it's not working properly.
