### ISSUE TITLE
Android: need to enable autostart permissions

### ISSUE THREAD

**Issue by Rcc19** [transistorsoft/cordova-plugin-background-fetch#104]
*****************************************************************
* Hi 
First of all, thank you for the plugin you developed. It works well under normal conditions.
*****************************************************************

## Your Environment
* Plugin version:5.4.1
* Platform: Android
* OS version: 8.0.0,  7.1.1, 8.0.0 (version corresponds to the following models)
* Device manufacturer / model: Samsung S8+,  Xiaomi note3,  Vivo x20
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin config

## Expected Behavior
> In the above device, calling configure should trigger the fetchCallback function normally. 
> And once the background app is closed, the app can be launched every 15 minutes.

## Actual Behavior
>In the test, I need to manually open the autostart permission of the application in the system settings or security software, the plugin can work normally.
> In the above device, the fetchCallback function is not triggered after calling configure.

## Steps to Reproduce
1. Just install the app in Xiaomi note3, don't manually open the autostart permission, the plugin will not work properly. 
2. Vivo is also the same

## Context
Can add the default autostart permission?

**Comment by christocracy** [comment]
Chinese devices are *the worst*.  The plugin has no control over these 3rd party APIs those manufacturers install into their custom version of the Android OS.

Unfortunately, It's you responsibility to educate your users about the specific requirements of these manufacturers specific requirements.
