### ISSUE TITLE
BackgroundFetch Class not found error

### ISSUE THREAD

**Issue by sureshway** [transistorsoft/cordova-plugin-background-fetch#105]
## Your Environment
* Plugin version:5.4.1
* Platform: Android
* OS version:6.0
* Device manufacturer / model:Motorola
* Cordova version (`cordova -v`):6.5.0
* Cordova platform version (`cordova platform ls`):
* Plugin config

var BackgroundFetch = window.BackgroundFetch;

// Your background-fetch handler.
var fetchCallback = function() {
  console.log('[js] BackgroundFetch event received');
  console.log("backgroung task *****************");
  // Required: Signal completion of your task to native code
  // If you fail to do this, the OS can terminate your app
  // or assign battery-blame for consuming too much background-time
  BackgroundFetch.finish();
};

var failureCallback = function(error) {
  console.log('- BackgroundFetch failed', error);
};

BackgroundFetch.configure(fetchCallback, failureCallback, {
  minimumFetchInterval: 15, // <-- default is 15
  stopOnTerminate: false,   // <-- Android only
  startOnBoot: true,        // <-- Android only
  forceReload: true
});

## Expected Behavior

We used the above code to test the plugin. While trying to use the above code. we got the plugin error as "BackgroundFetch failed Class not found". Please give us the solution.

**Comment by christocracy** [comment]
When in doubt, remove / re-add the plugin.  Cordova sometimes gets confused.  Open XCode and observe the `Plugins` folder.  You'll likely find the plugin classes `CDVBackgroundFetch` are missing.

![](https://dl.dropboxusercontent.com/s/rns1p1f5k0lfoe1/Screenshot%202018-12-19%2009.00.51.png?dl=1)

**Comment by sureshway** [comment]
I found class files are in plugin. still it shows the class files are missing when running the function in android.
