### ISSUE TITLE
Service not starting using ionic, but works fine with adb sheel start

### ISSUE THREAD

**Issue by spkprav** [transistorsoft/cordova-plugin-background-fetch#109]
## Your Environment
* Plugin version: 5.5.0
* Platform: Android
* OS version: 9
* Device manufacturer / model: SM-A505F
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): 
```
Installed platforms:
  android 7.1.4
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~6.0.0
```
* Plugin config
<plugin name="cordova-plugin-background-fetch" spec="~5.5.0" />
## Expected Behavior
The service should be called and I should get.
```
TSBackgroundFetch: - start
TSBackgroundFetch: - Background Fetch event received
TSBackgroundFetch: - finish
TSBackgroundFetch: - jobFinished
```

## Actual Behavior
I get only and nothing happens:
```
TSBackgroundFetch: - start
```
But, if I run using `adb shell cmd jobscheduler run -f <your.application.id> 999`, it works fine.
Background service with Ionic not working, this is not the only plugin which I tried, I have tried building a custom plugin, everything works fine in an android native app, when moved to the ionic plugin, it doesn't work.

## Steps to Reproduce

Example not working.

## Context
All I am trying is run a simple service which calls every few minutes and sends notification or even a simple log is not working, any help would be appreciated. 

## Debug logs

finish doesn't comes on log, so it's just 1 line with the configuration.

**Comment by christocracy** [comment]
I don't see a problem here in the SampleApp:
```
06-19 10:20:07.978  9251  9251 I chromium: [INFO:CONSOLE(1404)] "[BackgroundFetch] - Received 

06-19 10:34:33.772  9251  9251 I chromium: [INFO:CONSOLE(1404)] "[BackgroundFetch] - Received 

06-19 10:50:29.775  9251  9251 I chromium: [INFO:CONSOLE(1404)] "[BackgroundFetch] - Received 

06-19 11:06:06.300  9251  9251 I chromium: [INFO:CONSOLE(1404)] "[BackgroundFetch] - Received 
```

Are you attempting to receive fetch events *after* you've terminated your app?  Are you sure your app is running *in the background*?

**Comment by spkprav** [comment]
Weird, do you think it has to do with the Ionic and Cordova versions that I'm using?

It would be great if you could share your Sample app, so that I can confirm that it has to do something with the versions.

**Comment by christocracy** [comment]
> do you think it has to do with the Ionic and Cordova versions that I'm using?

No.

I asked you 2 questions:
1.  Are you attempting to receive fetch events after you've terminated your app? 
2.  Are you sure your app is running in the background?

**Comment by spkprav** [comment]
1. No
2. Yes and moreover, I'm still trying when the app is in foreground and with wake lock, so basically app doesn't sleep at all or goes to background, the screen will be always on and the app will be in active state

**Comment by Simbaclaws** [comment]
This issue is still affecting me.

I'm having this issue on both iOS and Android, whenever I simulate the background fetch it works, but when I set the app in the background aka the app drawer without closing the app. I can wait for hours without a single background fetch event happening.

Any idea what could be going on?
I'm also using ionic and cordova + capacitor (ionic 4)
