### ISSUE TITLE
UIBackgroundModes in *-Info.plist doesn't get updated

### ISSUE THREAD

**Issue by pehagg** [transistorsoft/cordova-plugin-background-fetch#110]
## Your Environment
* Plugin version: 5.5.0
* Platform: iOS
* OS version: macOS 10.14.6
* Device manufacturer / model: -
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): ios 5.0.1
* Plugin config: default

## Expected Behavior

UIBackgroundModes in project plist file should contain value "<string>fetch</string>".

## Actual Behavior

The value hasn't been added.

## Steps to Reproduce

1. cordova plugin add cordova-plugin-background-fetch

## Context

Add and use the plugin, simple as that. Now I get a warning that "fetch" needs to be added to the plist file under UIBackgroundModes. Manually adding it removes the warning (obviously). However, as we don't store plugins nor platform specific parts in version control we don't want to make manual tweaks to generated platform specific files either.

**Comment by christocracy** [comment]
Are you using Capacitor?

**Comment by pehagg** [comment]
Nope, we're using an Angular + Cordova setup.

**Comment by pehagg** [comment]
This has something to do with our project setup, because I can't repro the issue with a freshly created project. Closing issue.
