### ISSUE TITLE
IOS warning "the completion handler was never called" while Debug->Simulate Background Fetch

### ISSUE THREAD

**Issue by ozgeekemen** [transistorsoft/cordova-plugin-background-fetch#112]
I am trying to make **HTTP** request while application is in the background, on **IOS** , **"fetchCallback"** is not called during the simulate fetch. But on **Android**, fetchCallback is called successfully, but HTTP request stays on **pending** status if application  in the background more than 5 minutes.

## Your Environment
* Plugin version: 5.6.0
* Platform: iOS
* OS version: 12.2
* Device manufacturer / model: Iphone 8
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): 5.0.1
* Plugin config 
>* minimumFetchInterval: 15, // <-- default is 15 
>* requiredNetworkType: window.BackgroundFetch.NETWORK_TYPE_ANY

```
class BackgroundFetchService {
    private isInit: boolean = false

    public init(): void {
        this.isInit = true
        window.BackgroundFetch.configure(this.fetchCallback, this.failureCallback, {
            minimumFetchInterval: 15, // <-- default is 15
            requiredNetworkType: window.BackgroundFetch.NETWORK_TYPE_ANY
        })
    }

    public start(): void {
        console.log('BackgroundFetch => start')
        if (!this.isInit) {
            this.init()
        }
        window.BackgroundFetch.start()
    }

    public stop(): void {
        console.log('BackgroundFetch => stop')
        window.BackgroundFetch.stop()
    }

    private fetchCallback(): void {
        console.log('BackgroundFetch => event received')
        PouchDBConnector.getInstance().getFavorites().then(() => {
            console.log('BackgroundFetch => finish')
            // Required: Signal completion of your task to native code
            // If you fail to do this, the OS can terminate your app
            // or assign battery-blame for consuming too much background-time
            window.BackgroundFetch.finish()
        })
    }

    private failureCallback(error: Error): void {
        console.log('BackgroundFetch => failed', error)
    }
}
```

## Expected Behavior

fetchCallback has to be called.

## Actual Behavior

fetchCallback did't called. And there is a warning on the log of Xcode.

## Steps to Reproduce

1. Run application in background
2. Debug->Simulate Background Fetch
3. Check logs if function is called

## Context

Sync PouchDB-CouchDB when application is at background.

## Debug logs

`Warning: Application delegate received call to -application:performFetchWithCompletionHandler: but the completion handler was never called.`

**Comment by christocracy** [comment]
```
Application delegate received call to -application:performFetchWithCompletionHandler: but the completion handler was never called.
```
This can only mean that `BackgroundFetch.finish()` was never called, therefore, `getFavorites()` must not be resolving.  You should be `catch(error)` and ensure `BackgroundFetch.finish()` is called there too.

```
PouchDBConnector.getInstance().getFavorites().then(() => {
            console.log('BackgroundFetch => finish')
            // Required: Signal completion of your task to native code
            // If you fail to do this, the OS can terminate your app
            // or assign battery-blame for consuming too much background-time
            window.BackgroundFetch.finish()
        }).catch((error) => {
            console.error('Something bad happened');
           window.BackgroundFetch.finish();
        });
```
