### ISSUE TITLE
Background fetch is not working for android

### ISSUE THREAD

**Issue by reetaramadurg** [transistorsoft/cordova-plugin-background-fetch#113]
## Your Environment
* Plugin version: 5.6.0
* Platform:  Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):7.1.4
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
Needed to call the background fetch for every 15 minutes as expected,but function is not getting called for one time also. Kindly tell me more about var BackgroundFetch = window.BackgroundFetch;
should I  create any UI component to start the activity?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by reetaramadurg** [comment]
var ts = {
    initialize: function() {
      this.bindEvents();
      console.log("initialized...........");
    },
    bindEvents: function() {
      document.addEventListener('deviceready', this.onDeviceReady, false);
    },  

  onDeviceReady: function() {
    var BackgroundFetch = window.BackgroundFetch;
  
    // Your background-fetch handler.
    var fetchCallback = function() {
      console.log('hello from background sync fetchCallback..........');
  
      // Required: Signal completion of your task to native code
      // If you fail to do this, the OS can terminate your app
      // or assign battery-blame for consuming too much background-time
      BackgroundFetch.finish();
    };
  
    var failureCallback = function(error) {
      console.log('- BackgroundFetch failed', error);
    };
  
    BackgroundFetch.configure(fetchCallback, failureCallback, {
      minimumFetchInterval: 15 // <-- default is 15
    });
    console.log('hello from background sync configure..........');
  }

}

**Comment by christocracy** [comment]
Are you simulating fetch events and watching `adb logcat`?

See the Debugging section in README.

**Comment by reetaramadurg** [comment]
I m checking logcat, BackgroundFetch is not called..
I have checked in remote debugger console also. BackgroundFetch is never called.please help me 
to solve this issue. I have used react-native-background-fetch for my other application. It is working perfectly

**Comment by christocracy** [comment]
Are you *simulating* fetch events?

> please help me

What do think I’m doing, by responding?

**Comment by reetaramadurg** [comment]
Thank you Sir,
I m not simulating fetch events

**Comment by christocracy** [comment]
>I m not simulating fetch events

Why not?

**Comment by reetaramadurg** [comment]
adb shell am broadcast -a com.veanka.hello.BackgroundFetch.event.BACKGROUND_FETCH
Broadcasting: Intent { act=com.veanka.hello.BackgroundFetch.event.BACKGROUND_FETCH flg=0x400000 }
Broadcast completed: result=0

this is the output of event

**Comment by christocracy** [comment]
Why have you ignored this from the issue template?

>OS version:
>Device manufacturer / model:

**Comment by reetaramadurg** [comment]
OS version:Android Pie 9.0
Device manufacturer / model:Samsung Tablet

**Comment by christocracy** [comment]
If you have a 9.0 device, why are you using `adb shell am broadcat`??  Do you know [what API level Android 9.0 is](https://source.android.com/setup/start/build-numbers)?

Simulate a background-fetch event on a device (insert <your.application.id>) (only works for sdk 24+):
```
$ adb shell cmd jobscheduler run -f <your.application.id> 999
```

**For devices with sdk <21**, simulate a "Headless JS" event with (insert <your.application.id>)
```
$ adb shell am broadcast -a <your.application.id>.event.BACKGROUND_FETCH
```

**Comment by reetaramadurg** [comment]
Could not find job 999 in package com.veanka.hello / user 0

**Comment by christocracy** [comment]
- Are you watching your Javascript logs?
- Are you observing `$ adb logcat -s TSLocationManager` while your app is booting?

**Comment by reetaramadurg** [comment]
yes sir I am watching javascript logs ,
adb logcat -s TSLocationManager
--------- beginning of crash
--------- beginning of main
--------- beginning of system

**Comment by christocracy** [comment]
Sorry, `$ adb logcat -s TSBackgroundFetch`

**Comment by reetaramadurg** [comment]
adb logcat -s TSBackgroundFetch
--------- beginning of crash
--------- beginning of main
09-19 18:12:26.450 23484 23484 D TSBackgroundFetch: JobService onStopJob
09-19 18:14:25.974 23484 23484 D TSBackgroundFetch: - Background Fetch event received
09-19 18:14:25.974 23484 23484 D TSBackgroundFetch: - finish
09-19 18:14:25.974 23484 23484 D TSBackgroundFetch: - jobFinished
09-19 18:14:26.003 23484 23484 D TSBackgroundFetch: HeadlessJobService onStartJob
09-19 18:14:26.009 23484 23484 D TSBackgroundFetch: onHeadlessJsTaskStart: 3
09-19 18:14:26.009 23484 23484 D TSBackgroundFetch: JobService onStopJob
09-19 18:14:26.160 23484 23484 D TSBackgroundFetch: HeadlessJobService onStartJob
09-19 18:14:26.162 23484 23484 D TSBackgroundFetch: onHeadlessJsTaskStart: 4
09-19 18:14:26.193 23484 23484 D TSBackgroundFetch: onHeadlessJsTaskFinish: 4
--------- beginning of system

**Comment by reetaramadurg** [comment]
how can I run cordova code in background

**Comment by christocracy** [comment]
**READ the README** [`enableHeadless`](https://github.com/transistorsoft/cordova-plugin-background-fetch#config-boolean-enableheadless-false).  You must write native Android Java code to handle the "headless" state.

**Comment by reetaramadurg** [comment]
ok thank you,
but can I have any option to run javasript in background,instead of running headless in java

**Comment by christocracy** [comment]
>but can I have any option to run javasript in background,instead of running headless in java

If I *could*, I would.  It's impossible with Cordova.  If you like to use Javascript in your Headless Task, use React Native.

**Comment by reetaramadurg** [comment]
Thank you so much sir.Information is very helpful.I will try to code my background task in java.

**Comment by reetaramadurg** [comment]
adb shell cmd jobscheduler run -f com.veanka.hello  999
Could not find job 999 in package com.veanka.hello / user 0
 i m getting error in my logcat


adb logcat -s TSBackgroundFetch
--------- beginning of crash
--------- beginning of main
09-20 11:41:23.650 28151 28151 D TSBackgroundFetch: - Background Fetch eve
09-20 11:41:23.650 28151 28151 D TSBackgroundFetch: - finish
09-20 11:41:23.650 28151 28151 D TSBackgroundFetch: - jobFinished
09-20 11:41:23.663 28151 28151 D TSBackgroundFetch: JobService onStopJobpJob                                                                ce onS
09-20 11:41:23.688 28151 28151 D TSBackgroundFetch: HeadlessJobServiStart:ce onStartJob                                                       Finish
09-20 11:41:23.690 28151 28151 D TSBackgroundFetch: onHeadlessJsTaskStart: 10
09-20 11:41:23.717 28151 28151 D TSBackgroundFetch: onHeadlessJsTaskFinish: 10--------- beginning of system
09-20 11:51:23.692 28151 28151 D TSBackgroundFetch: JobService onStopJob
09-20 11:51:53.717 28151 28151 D TSBackgroundFetch: HeadlessJobService onStartJob
09-20 11:51:53.721 28151 28151 D TSBackgroundFetch: onHeadlessJsTaskStart: 11
09-20 11:51:53.753 28151 28151 D TSBackgroundFetch: onHeadlessJsTaskFinish: 11
 is running 

how can i gun Jobscheduler in my code

**Comment by reetaramadurg** [comment]
adb shell cmd jobscheduler run -f com.veanka.hello  999
Could not find job 999 in package com.veanka.hello / user 0
 i m getting error in my logcat


adb logcat -s TSBackgroundFetch
--------- beginning of crash
--------- beginning of main
09-20 11:41:23.650 28151 28151 D TSBackgroundFetch: - Background Fetch eve
09-20 11:41:23.650 28151 28151 D TSBackgroundFetch: - finish
09-20 11:41:23.650 28151 28151 D TSBackgroundFetch: - jobFinished
09-20 11:41:23.663 28151 28151 D TSBackgroundFetch: JobService onStopJobpJob                                                                ce onS
09-20 11:41:23.688 28151 28151 D TSBackgroundFetch: HeadlessJobServiStart:ce onStartJob                                                       Finish
09-20 11:41:23.690 28151 28151 D TSBackgroundFetch: onHeadlessJsTaskStart: 10
09-20 11:41:23.717 28151 28151 D TSBackgroundFetch: onHeadlessJsTaskFinish: 10--------- beginning of system
09-20 11:51:23.692 28151 28151 D TSBackgroundFetch: JobService onStopJob
09-20 11:51:53.717 28151 28151 D TSBackgroundFetch: HeadlessJobService onStartJob
09-20 11:51:53.721 28151 28151 D TSBackgroundFetch: onHeadlessJsTaskStart: 11
09-20 11:51:53.753 28151 28151 D TSBackgroundFetch: onHeadlessJsTaskFinish: 11
 is running 

how can i run Jobscheduler in my code

**Comment by christocracy** [comment]
Are you executing this *after* terminating your app?

**Comment by ilyafriedman** [comment]
> If you have a 9.0 device, why are you using `adb shell am broadcat`?? Do you know [what API level Android 9.0 is](https://source.android.com/setup/start/build-numbers)?
> 
> Simulate a background-fetch event on a device (insert <your.application.id>) (only works for sdk 24+):
> 
> ```
> $ adb shell cmd jobscheduler run -f <your.application.id> 999
> ```
> 
> **For devices with sdk <21**, simulate a "Headless JS" event with (insert <your.application.id>)
> 
> ```
> $ adb shell am broadcast -a <your.application.id>.event.BACKGROUND_FETCH
> ```

Simulate a background-fetch event on a device (insert <your.application.id>) (only works for sdk 24+):

and 
For devices with sdk <21, simulate a "Headless JS" event with (insert <your.application.id>)

What about sdk > 21 but < 24? lol
