### ISSUE TITLE
Headless Fetch

### ISSUE THREAD

**Issue by mark-wallpapermatic** [transistorsoft/cordova-plugin-background-fetch#114]
Hi, 

I want to implement a headless fetch. Do I still have to implement a javascript background fetch or will that headless fetch run for both when the app is running and when the app is terminated?

Thanks in advance.

**Comment by christocracy** [comment]
It’s documented in the readme.  You must implement the headless fetch handler with Java code in Cordova.  

https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/README.md#headless-fetch-setup

**Comment by mark-wallpapermatic** [comment]
Sorry if I was not clear. I know if have to write Java code. What I'm asking is if I used headless fetch handler, do I still have to write the javascript callback? It is unclear in the documentation.

**Comment by christocracy** [comment]
Yes, you need to #configure the plugin with JavaScript.  The #configure method requires a callback.

**Comment by mark-wallpapermatic** [comment]
Just to clarify, when app is NOT terminated, background fetch will run the javascript callback. But if the app is terminated, it will use run the java code in BackgroundFetchHeadlessTask.java. Is that right?

**Comment by christocracy** [comment]
Yes

**Comment by mark-wallpapermatic** [comment]
Thanks :)
