### ISSUE TITLE
Background fetch not getting called automatically at some periods of time (iOS)

### ISSUE THREAD

**Issue by NiravDhrangdharia** [transistorsoft/cordova-plugin-background-fetch#115]
## Your Environment
* Plugin version: 5.19.1
* Platform: iOS
* OS version: iOS 13.2, 13.3
* Device manufacturer / model: Apple
* Device: iPad with iOS 13.3, iPhone6s with iOS 13.3, iPhone 6 with iOS 12.3
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): iOS 5.1.1
* Plugin config

## Expected Behavior
Background fetch should run automatically in background and call the method that is into the #configure method of background fetch object

## Actual Behavior
When I tried to simulate background fetch from Debug menu of Xcode it will execute my method but it won't call this method t some period of time when I put the beside me and do some other stuffs in that device.

## Steps to Reproduce
1. Install plugin in app
2. Added background fetch configure method in constructor
3. In configure methods, I have call one method that will scheduled local notification for current day
4. When I installed app in my device and then I pressed Debug menu from Xcode, All things works well
5. But when I put device beside me and do some other stuffs in device, nothing will happen and also app won't refresh in background and obviously my  local notification won't be scheduled.

## Context
I am just trying to scheduled local notification for current day when app is in background state

## Debug logs (iOS XCode logs)
1. [Process] kill() returned unexpected error 1 
2. [ProcessSuspension] Background task expired while holding WebKit ProcessAssertion (isMainThread? 1).

**Comment by christocracy** [comment]
If it works in the simulator, that's **all you need to know**.  it can take *days* before iOS machine-learning model generates a pattern of behaviour for your app and begins firing the events on a regular basis.

This is been ask dozens of times, search the closed issues for "not firing", "not executing".
