### ISSUE TITLE
Testing headless fetch

### ISSUE THREAD

**Issue by mark-wallpapermatic** [transistorsoft/cordova-plugin-background-fetch#116]
Working on macOS and Android Studio, I am trying to trigger a headless fetch by simulating it with this command

`$ adb shell cmd jobscheduler run -f <your.application.id> 999`

Unfortunately, I could not seem to make it work as I could not find any log entries that BackgroundFetchHeadlessTask.java should be creating. Do you have any ideas on what I could be doing wrong?

**Comment by christocracy** [comment]
*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

  Provide a general summary of the issue in the Title above 

## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by mark-wallpapermatic** [comment]
### Environment
- Plugin version: 5.6.1
- Platform: Android
- OS version: 9.0 (Pie)
- Device manufacturer / model: Google Pixel (Emulator)
- Cordova version (cordova -v): 8.1.2
- Cordova platform version (cordova platform ls): android 8.1.0
- Plugin config

### Expected Behavior
Expecting to find log messages in logcat from BackgroundFetchHeadlessTask.java after running `$ adb shell cmd jobscheduler run -f <your.application.id> 999`

### Actual Behavior
Could not find any log messages in logcat from BackgroundFetchHeadlessTask.java. Simulating background fetch even does not seem to trigger BackgroundFetchHeadlessTask.java.

### Steps to Reproduce
1. Debug app from Android Studio
2. Close app in emulator
3. Run command `$ adb shell cmd jobscheduler run -f <your.application.id> 999` in terminal
4. Check logcat in Android Studio

**Comment by christocracy** [comment]
- Are you replacing `<your.application.id>` with your *actual* application id?
- What is the output of `$ adb logcat -s TSBackgroundFetch`?

**Comment by christocracy** [comment]
>Plugin config

**Comment by mark-wallpapermatic** [comment]
### Plugin Config
```
cbf.configure(cordovaBackgroundFetch, err => console.log, {
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        requiredNetworkType: cbf.NETWORK_TYPE_ANY
    });
```

> * Are you replacing `<your.application.id>` with your _actual_ application id?

Yes

> * What is the output of `$ adb logcat -s TSBackgroundFetch`?
```
onFetch -- DEFAULT IMPLEMENTATION
01-20 11:09:33.935  5539  5539 D TSBackgroundFetch: - finish
01-20 11:09:33.935  5539  5539 D TSBackgroundFetch: HeadlessJobService jobFinished
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch: - configure: {
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "minimumFetchInterval": 15,
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "stopOnTerminate": false,
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "requiredNetworkType": 1,
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "requiresCharging": false,
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "requiresDeviceIdle": false,
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "requiresStorageNotLow": false,
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "startOnBoot": true,
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "forceReload": false,
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch:   "jobService": "com.transistorsoft.cordova.backgroundfetch.HeadlessJobService"
01-20 11:09:36.373  5539  5700 D TSBackgroundFetch: }
01-20 11:09:36.378  5539  5700 D TSBackgroundFetch: - start
```

**Comment by christocracy** [comment]
I see in your logs:
```
onFetch -- DEFAULT IMPLEMENTATION
```

Which is coming [from the default implementation contained in the plugin](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/src/android/BackgroundFetchHeadlessTask.java#L15).

It seems you've made a mistake in the [Headless Fetch Setup](https://github.com/transistorsoft/cordova-plugin-background-fetch#headless-fetch-setup) and failed to have your custom `BackgroundFetchHeadlessTask.java` copied into the android app.

**Comment by mark-wallpapermatic** [comment]
I've reviewed the headless fetch setup

BackgroundFetchHeadlessTask.java 
```
package com.transistorsoft.cordova.backgroundfetch;
import android.content.Context;
import com.transistorsoft.tsbackgroundfetch.BackgroundFetch;
import android.util.Log;

public class BackgroundFetchHeadlessTask implements HeadlessTask {
    @Override
    public void onFetch(Context context) {
        Log.d(BackgroundFetch.TAG, "My BackgroundFetchHeadlessTask:  onFetch");
        Log.d(BackgroundFetch.TAG, "Pinging from background headless");
        Log.d("wallpapermatic", "Pinging from headless background fetch");
        // Perform your work here.

        // Just as in Javascript callback, you must signal #finish
        BackgroundFetch.getInstance(context).finish();
    }
}
```
config.xml 
```
<platform name="android">
    <allow-intent href="market:*" />
    <resource-file src="os/android/BackgroundFetchHeadlessTask.java" target="src/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java" />
</platform>
```
I also checked the build files in `/platforms/android/src/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java` and I can confirm that it is indeed the java file I pasted above.

Having done that, I'm still getting `01-22 09:56:08.606  6121  6121 D TSBackgroundFetch: BackgroundFetchHeadlessTask onFetch -- DEFAULT IMPLEMENTATION`

What am I missing or doing wrong?

**Comment by christocracy** [comment]
Showing your class file is irrelevant since it’s not being copied into the source.  The problem is in your Config.xml

**Comment by mark-wallpapermatic** [comment]
Here's my entire config.xml. Not sure what you mean by not being copied into the source, but after running `cordova build android` the class file is indeed being copied to `/platforms/android/src/com/transistorsoft/cordova/backgroundfetch`

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.wallpapermatic.app" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Wallpapermatic</name>
    <description>
        Wallpapermatic Client App
    </description>
    <author email="mark@wallpapermatic.com" href="https://wallpapermatic.com">
        Wallpapermatic
    </author>
    <content src="app.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <icon src="www/static/assets/app-icon-1024.png" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
        <resource-file src="os/android/BackgroundFetchHeadlessTask.java" target="src/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <preference name="AndroidPersistentFileLocation" value="Internal" />
    <preference name="iosPersistentFileLocation" value="Library" />
    <plugin name="cordova-plugin-device" spec="^2.0.3" />
    <plugin name="cordova-plugin-wallpaper" spec="https://github.com/mark-wallpapermatic/cordova-plugin-wallpaper.git" />
    <plugin name="cordova-plugin-background-fetch" spec="^5.6.1" />
    <plugin name="cordova-plugin-file" spec="^6.0.2" />
    <plugin name="cordova-plugin-service-task" spec="../cordova-plugin-service-task" />
    <engine name="ios" spec="^5.1.0" />
    <engine name="android" spec="^8.1.0" />
</widget>
```

**Comment by christocracy** [comment]
Check your src after running `cordova build android`

**Comment by lucasssv** [comment]
same problem here

**Comment by christocracy** [comment]
@lucasssv without any information, “me too” response is useless.

**Comment by lucasssv** [comment]
I already made all the settings, my "BackgroundFetchHeadlessTask" is being copied to the target, but when executing this, the DEFAULT IMPLEMENTATION is displayed

**Comment by christocracy** [comment]
The purpose of the setup instructions is to *copy over* the default implementation file.

If you see “default implementation” in logs, the default class file was not copied over.

**Comment by mark-wallpapermatic** [comment]
@christocracy how do we verify if the default class was copied over? Looking at `src/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java` after running `cordova build android` I can confirm that it is indeed my custom file. Unfortunately I'm still getting `DEFAULT IMPLEMENTATION` in the logs.

**Comment by christocracy** [comment]
I don’t know.  Try cleaning your Android build.

**Comment by ckamil** [comment]
Hello, I have the same issue as @mark-wallpapermatic, I tested on 5.6.1 and 6.0.2 with the same effect:
BackgroundFetchHeadlessTask onFetch -- DEFAULT IMPLEMENTATION

Environment
    Plugin version: 5.6.1 and 6.0.2
    Platform: Android
    OS version: 8.1
    Device manufacturer / model: Google Pixel (Emulator)
    Cordova version (cordova -v): 9.0.0
    Cordova platform version (cordova platform ls): android 8.1.0

My config.xml It contained
<resource-file src="os/android/BackgroundFetchHeadlessTask.java" target="src/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java" />

and existed file:
platforms/android/src/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java

I solved the problem by replacing the path in target attribute, probably it is not a best solution, but it works:
<resource-file src="src/android/BackgroundFetchHeadlessTask.java" target="app/src/main/java/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java" />

I have now:
My BackgroundFetchHeadlessTask:  onFetch: cordova-background-fetch

**Comment by christocracy** [comment]
There was an error in the setup docs `target`.  The correct target is as you say @ckamil.

```xml
<resource-file src="src/android/BackgroundFetchHeadlessTask.java" target="app/src/main/java/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java" />
```

The README has been updated.
