### ISSUE TITLE
Android - run only once

### ISSUE THREAD

**Issue by matodrobec** [transistorsoft/cordova-plugin-background-fetch#117]
## Your Environment
* Plugin version: cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
* Platform: Android
* OS version: 9
* Device manufacturer / model:
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config
01-21 17:20:32.798 15869 15946 W TSBackgroundFetch: - Configuration error:  {forceReload: false, jobService: null} is incompatible with stopOnTerminate: false:  Enforcing stopOnTerminate: true.
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch: - configure: {
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch:   "minimumFetchInterval": 15,
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch:   "stopOnTerminate": true,
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch:   "requiredNetworkType": 0,
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch:   "requiresCharging": false,
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch:   "requiresDeviceIdle": false,
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch:   "requiresStorageNotLow": false,
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch:   "startOnBoot": false,
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch:   "forceReload": false
01-21 17:20:32.798 15869 15946 D TSBackgroundFetch: }

## Expected Behavior

The code should run every time when run `adb shell cmd jobscheduler run -f  io.ionic.starter 999`

```
initBackgroundFetch() {
    const config: BackgroundFetchConfig = {
      stopOnTerminate: false,
    }

    this.backgroundFetch
      .configure(config)
      .then((_) => {
        console.log('Background Fetch initialized', _);
        this.backgroundFetch.finish();
        // this.backgroundFetch.stop();
        // this.initBackgroundFetch();
      })
      .catch(e =>
        console.log('Error initializing background fetch', e)
      );
  }
```
- output of ` adb logcat -s TSBackgroundFetch`
```
01-21 17:22:52.110 18088 18167 W TSBackgroundFetch: - Configuration error:  {forceReload: false, jobService: null} is incompatible with stopOnTerminate: false:  Enforcing stopOnTerminate: true.
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch: - configure: {
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch:   "minimumFetchInterval": 15,
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch:   "stopOnTerminate": true,
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch:   "requiredNetworkType": 0,
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch:   "requiresCharging": false,
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch:   "requiresDeviceIdle": false,
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch:   "requiresStorageNotLow": false,
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch:   "startOnBoot": false,
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch:   "forceReload": false
01-21 17:22:52.110 18088 18167 D TSBackgroundFetch: }
01-21 17:22:52.113 18088 18167 D TSBackgroundFetch: - start
01-21 17:23:01.540 18088 18088 D TSBackgroundFetch: - Background Fetch event received
01-21 17:23:01.551 18088 18167 D TSBackgroundFetch: - finish
01-21 17:23:01.551 18088 18167 D TSBackgroundFetch: - jobFinished
01-21 17:23:05.367 18088 18088 D TSBackgroundFetch: - Background Fetch event received
```
As you can see the finish and jobFinished is not in log second time.

## Actual Behavior

If I uncomented these two lines from code above
```
        // this.backgroundFetch.stop();
        // this.initBackgroundFetch();
```
Then It is working as I expected and I got always notification each time when I run   `adb logcat -s TSBackgroundFetch`

I have same problem when I am testing it in real world. First time I got notification till 15 min but then i never got secound time the notification. What am I doing wrong?

Thank you.

**Comment by christocracy** [comment]
Why would you do this in the fetch handler?  It’s weird.  Why would call #configure twice?  Just don’t.

this.backgroundFetch.stop();
this.initBackgroundFetch();

After calling #stop, you’d have to call #start again.

**Comment by kenibarwick** [comment]
I have a similar issue in that the background fetch runs once only

**Comment by christocracy** [comment]
@kenibarwick you are providing no information.

**Comment by kenibarwick** [comment]
@christocracy 
https://github.com/kenibarwick/background-fetch-test

I've been attempting to use the plug in within my app, to no avail, so I wrote a simple blank Ionic app with the sole purpose of getting the plug in to work. 

That repo is above

I debug the app using VS code and can see after just shy of 15 minutes the "Background Fetch initialized" log arrive, but it never fires after that one time.

What do you think I am doing wrong please?

thanks

**Comment by christocracy** [comment]
@kenibarwick 

Provide a general summary of the issue in the Title above 
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
- include iOS / Android logs
- ios XCode logs, 
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat

**Comment by matodrobec** [comment]
Hi @christocracy ,

the ionic-native/background-fetch/ngx implementation is only promise. I am switch to your implementation and I got always result

```
// import { BackgroundFetch as IonicBackgroundFetch, BackgroundFetchConfig } from '@ionic-native/background-fetch/ngx';
import BackgroundFetch from "cordova-plugin-background-fetch";

initBackgroundFetch() {
    BackgroundFetch.configure(
      () => {
        console.log('Background Fetch initialized');
        BackgroundFetch.finish();
        
      },
      (error) => {
        console.log('Error initializing background fetch', error)
      },
      {
        // Set true to cease background-fetch from operating after user "closes" the app. Defaults to true.
        stopOnTerminate: false,
      }
    );
  }
```

Nice work.

Thank you
