### ISSUE TITLE
[Question] How long may the callback function execute?

### ISSUE THREAD

**Issue by anthonyg-passport** [transistorsoft/cordova-plugin-background-fetch#119]
Regarding the docs: "Background Fetch is a very simple plugin for iOS & Android which will awaken an app in the background about every 15 minutes, providing a **short period** of background running-time."

Is there a defined limit to how long my callback function can take to execute? Can I await some asynchronous action like an HTTP response or DB query and safely assume it will resolve before the thread is locked?

**Comment by christocracy** [comment]
30s

**Comment by christocracy** [comment]
You have 30s to call #finish.
