### ISSUE TITLE
How to execute code when app is terminated.

### ISSUE THREAD

**Issue by pournima12** [transistorsoft/cordova-plugin-background-fetch#120]
@christocracy 
Hi,
I have to call some API methods in custom callback function and also have to insert data into local db when app is terminated or in background. In my case task is scheduling only when app is minimized.
Please provide solution for this. Thanks in advance.

Following are code snippets:

     function syncOnlineDB(){    // some database related tasks or API calls

        }

    document.addEventListener("deviceready", function() {

            var BackgroundFetch = window.BackgroundFetch;
           
            // Your background-fetch handler.
            var fetchCallback = function() {
              console.log('[js] BackgroundFetch event received: ', );

               syncOnlineDB(); // call function
           
         };

            BackgroundFetch.finish();
            var failureCallback = function(error) {
              console.log('- BackgroundFetch failed', error);
            };
           
            BackgroundFetch.configure(fetchCallback, failureCallback, {
                enableHeadless: true,    // <-- enable Headless mode
                stopOnTerminate: false,  
                minimumFetchInterval: 15 // <-- default is 15
            });
    }, false);

## Your Environment
* Plugin version: 6.0.1
* Platform: Android
* OS version: 7
* Device manufacturer / model: i-ball tab
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`):9.0.0
* Plugin config

## Expected Behavior
after every 15 min call syncOnlineDB() to insert data into local db or make API calls

## Actual Behavior
nothing is happening. no task done.

##logs 
02-25 15:32:24.318 18209 18209 D TSBackgroundFetch: - Background Fetch event received
02-25 15:32:24.325 18209 18209 D TSBackgroundFetch: - finish
02-25 15:32:24.325 18209 18209 D TSBackgroundFetch: - jobFinished
02-25 15:32:24.447 18209 18209 D TSBackgroundFetch: HeadlessJobService onStartJob
02-25 15:32:24.447 18209 18209 D TSBackgroundFetch: BackgroundFetchHeadlessTask onFetch -- DEFAULT IMPLEMENTATION
02-25 15:32:24.447 18209 18209 D TSBackgroundFetch: - finish
02-25 15:32:24.447 18209 18209 D TSBackgroundFetch: HeadlessJobService jobFinished
02-25 15:45:00.849 18209 18209 D TSBackgroundFetch: - Background Fetch event received
02-25 15:45:00.852 18209 18209 D TSBackgroundFetch: - finish
02-25 15:45:00.852 18209 18209 D TSBackgroundFetch: - jobFinished
02-25 15:45:00.987 18209 18209 D TSBackgroundFetch: HeadlessJobService onStartJob
02-25 15:45:00.987 18209 18209 D TSBackgroundFetch: BackgroundFetchHeadlessTask onFetch -- DEFAULT IMPLEMENTATION
02-25 15:45:00.987 18209 18209 D TSBackgroundFetch: - finish
02-25 15:45:00.987 18209 18209 D TSBackgroundFetch: HeadlessJobService jobFinished

## Context
**I have to call functions(Which has specific tasks like fetch data from server etc.) for every 15 min.**

**Comment by christocracy** [comment]
See readme [enableHeadless](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/README.md#config-boolean-enableheadless-false).

It can only be done with Java code.

**Comment by stefanotauriello** [comment]
> See readme [enableHeadless](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/README.md#config-boolean-enableheadless-false).
> 
> It can only be done with Java code.

How Can I use angular/js variables in Java code?

**Comment by christocracy** [comment]
You can’t.  You’d have to somehow get those   Bats stored in Android SharedPreferences (Sort of like localStorage for Android) There’s probably a Cordova plugin that implements SharedPreferences.

**Comment by pournima12** [comment]
I have followed readme enableHeadless and did exactly what has said in it but I'm getting this default logs -

**02-25 15:45:00.987 18209 18209 D TSBackgroundFetch: BackgroundFetchHeadlessTask onFetch -- DEFAULT IMPLEMENTATION**

I think  src/android/BackgroundFetchHeadlessTask.java is not running. Because I'm not able to see this logs
Log.d(BackgroundFetch.TAG, "My BackgroundFetchHeadlessTask:  onFetch: " + taskId);

**Comment by christocracy** [comment]
@pournima12 your code is incorrect for v6 of the plugin.  See the [CHANGELOG](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/CHANGELOG.md#breaking-changes).  You must provide `taskId` to `#finish` now.  Please re-install the plugin from scratch and carefully review the setup.
