### ISSUE TITLE
Need to update android.support package import to androidx

### ISSUE THREAD

**Issue by jacobg** [transistorsoft/cordova-plugin-background-fetch#121]
https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/d7b1fec8d2e5dd69767921961fba85b91d9521be/src/android/CDVBackgroundFetch.java#L17

Compilation fails when AndroidX is enabled, with this error:
```
src-cordova/platforms/android/app/src/main/java/com/transistorsoft/cordova/backgroundfetch/CDVBackgroundFetch.java:17: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
```

Instead it should import:
```
import androidx.annotation.Nullable;
```

However, actually the import is not used at all, so it and two other imports should just be removed:
<img width="294" alt="Screen Shot 2020-02-27 at 12 06 44 PM" src="https://user-images.githubusercontent.com/736985/75467446-a6958680-5959-11ea-8874-e56a68ab4135.png">

**Comment by christocracy** [comment]
Thanks, imports removed.  Published to `6.0.3`
