### ISSUE TITLE
Geolocation show timeout expired in background. 

### ISSUE THREAD

**Issue by maniwebertech** [transistorsoft/cordova-plugin-background-fetch#122]
## Updated
I have tried to remove these options:

start on boot: true,
stopOnTerminate: false

but still the same.

## My Code
```
background_fetch.configure($scope.backgroundTask, $scope.backgroundFailure, {
    minimumFetchInterval: 15,
    startOnBoot: true,
    stopOnTerminate: false
 });

$scope.backgroundFailure = function(error) {
      $cordovaLocalNotification.schedule({
        id: Math.floor(100000 + Math.random() * 900000),
        title: "Background Fetch Service",
        text: "The following error occurred: " + error + ".",
        icon: PUSH_ICON,
        foreground: true
      });
  };

$scope.backgroundTask = function(taskId ) {
      Location.getLocation().then(function(position) {
          //this never gets called

      },
      function(error) {
                //alert("14");
              //this get called and shows timeout expired push
                $cordovaLocalNotification.schedule({
                  id: Math.floor(100000 + Math.random() * 900000),
                  title: "Location Permission",
                  text: "You need to share your location in order to use this app. The following error occurred: " + error.message + '.',
                  icon: PUSH_ICON,
                  foreground: true
                });
              }
       );
};

```

## Your Environment
* Plugin version: 
```

cordova-plugin-background-fetch 6.0.3 "CDVBackgroundFetch"

```

* Platform: Android
* OS version: 8.0
* Device manufacturer / model: Huawei 
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): 
Installed platforms:
  android 8.1.0
Available platforms:

```

  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0

```

* Plugin config:

 ```
    minimumFetchInterval: 15,
    startOnBoot: true,
    stopOnTerminate: false
```
## Expected Behavior

The location permission is already assigned. It should get it and store in the database. 

## Actual Behavior

It shows Timeout expired after 15 minutes. 

## Context

I was trying to save geolocation every 15 minutes to the local database.

**Comment by christocracy** [comment]
> Plugin version: latest

It’s meaningless to the future.

**Comment by maniwebertech** [comment]
I have just downloaded the plugin from git repository.

**Comment by maniwebertech** [comment]
I used this command in ionic cordova root:

cordova plugin add cordova-plugin-background-fetch

**Comment by christocracy** [comment]
Do you know that the command `cordova plugins` will show you a list of all installed plugins, including their version?

You could also look at the package.json of the plugin installed into your node_modules.

**Comment by maniwebertech** [comment]
Ok its 6.0.3

**Comment by christocracy** [comment]
Please edit your original post and append to *Plugin version*

**Comment by maniwebertech** [comment]
I have added more details.

**Comment by maniwebertech** [comment]
> Please edit your original post and append to _Plugin version_

Did that.

**Comment by christocracy** [comment]
The background-fetch plugin is not responsible for what you do inside the callback.  The plugin is responsible for executing the callback.  If the callback executes, the plugin has fulfilled its responsibility.

BackgroundFetch is not involved with your `Location` code.
