### ISSUE TITLE
Cordova/Ionic/Angular/PGB - BackgroundTask.h not found when building to PhoneGap Build

### ISSUE THREAD

**Issue by dansolhan** [transistorsoft/cordova-plugin-background-fetch#123]
Having some issues with otherwise seemingly sublime background-fetch plugin. Please let me know if there are some information missing. Thanks a bunch!

## Your Environment
* Plugin version: npm 6.0.3
* Platform: iOS (works on Android)
* OS version: Unsure, but Xcode version 10.1
* Device manufacturer / model: N/A
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): 5.0.1
* Plugin config: `<plugin name="cordova-plugin-background-fetch" source="npm" />`

## Expected Behavior
Builds correctly on both iOS and Android.

## Actual Behavior
iOS build fails.

The following error is generated by Phonegap Build: `Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-background-fetch`

## Steps to Reproduce

1. run `ionic cordova plugin add cordova-plugin-background-fetch`
2. Ensure config.xml has the following entry ` <plugin name="cordova-plugin-background-fetch" source="npm" />`
3. Ensure 'cordova-plugin-background-fetch' exists as an entry in package.json
4. Build to Phonegap Build.

## Context
Attempting to build iOS version of our app on PhoneGap Build. The Android version seems to build just fine.

## Debug logs
Relevant (I believe) parts: 

```
While building module 'TSBackgroundFetch' imported from /project/eCHANGE daniel/Plugins/cordova-plugin-background-fetch/CDVBackgroundFetch.m:9:
In file included from <module-includes>:1:
eCHANGE daniel/Plugins/cordova-plugin-background-fetch/TSBackgroundFetch.framework/Headers/TSBackgroundFetch.h:11:9: fatal error: 'BackgroundTasks/BackgroundTasks.h' file not found
#import <BackgroundTasks/BackgroundTasks.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
/project/eCHANGE daniel/Plugins/cordova-plugin-background-fetch/CDVBackgroundFetch.m:9:9: fatal error: could not build module 'TSBackgroundFetch'
#import <TSBackgroundFetch/TSBackgroundFetch.h>
 ~~~~~~~^
2 errors generated.

```
And finally:

`Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)`

**Comment by christocracy** [comment]
The new iOS 13 [`BackgroundTasks`](https://developer.apple.com/documentation/backgroundtasks?language=objc) api is available only in the latest XCode (v11).

Your issue is with PhoneGap.

**Comment by dansolhan** [comment]
That does explain a thing or two. Thanks a bunch!

**Comment by Vamsikri05** [comment]
@dansolhan Were you able to resolve this?

**Comment by christocracy** [comment]
@Vamsikri05 You need to ensure that PhoneGap is using XCode 11 to build.  Latest background-fetch is using  new [`BGTaskScheduler`](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler?language=objc) framework, which was introduced in iOS 13.  Only XCode 11+ is aware of iOS 13.
