### ISSUE TITLE
Question on BGTaskScheduler and simulation

### ISSUE THREAD

**Issue by alexhisen** [transistorsoft/cordova-plugin-background-fetch#124]
Readme seems to imply that to simulate a background-fetch event on iOS older than 13, you use the "Simulate Background Fetch" menu option in XCode, but on iOS 13, you must use execute the lldb command in console.

However, when I tried the lldb command from the Readme against an iOS 13.3 device, it errored with:
error: <user expression 0>:1:9: use of undeclared identifier 'BGTaskScheduler'

And it seems "Simulate Background Fetch" menu option in XCode still works.

Is the lldb command only meant to simulate custom tasks? Perhaps the documentation can be clarified on this.

Thanks.

**Comment by alexhisen** [comment]
An update. It turns out I was previously using an old version of the plugin. Using the current version, Simulate Background Fetch still works but using
```
e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.transistorsoft.fetch"]
```
in XCode console results in:
```
Error [IRForTarget]: Couldn't resolve the class for an Objective-C static method call
error: The expression could not be prepared to run in the target
```

**Comment by christocracy** [comment]
What version of XCode are you using?

**Comment by alexhisen** [comment]
11.4

**Comment by alexhisen** [comment]
Wait, this is an iOS 12 device. Let me try iOS 13 and get back to you.

**Comment by christocracy** [comment]
You can’t simulate an iOS 13 command upon an iOS 12 device.  That won’t happen in reality.

**Comment by alexhisen** [comment]
Yeah, ok, so on an iOS 13 device both the "Simulate Background Fetch" menu option and the lldb command work.
