### ISSUE TITLE
How to call systematically java code (onFetch method) ?

### ISSUE THREAD

**Issue by LudoWeb** [transistorsoft/cordova-plugin-background-fetch#125]
Hey @christocracy,

Thank you so much for this plugin, this helps me so much! 
I have implemented the headless fetch handler with Java code in Cordova.

This solution works perfectly only when app is closed. Is that the normal behaviour ? 
If the app is running, the JS callback works but my onFetch method (in backgroundFetchHeadlessTask class) is not called.

If this is the normal behaviour, do you know there is a simple to do that easily ?

Thanks,
Ludo

## Your Environment
* Plugin version: 6.0.1
* Platform: Android
* OS version: 7
* Device manufacturer / model: Huawei P20
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): 9.0.0

**Comment by christocracy** [comment]
What do you think headless *means*?

**Comment by LudoWeb** [comment]
Probably a running job worker without GUI ? 
Then, what do you advise for write a same logic when app is closed and when it's running ? Because now, i have the similar code in my **backgroundFetchHeadlessTask** and in my **JS callback response**.

Is there a simple way to factorize this only in a single location ?

**Comment by christocracy** [comment]
This is JavaScript 101:

```javascript
Import myCommonFetchTask from ‘./fetchTask’;
```

**Comment by LudoWeb** [comment]
Of course but is the JS callback response called even if app is closed ? I do not have the impression with my tests.

**Comment by christocracy** [comment]
Oh right.  This is Cordova.  Only React Native allows implementing one's headless-task in Javascript.  With Cordova, you must write your headless-task in *pure java*.  There's no possible way to share code between the Javascript fetch-task and the Android `BackgroundGeolocationHeadlessTask.java`.

**Comment by LudoWeb** [comment]
Thanks, in full java it works! 

Only this one seems to not work in my example: 
`"startOnBoot": true`

Do you have any tips to debug this ?

**Comment by christocracy** [comment]
- Are you *simulating* a fetch event?
- Are you *unlocking* the device after reboot?

**Comment by LudoWeb** [comment]
(1) No, but when I'm simulating a fetch event, i get this error : 

`04-27 17:43:04.202  1187  6695 D JobScheduler: Error executing JobStatus{813febf #u0a261/999 io.ionic.starter/com.transistorsoft.tsbackgroundfetch.FetchJobService u=0 s=10261 TIME=+12m37s252ms:+17m37s252ms PERIODIC PERSISTED READY}`

(2) Yes

**Comment by christocracy** [comment]
You can't simulate an event with `forceAlarmManager: true`.  Set it to false and try again.

**Comment by LudoWeb** [comment]
Yes, without forceAlarmManager, the fetch event works perfectly.

**Comment by LudoWeb** [comment]
Hey @christocracy,

I'm still searching a solution for this problem :(

### On app is killed, it works fine : 
`05-05 01:45:53.834  1180  1289 I ActivityManager: Start proc 9326:io.ionic.starter/u0a269 for service io.ionic.starter/com.transistorsoft.tsbackgroundfetch.FetchJobService`

### On phone is rebooted :
 
`05-05 01:47:43.520  1180  3474 D JobScheduler: Error executing JobStatus{38222af #u0a269/999 io.ionic.starter/com.transistorsoft.tsbackgroundfetch.FetchJobService u=0 s=10269 TIME=+14m26s394ms:+19m26s394ms PERIODIC PERSISTED READY}`

And few seconds later : 

`05-05 01:48:01.518  1180  1180 W JobServiceContext: Time-out while trying to bind 38222af #u0a269/999 io.ionic.starter/com.transistorsoft.tsbackgroundfetch.FetchJobService, dropping.`

Just to say that if you have any advice, I'm more than interrested!

**Comment by christocracy** [comment]
Works for me after reboot.

- After reboot you **must** first unlock the device.
- After some time (~30s) the Android `BootReceiver` will launch and re-register the fetch task.
- Only then, will the app respond to simulated fetch events.

**Comment by LudoWeb** [comment]
The `BootReceiver` seems to not re-register the fetch task after reboot - Do you have any logs on this event occurs ?

Should I have a `android.permission.RECEIVE_BOOT_COMPLETED` in my AndroidManifest ?

**Comment by christocracy** [comment]
>seems to not re-register the fetch task after reboot

It does for me on my Pixel 3a @ 10.0.0.

>Should I have a android.permission.RECEIVE_BOOT_COMPLETED in my AndroidManifest ?

No.  The plugin includes its own [`AndroidManifest.xml` with all the necessary elements](https://github.com/transistorsoft/transistor-background-fetch/blob/master/android/tsbackgroundfetch/src/main/AndroidManifest.xml#L4-L15), which are automatically merged into your app's `AndroidManifest.xml`.

You do not need to think about this.

See http://dontkillmyapp.com

**Comment by LudoWeb** [comment]
http://dontkillmyapp.com helps me.

I have a huawei P20 and their user advices seem to work for my case! Now, i will try to implement this in my code in order to workaround the problem : 

```
String tag = "com.my_app:LOCK";

if (Build.VERSION.SDK_INT == Build.VERSION_CODES.M && Build.MANUFACTURER.equals("Huawei")) { tag = "LocationManagerService"; }

PowerManager.WakeLock wakeLock = ((PowerManager) getSystemService(Context.POWER_SERVICE)).newWakeLock(1, tag); wakeLock.acquire();
```
