### ISSUE TITLE
problem at compilation for ios using phonegap build cordova v9.0.0

### ISSUE THREAD

**Issue by vromrom** [transistorsoft/cordova-plugin-background-fetch#126]
hello

trying to use background fetch plugin with ios (working perfectly well on android) but i get the error :

Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-background-fetch , 

* Plugin version: latest
* Platform: iOS
* OS version: cordova ios 5.0.0
* Cordova version : 9.0.0

## Steps to Reproduce
1. add into config.xml : <plugin name="cordova-plugin-background-fetch"/>
2. try to compile on https://build.phonegap.com

## Debug logs
The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/Testy-eoasvhmboqlmtygrcdtflkjtgejl/Build/Intermediates.noindex/ArchiveIntermediates/Testy/IntermediateBuildFilesPath/Testy.build/Release-iphoneos/Testy.build/Objects-normal/armv7/CDVBackgroundFetch.o Testy/Plugins/cordova-plugin-background-fetch/CDVBackgroundFetch.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by christocracy** [comment]
Duplicate #123.

**Comment by vromrom** [comment]
thank you !  and sorry again :(
