### ISSUE TITLE
Cordova PhoneGap build failing

### ISSUE THREAD

**Issue by Vamsikri05** [transistorsoft/cordova-plugin-background-fetch#127]
## Your Environment
* Plugin version: 6.0.7
* Platform: iOS
* OS version: 
* Device manufacturer / model:
* PhoneGap Version: cli-8.0.0 (4.5.4 / 7.0.0 / 5.0.0)
* Cordova platform version (`cordova platform ls`): 
* Plugin config : <plugin name="cordova-plugin-background-fetch" source="npm" />

## Expected Behavior
PhoneGap build should compile successfully.

## Actual Behavior
PhoneGap build is failing.

## Steps to Reproduce
Added the backgrounf-fetch plugin in the config.xml. Build compiles successfully without the plugin.

## Debug logs
** ARCHIVE FAILED **
The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/CAPI_Test-cqknrkzjpojvzqhanqxktllvedbg/Build/Intermediates.noindex/ArchiveIntermediates/CAPI\ Test/IntermediateBuildFilesPath/CAPI\ Test.build/Release-iphoneos/CAPI\ Test.build/Objects-normal/armv7/CDVBackgroundFetch.o CAPI\ Test/Plugins/cordova-plugin-background-fetch/CDVBackgroundFetch.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build-release.xcconfig,-workspace,CAPI Test.xcworkspace,-scheme,CAPI Test,-configuration,Release,-destination,generic/platform=iOS,-archivePath,CAPI Test.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHARED_PRECOMPS_DIR=/private/project/build/sharedpch,-UseModernBuildSystem=0

**Comment by christocracy** [comment]
Duplicate #123
