### ISSUE TITLE
Unable to execute code in the background with a basic Ionic/Angular project

### ISSUE THREAD

**Issue by user1337** [transistorsoft/cordova-plugin-background-fetch#132]
## Your Environment
* Plugin version:					^6.1.0
* Platform:						iOS
* OS version:						macOS Catalina version 10.15.4
* Device manufacturer / model:				11.2
* Cordova version:			9.0.0 (cordova-lib@9.0.1)
* Cordova platform version:
Installed platforms:
  								android 8.1.0
  								ios 5.1.1
							Available platforms:
 			 					browser ^6.0.0
  								electron ^1.0.0
  								osx ^5.0.0
  								windows ^7.0.0
* Plugin config:					Use with Ionic 6.3.0 with Angular

## Expected Behavior
Make the phone vibrate, when the background is activated.

## Actual Behavior
Doesn't seem to detect the background, and doesn't run the code

## Steps to Reproduce
1. Start a new Ionic project
2. Install the plugin
3. Put the code to make the app vibrate when the phone is on background
4. Put the app in background

## Context
Try to make it work with a basic code to see that we can execute code in the background.

## Code

    const config: BackgroundFetchConfig = {
      stopOnTerminate: false,
    }

    this.backgroundFetch
        .configure(config)
        .then(
          async () => {
              const status = JSON.stringify(await this.backgroundFetch.status);
              this._debugService.alertForObject(status, "configure - success");
              this._vibration.vibrate(4000);
              this.backgroundFetch.finish("io.ionic.starter.t1");
            },
            async error => {
              const status = JSON.stringify(await this.backgroundFetch.status);
              this._debugService.alertForObject(status, "configure - error");
              this._vibration.vibrate(4000);
            }
          )
        .catch(async e => {
            const status = JSON.stringify(await this.backgroundFetch.status);
            this._debugService.alertForObject(status, "configure - catch");
            this._vibration.vibrate(4000);
          });
  

    this.backgroundFetch
        .start()
        .then(
          async () => {
            const status = JSON.stringify(await this.backgroundFetch.status);
            this._debugService.alertForObject(status, "backgroundFetch - success");
            this._vibration.vibrate(4000);
          },
          async () => {
            const status = JSON.stringify(await this.backgroundFetch.status);
            this._debugService.alertForObject(status, "backgroundFetch - error");
            this._vibration.vibrate(4000);
          }
        )
        .catch(async e => {
          const status = JSON.stringify(await this.backgroundFetch.status);
          this._debugService.alertForObject(status, "backgroundFetch - catch");
          this._vibration.vibrate(4000);
        });

Also, the current documentation doesn't seem to match with the current version of the code.

Do we need to add the "task-identifier" in the "config.xml" ?
In the current version, we seem to not be able to specify a "task-identifier" ( BackgroundFetch.scheduleTask() )

**Comment by christocracy** [comment]
You are not implementing the plugin correctly.

Re-read the README and Setup Instructions.

**Comment by user1337** [comment]
Hmmm 
the current BackgroundFetch.configure() doesn't have the same Signature from the README
and BackgroundFetch.scheduleTask() doesn't seem to exists

**Comment by christocracy** [comment]
Are you *sure* you're using *this* plugin and not some old/out-dated ionic wrapper of it?

**Comment by user1337** [comment]
hmmmm, nice answer!
You are right, the lastest Ionic seem to not be updated.

I do
   import BackgroundFetch from 'cordova-plugin-background-fetch';
instead of this
  import { BackgroundFetch, BackgroundFetchConfig} from '@ionic-native/background-fetch'

the README methods seems to be reachable now   :D
now I will test the thing !

Thanks !

**Comment by christocracy** [comment]
Do not look to `@ionic` to install this plugin.  Remove everything related to that and follow the instructions in this readme.

**Comment by user1337** [comment]
hmmm, I am able to make the plugin work in Android, 
but not in iOS unfortunately.


I did try to replicate everything in the README for iOS:

- added the custom task in the "config.xml"
- make the call to "BackgroundFetch.finish(taskId)"
- the Phone is plugged into power


Here the code of the basic project :

https://github.com/user1337/ionic-background-fetch 
(the code simply, show message and vibrate on each run)

**Comment by jmesa-sistel** [comment]
I have same issue.
I can see on logs the task can proceed (dasd process) but javascript code is not executed. Seems webview is down or freeze and you cannot execute javascript code.
@christocracy Can you give as a simple working example?
@user1337 example is very simple and it is not working.
