### ISSUE TITLE
Caan not fetch geo location using cordova-plugin-background-fetch

### ISSUE THREAD

**Issue by shehanhasanga** [transistorsoft/cordova-plugin-background-fetch#133]
Ionic 3 / cordova 7.1.0
* Plugin version:4
* Platform: Android
* OS version: windows 10
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`8`):

` const config: BackgroundFetchConfig = {
            stopOnTerminate: false, // Set true to cease background-fetch from operating after user "closes" the app. Defaults to true.
        };

  this.BackgroundFetch.configure(config)
            .then(() => {
                console.log('Background Fetch initialized');
                this.getCurrentPosition();
                this.BackgroundFetch.finish();

            })
            .catch(e => console.log('Error initializing background fetch', e));
    }`

` getCurrentPosition(){
    this.geolocation.getCurrentPosition({enableHighAccuracy:true, maximumAge:600000, timeout:5000}).then(
        position => {
          console.log('setting map center from current location');
          console.log('lat = ', position.coords.latitude , 'lng = ',position.coords.longitude );
        },
        error => {
          console.error('ngui-map: Error finding the current position');
        }
    );

      // this.geolocation.getCurrentPosition(this.onMapSuccess, this.onMapError, { enableHighAccuracy: true });
  }`
Error initializing background fetch BackgroundGeolocation.

**Comment by christocracy** [comment]
Where did you get the idea that `BackgroundFetch.configure` returns a `Promise`?  It doesn’t.  You’re not using the `#configure` method correctly.

The proper way to use the plugin is documented in the README.  Follow the example exactly as documented.

**Comment by shehanhasanga** [comment]
https://ionicframework.com/docs/v3/native/background-fetch/

**Comment by christocracy** [comment]
That’s not my plugin.  That’s ionic’s old and crappy wrapper *of* my plugin.  Don’t use the Ionic wrapper.

Everything you need to know to use my plugin is in the readme.  Get rid of that Ionic wrapper and don’t look at those docs.

**Comment by shehanhasanga** [comment]
I have tried using your plugin.
`  onReady() {
        // Your background-fetch handler.
        let fetchCallback = (taskId)=> {
            console.log('[js] BackgroundFetch event received: ', taskId);
            this.getCurrentPositions();
            // Required: Signal completion of your task to native code
            // If you fail to do this, the OS can terminate your app
            // or assign battery-blame for consuming too much background-time
            BackgroundFetch.finish(taskId);
        };

        let failureCallback = (error)=> {
            console.log('- BackgroundFetch failed', error);
        };

        BackgroundFetch.configure(fetchCallback, failureCallback, {
            minimumFetchInterval: 15 // <-- default is 15
        });
        BackgroundFetch.start();
    }`

 But it does not work yet.  Error finding the current position

**Comment by christocracy** [comment]
Am I supposed to guess what that “error in getCurrentPosition” is or are you going to provide some interesting logs to look at
