### ISSUE TITLE
Error on post request

### ISSUE THREAD

**Issue by lozno** [transistorsoft/cordova-plugin-background-fetch#134]
## Your Environment
* Plugin version: 6.1.1
* Platform: Android
* OS version: 9
* Device manufacturer / model: 
* Cordova version (`cordova -v`): 
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
The app send post requests in background.

## Actual Behavior
The app only send post requests first 5 minutes. 

## Steps to Reproduce
        var BackgroundFetch = window.BackgroundFetch;

        // Your background-fetch handler.
        var fetchCallback = function(taskId) {
            console.log('[js] BackgroundFetch event received: ', taskId);

            $.ajax({
                url: 'http://192.168.1.39/data.php?longitude=' + lon + '&latitude=' + lat,
                dataType: 'text',
                type: 'get',
                contentType: 'application/json',
                timeout: 3000,
                success: function(){
                    console.log("Finish query");
                    BackgroundFetch.finish(taskId);
                },
                error: function( error ){
                    console.log("Error");
                    BackgroundFetch.finish(taskId);
                    console.log( error );
                }
            });
            
        };
        
        var failureCallback = function(error) {
            console.log('- BackgroundFetch failed', error);
        };
        
        BackgroundFetch.configure(fetchCallback, failureCallback, {
            minimumFetchInterval: 1, // <-- default is 15
            requiredNetworkType: BackgroundFetch.NETWORK_TYPE_ANY,
            forceAlarmManager: true
        });

## Context
Send my position to server

## Debug logs
[INFO:CONSOLE(69)] "[js] BackgroundFetch event received:  cordova-background-fetch"
[INFO:CONSOLE(78)] "Finish query"
[INFO:CONSOLE(69)] "[js] BackgroundFetch event received:  cordova-background-fetch"
[INFO:CONSOLE(78)] "Finish query"
[INFO:CONSOLE(69)] "[js] BackgroundFetch event received:  cordova-background-fetch"
[INFO:CONSOLE(78)] "Finish query"
[INFO:CONSOLE(69)] "[js] BackgroundFetch event received:  cordova-background-fetch"
[INFO:CONSOLE(69)] "[js] BackgroundFetch event received:  cordova-background-fetch"
[INFO:CONSOLE(69)] "[js] BackgroundFetch event received:  cordova-background-fetch"

**Comment by christocracy** [comment]
Where are you getting the location from?

**Comment by lozno** [comment]
https://www.npmjs.com/package/@mauron85/cordova-plugin-background-geolocation

**Comment by lozno** [comment]
More information (versions and plugins):

"@mauron85/cordova-plugin-background-geolocation": "^3.1.0",
"cordova-android": "^8.1.0",
"cordova-browser": "^6.0.0",
"cordova-plugin-androidx": "^2.0.0",
"cordova-plugin-androidx-adapter": "^1.1.1",
"cordova-plugin-background-fetch": "^6.1.1",
"cordova-plugin-power-optimization": "0.0.4",
"cordova-plugin-x-toast": "^2.7.2"

The location isn't a problem, I try to send 'http://192.168.1.39/data.php?longitude=0&latitude=0' with the same result, only work during 5 minutes.

**Comment by lozno** [comment]
When the app return to foreground the get requests send all at the same time.

[INFO:CONSOLE(69)] "[js] BackgroundFetch event received: cordova-background-fetch"
[INFO:CONSOLE(69)] "[js] BackgroundFetch event received: cordova-background-fetch"
[INFO:CONSOLE(69)] "[js] BackgroundFetch event received: cordova-background-fetch"
--> Go to foreground
[INFO:CONSOLE(78)] "Finish query"
[INFO:CONSOLE(78)] "Finish query"
[INFO:CONSOLE(78)] "Finish query"
[INFO:CONSOLE(78)] "Finish query"
.....

**Comment by IanMcGhie** [comment]
"@mauron85/cordova-plugin-background-geolocation": "^3.1.0"

Was not developed by Transistorsoft.
You are using a GPS library written by mauron85

-Ian

**Comment by lozno** [comment]
My question is about "cordova-plugin-background-fetch": "^6.1.1". not about geolocation plugin.

**Comment by shayanaijaz** [comment]
Having the same issue. Background fetch event is received in the logs but the post request is only executed when app is opened

**Comment by zmoshansky** [comment]
@lozno I've recently had success by ensuring that my `background fetch` task spawns a foreground service first (There's a cordova plugin for it). On newer versions of android, I believe this affects whether you'll have network/async in the background.

**Comment by symun92** [comment]
I can see that in your code minimumFetchInterval: 1
Is it possible to make the Interval time as like 1 minute?

**Comment by christocracy** [comment]
> Is it possible to make the Interval time as like 1 minute?

No.

**Comment by symun92** [comment]
> > Is it possible to make the Interval time as like 1 minute?
> 
> No.

Thank you for the quick reply.
I need to make an interval after every 1 minutes when app in background.
How can I do that? Do you have any idea or suggestion?

**Comment by christocracy** [comment]
You can’t develop a mobile app in the same manner as a web app running on a desktop plugged into ac power.

You can do this on Android only with `forceAlarmManager: true`.  It will still be subject to Android doze mode so is not guaranteed to always respect your 1 minute interval while the device is sitting idle for long periods of time.  You **will** consume **a lot** of battery power.

On iOS :  **100% impossible**.

**Comment by ReneDyhr** [comment]
I got this issue as well. I got the app open and then goes to home screen without terminating the app.
The background event fires but it stops at the post request in my Javascript code. Is it impossible to make requests from the app when it's in the background?
