### ISSUE TITLE
iOS - Background events never fire

### ISSUE THREAD

**Issue by TylerBrinks** [transistorsoft/cordova-plugin-background-fetch#135]
## Your Environment
* Plugin version: 6.1.1
* Platform: iOS
* OS version: 13.7
* Device manufacturer / model: Apple iPhone 11
* Cordova version (`cordova -v`): n/a using Ionic + Capacitor which supports Cordova
* Cordova platform version (`cordova platform ls`):  n/a using Ionic + Capacitor which supports Cordova
* Plugin config

## Expected Behavior
Background events fire when the app is not in the foreground

## Actual Behavior
No events fire

## Steps to Reproduce
Using Ionic 4 + Capacitor with TypeScript.  This is a simple 1 page demo app

Steps to reproduce include the setup outlined in the Capacitor setup at [](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/docs/INSTALL_CAPACITOR.md)

1. Import module into app.component.ts
`import BackgroundFetch from "cordova-plugin-background-fetch";`
2. On platform ready, configure BackgroundFetch to write to localStorage
```
BackgroundFetch.configure(async (taskId) => {
        console.log("BackgroundFetch with taskId: ", taskId);
        localStorage.setItem(Math.random().toString(),  Math.random().toString());
        BackgroundFetch.finish(taskId);

      }, async (status) => {
        console.log("BackgroundFetch failed");
        localStorage.setItem('failed ' + Math.random().toString(), 'failed ' + Math.random().toString());

      }, {
        minimumFetchInterval: 15,
        stopOnTerminate: false
      });
```
3. Run the app from XCode and verity BackgroundFetch is configured (via Safari debugger)
4. Put the app in the background and bring another app (or desktop) into the foreground
5. Wait 20 minutes; no entries are written to localStorage.  The plugin never fires the success or failure callback

## Context
Trying to run periodic tasks on iOS.  The BackgroundTask.swift and TSBackgroundFetch.h code within the iOS project do hit breakpoints, but nothing on the device triggers a background event.  

I am able run `e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.transistorsoft.fetch"]` to manually cause the events to fire from XCode

## Debug logs
020-10-13 08:59:04.776818-0600 Demo App[15817:6363703] [TSBackgroundFetch load]: (
)
2020-10-13 08:59:04.777246-0600 Demo App[15817:6363703] [TSBGAppRefreshSubscriber load]: {
    "cordova-background-fetch" = "<TSBGAppRefreshSubscriber identifier=cordova-background-fetch, executed=0, enabled=1>";
}
2020-10-13 08:59:04.960555-0600 Demo App[15817:6363703] WF: === Starting WebFilter logging for process Demo App
2020-10-13 08:59:04.960603-0600 Demo App[15817:6363703] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2020-10-13 08:59:04.960630-0600 Demo App[15817:6363703] WF: _WebFilterIsActive returning: NO
Loading network plugin
2020-10-13 08:59:05.014828-0600 Demo App[15817:6363703] CAPKeyboard: resize mode - native
⚡️  Loading app at capacitor://localhost...
Reachable via WiFi
APP ACTIVE
To Native Cordova ->  File requestAllPaths File1335509495 ["options": []]
⚡️  [log] - onscript loading complete
⚡️  WebView loaded
⚡️  [log] - Angular is running in the development mode. Call enableProdMode() to enable the production mode.
⚡️  [log] - Ionic Native: deviceready event fired after 222 ms
⚡️  [warn] - Native: tried calling StatusBar.styleDefault, but the StatusBar plugin is not installed.
To Native Cordova ->  BackgroundFetch configure BackgroundFetch1335509496 ["options": [{
    enableHeadless = 1;
    forceAlarmManager = 1;
    minimumFetchInterval = 15;
    stopOnTerminate = 0;
}]]
⚡️  [warn] - Install the StatusBar plugin: 'ionic cordova plugin add cordova-plugin-statusbar'
⚡️  [warn] - Native: tried calling SplashScreen.hide, but the SplashScreen plugin is not installed.
⚡️  [warn] - Install the SplashScreen plugin: 'ionic cordova plugin add cordova-plugin-splashscreen'
2020-10-13 08:59:05.541948-0600 Demo App[15817:6363703] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
⚡️  To Native ->  App addListener 52882312
SplashScreen.hideSplash: SplashScreen was automatically hidden after default timeout. You should call `SplashScreen.hide()` as soon as your web app is loaded (or increase the timeout). Read more at https://capacitorjs.com/docs/apis/splash-screen#hiding-the-splash-screen

**Comment by TylerBrinks** [comment]
I understand I don't need to wait as I described in the post. I am simulating the events via XCode successfully.  I would like to see them run on a device without the simulation.  So far I am unable to do so.  Is there a way to run the code without simulating the events?

**Comment by christocracy** [comment]
If it works with simulated event, that's all you need to know that everything is setup correctly.  Everything else is in the hands of iOS' secret algorithm.  It can take *days* before iOS settles into regularly scheduled events.  Also:
- if the user terminates your app, iOS halts fetch events.
- If the user doesn't open your app daily, iOS halts fetch events.

> Is there a way to run the code on a device with the OS triggering the events instead of simulating the events?

No.

**Comment by TylerBrinks** [comment]
Is there any difference in execution when using a scheduled task that's configured as Periodic?  Ultimately what I need is for a background process to run every so often, ideally with some kind of regular cadence.

**Comment by christocracy** [comment]
>Is there any difference in execution when using a Scheduled Task that's configured as Periodic?

Yes.  `scheduleTask` seems only to run when the device is plugged into power.  It is unreliable.  The traditional `fetch` event is *much* more reliable. 

>ideally with some kind of regular cadence.

Impossible with iOS.
