### ISSUE TITLE
Builds breaking for IOS

### ISSUE THREAD

**Issue by rahulinaction** [transistorsoft/cordova-plugin-background-fetch#136]
## Your Environment
* Plugin version: 5.6.1
* Platform: iOS 
* OS version: IOS 14.0
* Device manufacturer / model: Iphone 12 Pro Max Simulator
* Cordova version (`cordova -v`): cordova-cli 8.1.2 
* Cordova platform version (`cordova platform ls`): ios@5.1.1
* Plugin config

Getting this error while trying to generate build using the following command

ionic cordova build ios --release as it is used in an ionic project

Error:

/Plugins/cordova-plugin-background-fetch/TSBackgroundFetch.framework/TSBackgroundFetch(TSBackgroundFetch.o), building for iOS Simulator, but linking in object file built for iOS, file 'Plugins/cordova-plugin-background-fetch/TSBackgroundFetch.framework/TSBackgroundFetch' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Steps to Reproduce
1.ionic cordova platform add ios@5.1.1
2.ionic cordova plugin add cordova-plugin-background-fetch
3. ionic cordova build ios --release

-->

**Comment by christocracy** [comment]
```
$ cordova platform remove ios
$ cordova platform add ios
```

**Comment by rahulinaction** [comment]
Hi @christocracy actually the  builds are built freshly on a build service VM so there is no IOS platform prior to me adding the platform.  I still tried removing and then adding the platform after the platform was added and it doesn't change the output.

**Comment by christocracy** [comment]
Ensure your build service is using the latest version of XCode.
