### ISSUE TITLE
Capacitor - BackgroundFetch is not define

### ISSUE THREAD

**Issue by PIXPOINT** [transistorsoft/cordova-plugin-background-fetch#138]
## Your Environment
* Plugin version: 6.1.1
* Platform: Android
* OS version: 8.0.0
* Capacitor: 2.4.2

## Expected Behavior
I get the error message when I run the sample code. Error `Uncaught ReferenceError: BackgroundFetch is not defined`

## Actual Behavior
No error should appear

## Steps to Reproduce
```
import BackgroundFetch from "cordova-plugin-background-fetch";

let fetchCallback = function(taskId) {
    console.log('[js] BackgroundFetch event received: ', taskId);
    BackgroundFetch.finish(taskId);
};
let failureCallback = function(error) {
    console.log('- BackgroundFetch failed', error);
};
BackgroundFetch.configure(fetchCallback, failureCallback, {
    minimumFetchInterval: 15 // <-- default is 15
});
```

## Context
Using the sample Code, Ionic 2+ Example

## Debug logs
`Uncaught ReferenceError: BackgroundFetch is not defined`

**Comment by christocracy** [comment]
Did you follow the *Capacitor Setup* in the readme?

**Comment by PIXPOINT** [comment]
Yes, i followed: [https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/docs/INSTALL_CAPACITOR.md](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/docs/INSTALL_CAPACITOR.md)
