### ISSUE TITLE
minimumFetchInterval of Custom task is not configurable

### ISSUE THREAD

**Issue by TennGit** [transistorsoft/cordova-plugin-background-fetch#140]
## Your Environment
* Plugin version: 6.1.1
* Platform: Android
* OS version: 10
* Device manufacturer / model: Sony XZ3
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin config

`BackgroundFetch.configure(successfulFm, failureFn, {
        minimumFetchInterval: 30,
    })

BackgroundFetch.scheduleTask({
    taskId: 'com.transistorsoft.sync',
    requiresStorageNotLow: true,
    requiredNetworkType: BackgroundFetch.NETWORK_TYPE_ANY,
    periodic: true,
    delay: 30 * 60 * 1000,
    minimumFetchInterval: 50 (I believe the custom task doesn't consider minumumFetchInterval at all)
})

BackgroundFetch.scheduleTask({
    taskId: 'com.transistorsoft.replication',
    requiresStorageNotLow: true,
    requiredNetworkType: BackgroundFetch.NETWORK_TYPE_ANY,
    periodic: true,
    delay: 35 * 60 * 1000
})

const successfulFm = (taskId) => {
    try {
        if (taskId === 'com.transistorsoft.sync') {
            ... setSyncToBeFinished()
            return
        }

        if (taskId === 'com.transistorsoft.replication' && hasSyncFinished) {
            ...
            return
        }
    } catch (error) {
            return BackgroundFetch.finish(taskId)
    }
    return BackgroundFetch.finish(taskId)
}

`

## Expected Behavior
Should be able to configure the interval of custom tasks.
What I'd like to achieve is
1. Run custom tasks every 30 mins
2. When task sync finished, then signal task replication to continue. or just wait for 5 minutes to execute task replication

## Actual Behavior
1. minimumFetchInterval is always 15 mins
2. custom task doesn't seem to respect the value of delay. it triggers the custom task after 13 mins

## Context
I want to sync customer data, that consists of 2 parts(sync and replication), every 30 mins when the app is running on the background.

## Debug logs
11-26 22:16:23.406  5725  5859 D TSBackgroundFetch: - configure
11-26 22:16:23.406  5725  5859 D TSBackgroundFetch: - start
11-26 22:16:23.407  5725  5859 D TSBackgroundFetch: - registerTask: cordova-background-fetch
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch: {
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "taskId": "cordova-background-fetch",
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "isFetchTask": true,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "minimumFetchInterval": 30,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "stopOnTerminate": true,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "requiredNetworkType": 0,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "requiresCharging": false,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "requiresDeviceIdle": false,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "requiresStorageNotLow": false,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "startOnBoot": false,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "forceAlarmManager": false,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "periodic": true,
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch:   "delay": -1
11-26 22:16:23.411  5725  5859 D TSBackgroundFetch: }
11-26 22:16:23.417  5725  5725 D TSBackgroundFetch: - Background Fetch event received
11-26 22:16:23.418  5725  5859 D TSBackgroundFetch: - registerTask: com.transistorsoft.sync
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch: {
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "taskId": "com.transistorsoft.sync",
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "isFetchTask": false,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "minimumFetchInterval": 15,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "stopOnTerminate": true,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "requiredNetworkType": 1,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "requiresCharging": false,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "requiresDeviceIdle": false,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "requiresStorageNotLow": true,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "startOnBoot": false,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "forceAlarmManager": false,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "periodic": true,
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch:   "delay": 1800000
11-26 22:16:23.419  5725  5859 D TSBackgroundFetch: }
11-26 22:16:23.421  5725  5725 D TSBackgroundFetch: - Background Fetch event received
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch: - registerTask: com.transistorsoft.replication
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch: {
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "taskId": "com.transistorsoft.replication",
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "isFetchTask": false,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "minimumFetchInterval": 15,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "stopOnTerminate": true,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "requiredNetworkType": 1,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "requiresCharging": false,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "requiresDeviceIdle": false,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "requiresStorageNotLow": true,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "startOnBoot": false,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "forceAlarmManager": false,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "periodic": true,
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch:   "delay": 2100000
11-26 22:16:23.424  5725  5859 D TSBackgroundFetch: }
11-26 22:16:23.427  5725  5725 D TSBackgroundFetch: - Background Fetch event received

11-26 22:39:23.684  7686  7686 D TSBackgroundFetch: - Background Fetch event received
11-26 22:39:23.688  7686  7686 D TSBackgroundFetch: - Background Fetch event received
11-26 22:39:23.721  7686  7686 D TSBackgroundFetch: - Stopping on terminate
11-26 22:39:23.721  7686  7686 D TSBackgroundFetch: - stop: cordova-background-fetch
11-26 22:39:23.721  7686  7686 D TSBackgroundFetch: - jobFinished
11-26 22:39:23.723  7686  7686 I TSBackgroundFetch: - cancel taskId=cordova-background-fetch, jobId=999
11-26 22:39:23.733  7686  7686 D TSBackgroundFetch: - Stopping on terminate
11-26 22:39:23.733  7686  7686 D TSBackgroundFetch: - stop: com.transistorsoft.sync
11-26 22:39:23.733  7686  7686 D TSBackgroundFetch: - jobFinished
11-26 22:39:23.734  7686  7686 I TSBackgroundFetch: - cancel taskId=com.transistorsoft.sync, jobId=1582398754
11-26 22:39:23.744  7686  7686 D TSBackgroundFetch: - onStopJob
11-26 22:39:23.747  7686  7686 D TSBackgroundFetch: - onStopJob

11-26 22:44:49.403  7686  7686 D TSBackgroundFetch: - Background Fetch event received
11-26 22:44:49.404  7686  7686 D TSBackgroundFetch: - Stopping on terminate
11-26 22:44:49.404  7686  7686 D TSBackgroundFetch: - stop: com.transistorsoft.replication
11-26 22:44:49.404  7686  7686 D TSBackgroundFetch: - jobFinished
11-26 22:44:49.405  7686  7686 I TSBackgroundFetch: - cancel taskId=com.transistorsoft.replication, jobId=-1581348530
11-26 22:44:49.431  7686  7686 D TSBackgroundFetch: - onStopJob

**Comment by christocracy** [comment]
>minimumFetchInterval: 50 (I believe the custom task doesn't consider minumumFetchInterval at all)

Correct.  `minimumFetchInterval` doesn't apply `scheduleTask`.  Only `delay`

**Comment by TennGit** [comment]
So it will just run every 15 mins?
and it also shows in the console when the background task started

11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: {
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "taskId": "com.transistorsoft.sync",
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "isFetchTask": false,
**11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "minimumFetchInterval": 15,**
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "stopOnTerminate": true,
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "requiredNetworkType": 1,
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "requiresBatteryNotLow": false,
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "requiresCharging": false,
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "requiresDeviceIdle": false,
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "requiresStorageNotLow": true,
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "startOnBoot": false,
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "forceAlarmManager": false,
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "periodic": true,
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: "delay": 1800000
11-26 22:16:23.419 5725 5859 D TSBackgroundFetch: }

**Comment by christocracy** [comment]
The traditional iOS `fetch` task (automatically started when `.configure` is called) is far more reliable than `scheduleTask`, which only seems to run when a device is plugged into power.

The iOS `fetch` task is not guaranteed to run at exactly `minimumFetchInterval` (and likely won't).  It's based upon the operating system's own machine-learning algorithm, presumably based upon the frequency of app usage.  

- If the user doesn't open your app each day, the OS halts fetch tasks.
- If the user terminates your app, the OS halts fetch tasks.
