### ISSUE TITLE
API request stays `pending` until the OS kills the APP

### ISSUE THREAD

**Issue by TennGit** [transistorsoft/cordova-plugin-background-fetch#142]
## Your Environment
* Plugin version: 6.1.1
* Platform: Android
* OS version: 10
* Device manufacturer / model: SONY XP3
* Cordova version (`cordova -v`): 10
* Cordova platform version (`cordova platform ls`): 8.1.0
* Plugin config
minimumFetchInterval: 15,
requiresStorageNotLow: true,
requiredNetworkType: BackgroundFetch.NETWORK_TYPE_NOT_ROAMING,

## Expected Behavior
resolved API request

## Actual Behavior
Request doesn't resolve

## Steps to Reproduce

1. add following code in the project
```
const callbackFn = async (taskId) => {
  await fetch('https://jsonplaceholder.typicode.com/todos/1')  // no authentication needed
     .then((response) => response.json())
     .then((json) => console.log(json))
  return BackgroundFetch.finish(taskId)
}

BackgroundFetch.configure(callbackFn, failureFn, {
        minimumFetchInterval: 15,
        requiresStorageNotLow: true,
        requiredNetworkType: BackgroundFetch.NETWORK_TYPE_NOT_ROAMING,
    })
```

2. open the app and see the console indicating the background fetch is scheduled
3. put app to background and open remote inspection from chrome
4. HTTP `fetch` is launched but pending until the OS terminates the APP. (The connection is off between laptop and mobile)

## Context
Call an API when the app is running in the background

## Debug logs
TSBackgroundFetch: - Background Fetch event received

**Comment by christocracy** [comment]
I don't see your callback calling `BackgroundFetch.finish(taskId)`

**Comment by TennGit** [comment]
updated the code. forgot to add it.

**Comment by christocracy** [comment]
If you do not call `BackgroundFetch.finish(taskId)` to signal that your work is complete, iOS will no longer emit events as punishment.

**Comment by TennGit** [comment]
I meant I have BackgroundFetch.finish(taskId) in my project. but i forgot to add to the example code here.
the `fetch` is still pending

**Comment by christocracy** [comment]
I don't think you're using http `fetch(url)` properly with `async/await`.  See here:
https://dmitripavlutin.com/javascript-fetch-async-await/

**Comment by TennGit** [comment]
that seems to be fine
![image](https://user-images.githubusercontent.com/26920754/101808856-2373a480-3b17-11eb-8377-93e7221564e3.png)

**Comment by christocracy** [comment]
If you understand the linked article, you *won't be using* .`then`

**Comment by TennGit** [comment]
this is just to prove the combination of `await` and `then` is working.
actually when the first time background fetch runs when I open the app, the api is resolved properly
but when I put the app to background. after 15 mins, the same `fetch` code run again, it doesn't resolved anymore

**Comment by TennGit** [comment]
I am giving a shot for only the await and async now. but I think it won't change the result

**Comment by TennGit** [comment]
![image](https://user-images.githubusercontent.com/26920754/101825464-ea92fa00-3b2d-11eb-9f66-546af10c9ceb.png)
![image](https://user-images.githubusercontent.com/26920754/101825495-f7175280-3b2d-11eb-83cf-3257e2fac626.png)

so I use await/async only, this still happens. first time it resolved, second time when the app is running in the background, it's not

**Comment by TennGit** [comment]
until I open the APP again the `fetch` resolved instantly. change from `pending` to `200`
What would be the reason?

**Comment by christocracy** [comment]
No idea.  Remove your http request and test again.

**Comment by kgillespieatmosphere** [comment]
A bit of an FYI on this bug. We are noticing you get different behavior if your android device has USB Debugging Enabled and is connected to an active ADB session. 

The background requests do NOT get held up in pending, but as soon as USB debugging is off the holding up requests in "pending" behavior appears. It is quite frustrating.

We can see the pending requests because what we have been doing is, disconnecting from USB debugging, waiting a bit for a background fetch to fire off, then reconnect debugging and go to the chrome device inspector and connect to the app. We then can see the pending request waiting forever until the app gets foreground again

I am now testing if native HTTP plugins can make requests during the background fetch, but it is very difficult to debug as this issue only appears when you do not have debugging turned on. Also tried plugins that disable certain webview optimizations, no luck.

**Comment by christocracy** [comment]
>We are noticing you get different behavior if your android device has USB Debugging Enable

Good to know.

>I am now testing if native HTTP plugins can make requests during the background fetch

It will probably solve your issue.  My React Native and Flutter customers don't have this issue.  This seems Cordova/WebView related.

**Comment by ngocviet** [comment]
Hi @kgillespieatmosphere ,
Did you resolve the issue? I got the same issue with axios in ionic capacitor. The requests keep pending in background mode and all get resolve when the app activates.
Could you share your solution?
