### ISSUE TITLE
Get asset file or local storage from headless

### ISSUE THREAD

**Issue by ReneDyhr** [transistorsoft/cordova-plugin-background-fetch#143]
## Your Environment
* Plugin version: 6.1.1
* Platform: Android
* OS version: 9
* Device manufacturer / model: OnePlus
* Cordova version (`cordova -v`): 10
* Cordova platform version (`cordova platform ls`): android 9

## Context
I got the Headless java file to run in the given time I want to.
Though I can't figure out a way for the headless to access data from the app, either via a created file or localstorage from the cordova app itself.
What option do I have if I want to get access to a token for a user login? Is there another way to save it from the cordova app, to access it in the headless function?

**Comment by christocracy** [comment]
`localStorage` is a browser mechanism.  The native environment has no access to browser `localStorage`

The best way to share data between Javascript land and native Android land is via Android's [`SharedPreferences`](https://developer.android.com/training/data-storage/shared-preferences).

There seems to be plenty of [Cordova SharedPreferences](https://www.google.com/search?q=cordova+shared-prferences&rlz=1C5CHFA_enCA816CA816&oq=cordova+shared-prferences&aqs=chrome..69i57j0l3.5575j0j4&sourceid=chrome&ie=UTF-8) plugins available.
