### ISSUE TITLE
Run native java background task instead of having both headless java code and javascript code

### ISSUE THREAD

**Issue by ReneDyhr** [transistorsoft/cordova-plugin-background-fetch#144]
## Your Environment
* Plugin version: 6.1.1
* Platform: Android
* OS version: 9
* Device manufacturer / model: OnePlus
* Cordova version (`cordova -v`): 10
* Cordova platform version (`cordova platform ls`):android 9

## Context
Is there an option to run the java headless code instead of having to make the same code for both javascript and java when making background tasks?

**Comment by christocracy** [comment]
Sorry, no.

Users of React and Flutter, versions are more fortunate than Cordova, since the headless-task can be created in JavaScript and dart, respectively.

It's only Cordova where you must create the headless task in pure Java.
