### ISSUE TITLE
Are sources of com.transistorsoft.tsbackgroundfetch.BGTask available ?

### ISSUE THREAD

**Issue by laurentperez** [transistorsoft/cordova-plugin-background-fetch#149]
## Your Environment
* Plugin version: 0.5.0
* Platform: Android
* OS version:10
* Device manufacturer / model:Xiaomi Redmi note 9
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`):android 9.0.0
* Plugin config

## Expected Behavior

Sources of com.transistorsoft.tsbackgroundfetch.BGTask available ?

## Actual Behavior

While debugging my own BackgroundFetchHeadlessTask, I'm getting some errors within BGTask

like 03-10 12:13:59.258  9084  9084 W System.err: 	at com.transistorsoft.tsbackgroundfetch.BGTask.fireHeadlessEvent(BGTask.java:227)

but there is no source for BGTask at https://github.com/transistorsoft/cordova-plugin-background-fetch/tree/master/src/android/libs/com/transistorsoft/tsbackgroundfetch

if you unzip classes.jar of the AAR, you don't have .java files

so I don't know how to debug this line 227

license is MIT, are you publishing the sources ?

thanks, great project btw :)

**Comment by christocracy** [comment]
The source for `tslocationmanager` is [here](https://github.com/transistorsoft/transistor-background-fetch/blob/master/android/tsbackgroundfetch/src/main/java/com/transistorsoft/tsbackgroundfetch/BGTask.java#L227)

**Comment by laurentperez** [comment]
thank you :+1:
