### ISSUE TITLE
Could not find job 999 in package <packageid> / user 0

### ISSUE THREAD

**Issue by anonymuos1** [transistorsoft/cordova-plugin-background-fetch#150]
Hi!

I ran this command: adb shell cmd jobscheduler run -f <packageid> 999
(i changed package id)

And i got this message: Could not find job 999 in package <packageid> / user 0

I use android sdk 29

What the problem? Thank you for help!

04-21 18:15:25.564 13147 13260 D TSBackgroundFetch: [CDVBackgroundFetch] scheduleTask()
04-21 18:15:25.574 13147 13260 D TSBackgroundFetch: - registerTask: <task id>
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: {
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "taskId": "<task id>",
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "isFetchTask": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "minimumFetchInterval": 1,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "stopOnTerminate": true,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "requiredNetworkType": 0,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "requiresCharging": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "requiresDeviceIdle": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "requiresStorageNotLow": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "startOnBoot": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "forceAlarmManager": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "periodic": true,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch:   "delay": -1
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: }

**Comment by christocracy** [comment]
The issue template is **not optional**.  It's required.

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

  Provide a general summary of the issue in the Title above 
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by anonymuos1** [comment]
Sorry.

## Your Environment
* Plugin version: 7.0.1
* Platform: Android
* OS version: 7 and 10
* Device manufacturer / model: Samsung SM-G925F, Xiaomi Redmi Note 9
* Cordova version: 8.1.2
* Cordova platform version: android 8.0.0
* Plugin config:
{taskId: 'custom task id',  // <-- Your custom task-identifier
delay: 60 * 60 * 1000,  //  In one hour (milliseconds)
minimumFetchInterval: 15,
periodic: true}

## Expected Behavior
I want to test with custom trigger

## Actual Behavior

I ran this command: adb shell cmd jobscheduler run -f 999
(i changed package id)

And i got this message: Could not find job 999 in package / user 0

I use android sdk 29

What the problem? Thank you for help!

## Steps to Reproduce
1. run adb code
2. get error

## Context
I want to run adb process.

## Debug logs
04-21 18:15:25.564 13147 13260 D TSBackgroundFetch: [CDVBackgroundFetch] scheduleTask()
04-21 18:15:25.574 13147 13260 D TSBackgroundFetch: - registerTask:
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: {
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "taskId": "",
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "isFetchTask": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "minimumFetchInterval": 1,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "stopOnTerminate": true,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "requiredNetworkType": 0,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "requiresBatteryNotLow": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "requiresCharging": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "requiresDeviceIdle": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "requiresStorageNotLow": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "startOnBoot": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "forceAlarmManager": false,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "periodic": true,
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: "delay": -1
04-21 18:15:25.576 13147 13260 D TSBackgroundFetch: }
