### ISSUE TITLE
Documentation for use with React JS

### ISSUE THREAD

**Issue by ptmkenny** [transistorsoft/cordova-plugin-background-fetch#152]
## Your Environment
* Plugin version: 7.0.2
* Platform: both iOS and Android
* OS version: Windows 10 Pro
* Cordova version (`cordova -v`): Capacitor 3

## Expected Behavior

The README includes an example for React JS in addition to Angular.

## Actual Behavior

The README only has an example for Angular.

## Context

I have an Ionic v5 React app on iOS and Android, and I'm hoping to use this plugin to periodically fetch some data from my Drupal server.  I'm pretty well-versed in PHP but relatively new to React, and I don't have the skills to convert an Angular example into a React one.  Since React has create-react-app, it would be great if there was a simple example based on that showing how to use this plugin.

Where I got stuck specifically:

The Angular example has this code:

```
export class HomePage {
  constructor(public navCtrl: NavController, public platform: Platform) {
    this.platform.ready().then(this.onDeviceReady.bind(this));
  }
```

I don't know how to implement this in React.

**Comment by christocracy** [comment]
You don't need to worry about "Platform Ready" in React.

Just implement in `componentDidMount`.

**Comment by christocracy** [comment]
Btw, I'm working on implementing pure Capacitor adapters for both `background-fetch` and `background-geolocation`.

They'll be ready in a few weeks.

**Comment by SandeshVakale** [comment]
Hello @christocracy Can you provide an example for use with react.

@ptmkenny Did you manage to use this library with react? Can you please provide an example?

Thanks

**Comment by christocracy** [comment]
There's nothing particularly special about using with react.

`import` the plugin as any other module and implement in `componentDidMount`.
