### ISSUE TITLE
[iOS] [question] How to set up BGAppRefreshTask?

### ISSUE THREAD

**Issue by fujiokayu** [transistorsoft/cordova-plugin-background-fetch#155]
This is the same issue as the react native plugin issue, but let me check just in case.
- [[iOS] How to set up BGAppRefreshTask?](https://github.com/transistorsoft/react-native-background-fetch/issues/285)

I would like to use BGAppRefreshTask instead of BGProcessingTask in a Cordova app I am developing.
In the above issue you gave the following answer.

>Don’t think too much about it,
>
>Calling #configure == BGAppRefreshTssk

Does the default fetch event also use BGAppRefreshTask in the Cordova app?

thanks

**Comment by christocracy** [comment]
> Does the default fetch event also use BGAppRefreshTask in the Cordova app?

Yes.  it's literally the same native libs running under the hood as the RN version.
