### ISSUE TITLE
Is the cordova-plugin-background-fetch working for Android?

### ISSUE THREAD

**Issue by Lightk3ira** [transistorsoft/cordova-plugin-background-fetch#157]
## Your Environment
* Plugin version: Latest
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Zebra
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.1.0   browser 6.0.0    
* Plugin config

## Expected Behavior
The ionic documentation [here](https://ionicframework.com/docs/native/background-fetch) does not have Android listed as a supported OS. Our team has checked online and it appears some are using the package but some encounter issues. I noticed on your readme documentation [here](https://github.com/transistorsoft/cordova-plugin-background-fetch#debugging) that it looks likes Android should be supported on Ionic. 

## Actual Behavior
Our team is not sure if the package is supported by Ionic or not and if it is partially supported, which versions are supported and not supported for the use of this package.

## Steps to Reproduce
There are no steps as use of this package has been postponed until we have more information regarding the compatibility.

## Context
We are trying to use this package to perform background tasks for an Angular + Ionic application. Our devices used in the field are Android only. We want to understand the compatibility of this package before trying to incorporate it as we see conflicting documentation between the read me on this package and the ionic specific site documentation.

## Debug logs
There are no available logs.
-->
[config-xml.txt](https://github.com/transistorsoft/cordova-plugin-background-fetch/files/7444406/config-xml.txt)

**Comment by christocracy** [comment]
The Ionic package has nothing to do with this plugin.

Yes, this supports both iOS and Android.
