### ISSUE TITLE
configure error: the first argument to #configure is the Config {}

### ISSUE THREAD

**Issue by HussamBarbour** [transistorsoft/cordova-plugin-background-fetch#158]
## Your Environment
* Plugin version: 5.36.0
* Platform: iOS
* OS version: macOs 12.0.1

in app-comonents.ts

```
this.platform.ready().then(() => {
      if (this.platform.is('ios')){
        const config: BackgroundFetchConfig = {
          stopOnTerminate: false,
        }
      
        this.backgroundFetch.configure(config)
           .then(() => {
               console.log('Background Fetch initialized');
      
      
               alert('Background Fetch initialized'); 
           })
           .catch((e) => {
            alert('Error initializing background fetch' + e); 
            console.log('Error initializing background fetch', e)
          });
      }
    }
```

This error appears in the console log 

Error initializing background fetch" "[BackgroundFetch] configure error: the first argument to #configure is the Config {}

**Comment by christocracy** [comment]
Where in the api docs does it state that `BackgroundFetch.configure` returns a `Promise`?

**Comment by HussamBarbour** [comment]
I am using the Ionic framework
I did as in this link
https://ionicframework.com/docs/native/background-fetch

**Comment by christocracy** [comment]
This plugin has nothing to do with Ionic framework docs.

They have their own wrapper around a fork of my plugin.

To use this plugin, you consult the readme here.  That's all.

**Comment by christocracy** [comment]
Uninstall everything you did from ionic docs.  Start from scratch using the readme here.
