### ISSUE TITLE
Modify Status bar icon and description

### ISSUE THREAD

**Issue by PhilGauths** [transistorsoft/cordova-plugin-background-fetch#159]
## Your Environment
* Platform: Android
* OS version: SDK 24+
* Device manufacturer / model: Pixel
* Cordova version: 10.0.0
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior
Is there a way to specify status bar icon,background color, title and description?

## Actual Behavior
Launcher icon
TITLE is running in background

**Comment by christocracy** [comment]
The background-fetch plugin does not produce a toolbar icon.
