### ISSUE TITLE
Crash on Android from BGTask.fireHeadlessEvent

### ISSUE THREAD

**Issue by Leffe108** [transistorsoft/cordova-plugin-background-fetch#161]
## Your Environment
* Plugin version: 7.0.3
* Platform: Android
* OS version: various versions including 11 and 12
* Device manufacturer / model: various models
* Cordova version (`cordova -v`): 11.0.0
* Cordova platform version (`cordova platform ls`):  android 10.1.1
* Plugin config:
```
window.BackgroundFetch.configure({
  stopOnTerminate: false,
  enableHeadless: true,
});
```

```
<resource-file src="src/android/BackgroundFetchHeadlessTask.java" target="src/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java" />
```

## Expected Behavior
No or very few crash reports in Google Play Console

## Actual Behavior
We see many crashes possible as many as 50% of the daily user count. (could be some users having it multiple times a day resulting in more than 50% crash-free users, but still it is a lot of crashes)

```
com.transistorsoft.tsbackgroundfetch.BGTask$Error: 
  at com.transistorsoft.tsbackgroundfetch.BGTask.fireHeadlessEvent (BGTask.java:231)
  at com.transistorsoft.tsbackgroundfetch.BGTask.onTimeout (BGTask.java:196)
  at com.transistorsoft.tsbackgroundfetch.BGTask$1.run (BGTask.java:80)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8633)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1133)
```

## Context
I noticed that the target in our <resource-file> is wrong with respect to the current docs. I did a blame on it and found it was changed two years ago and fixed issue #116. However in that issue there is not any error report with similar stack trace as the one we received.

This crashes started to occur when we migrated from 6.0.8 to 7.0.3 of the plugin.

I first saw that we slipped to address the [breaking change with BG Task](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/CHANGELOG.md#warning-android-breaking-change-for-android-headless-task), but after fixing that, the crashes still occurs. It could be because the wrong target in resource-file and some changes from 6.0.8 => 7.0.3 making the wrong target now fatal.

If you have any insight, that would be welcome. But otherwise it might resolve if target in resource-file is changed and/or we can probably avoid the crashes by disabling headless in JS conifg I hope.

**Comment by christocracy** [comment]
Show me your HeadlessTask.

Btw, where are your `callback` functions for `configure` (args 2 and 3)?  have you simply not shown them?

```javascript
window.BackgroundFetch.configure({
  stopOnTerminate: false,
  enableHeadless: true,
});
```

**Comment by Leffe108** [comment]
Sorry, I accidently forgot to include the callback functions?
```
window.BackgroundFetch.configure({
	stopOnTerminate: false,
	// Android
	enableHeadless: false,
}, self.onBackgroundFetch, self.onBackgroundFetchTimeout).then(function() {
	// config successful
}, self.onBackgroundFetchFailed);
```

```
onBackgroundFetch: function() {
	Log.log('BackgroundFetch');
	window.BackgroundGeolocation.startBackgroundTask(function(taskId) {
		if (ionic.Platform.isAndroid()) {
			window.AndroidCommon.handleOnBackgroundFetch(function(){
				window.BackgroundFetch.finish(taskId);
			}, function(){
				window.BackgroundFetch.finish(taskId);
			});
		} else {
```

AndroidCommon is our code and is called from both the JS side and from the Java side. 

The headless task looks like this in our last production version which the crashlog corresponds to. But from my understanding it is not used due to the wrong path in <resource-file> in config.xml.

```
package com.transistorsoft.cordova.backgroundfetch;
import android.content.Context;
import org.apache.cordova.CallbackContext;
import com.transistorsoft.tsbackgroundfetch.BackgroundFetch;
import com.transistorsoft.tsbackgroundfetch.BGTask;
import android.util.Log;

import com.company.app.AndroidCommonFunctions;

public class BackgroundFetchHeadlessTask implements HeadlessTask {
    @Override
    public void onFetch(Context context, BGTask task) {
        String taskId     = task.getTaskId();
        boolean isTimeout = task.getTimedOut();
        if (isTimeout) {
                Log.d(BackgroundFetch.TAG, "My BackgroundFetchHeadlessTask:  onFetch - timeout - taskid: " + taskId);
                BackgroundFetch.getInstance(context).finish(taskId);
                return;
        }
        Log.d(BackgroundFetch.TAG, "My BackgroundFetchHeadlessTask:  onFetch - taskId: " + taskId);
        // Perform your work here.
//        AndroidCommonFunctions.handleOnBackgroundFetch(context);
        // Just as in Javascript callback, you must signal #finish
        BackgroundFetch.getInstance(context).finish(taskId);
    }
}
```

**Comment by christocracy** [comment]
Are you simulating Headless events on your development device?

>But from my understanding it is not used due to the wrong path in in config.xml.

Why have you not corrected this?

The plugin is crashing [here in `tsbackgroundfetch`](https://github.com/transistorsoft/transistor-background-fetch/blob/master/android/tsbackgroundfetch/src/main/java/com/transistorsoft/tsbackgroundfetch/BGTask.java#L230-L231), where it tried to reflect your configured `BackgroundGeolocationHeadlessTask` (`ClassNotFoundError`).

**Comment by Leffe108** [comment]
> Why have you not corrected this?

Because I found out about this today. But it is among the changes that I will push a new update to production later today once I have cleared the basic Q/A steps.

Thank you for the source code link. I didn't know it was public.

**Comment by Leffe108** [comment]
> Are you simulating Headless events on your development device?

I think this was made by my co worker that implemented this code initially. But things blow up in production now and I got to solve it. :-)

Thank you for the quick help.

**Comment by christocracy** [comment]
the quick solution is `enableHeadless: false`.  The long-term solution is to ensure that your `BackgroundGeolocationHeadlessTask.java` is properly configured in `config.xml`.

This will be easy to simulate and test on your local device.
