### ISSUE TITLE
 Security error from Scan: Manifest Declared Broadcast Receivers Not Protected With Permissions. Can Leak Data to Other Apps

### ISSUE THREAD

**Issue by nanshaki** [transistorsoft/cordova-plugin-background-fetch#163]
## Your Environment
* Plugin version: 4.4.0
* Platform: Android
* OS version: 12
* Device manufacturer / model: Galaxy
* Cordova version (`cordova -v`): 10.0
* Cordova platform version (`cordova platform ls`): 10.1.1
* Plugin config

## Expected Behavior
Should not get error in Security Scan

## Actual Behavior
Description
Manifest Declared Broadcast Receivers Not Protected With Permissions Can Leak Data to Other Apps This test statically audits the app binary forany manifest declared broadcast receivers that have not been protected with permissions. Description Broadcast receivers that are registeredwithout specifying any permissions can potentially leak sensitive info to all other applications on the device. A malicious app installed on the devicecan attempt to send broadcast intents that trigger the unprotected broadcast receiver. These intents can modify the runtime of the app, making theapp a potential phishing vector. If the sender app's broadcasts contain sensitive information, a malicious app may be able to perform intent sniffing,leaking sensitive data. Furthermore, a malicious app can register itself with high priority, if the broadcast is an ordered broadcast, to receive thebroadcast first. If the malicious app is the first to receive the broadcast, it could cancel the broadcast causing a denial of service, or it could inject amalicious data into the broadcast. NAME INTENTS COMPONENT PERMISSION com.transistorsoft.locationmanager.BootReceiver receivercom.transistorsoft.cordova.backgroundfetch.HeadlessBroadcastReceiver receiver com.transistorsoft.tsbackgroundfetch.BootReceiver receiver

## Steps to Reproduce
Test App thru INSEC

## Context
test the app thru INSEC

**Comment by christocracy** [comment]
This is not a security issue.  The plug-in’s BootReceiver simply automatically starts the plugin when the device is rebooted (for Config.startOnBoot) and the plugin currently has State.enabled == true.
