### ISSUE TITLE
Adding GET_TASKS permission to AndroidManifest.xml file

### ISSUE THREAD

**Issue by venkateshkakumani** [transistorsoft/cordova-plugin-background-fetch#164]
## Environment

- Plugin version: 7.1.1
- Platform: Android
- Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0
- Cordova:
   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1

## Expected Behavior

The GET_TASKS permission has been added to the AndroidManifest.xml file. Even though it isn't declared in plugin.xml

## Actual Behavior
According to Google Play's new guidelines, this permission should be removed effectively from July 2022

**Comment by christocracy** [comment]
> According to Google Play's new guidelines, this permission should be removed effectively from July 2022

Show me the link to this guidance.

I have a migration plan which involves cutting off Android 4 from the plugin.

**Comment by venkateshkakumani** [comment]
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/35324358/169258905-5c0d82b5-3713-44c8-913a-3ea25c16a7a0.png)

Policy Link :  https://support.google.com/googleplay/android-developer/answer/9888170
