### ISSUE TITLE
Background fetch not working every 5 minutes in android, when app killed and stationary and locked

### ISSUE THREAD

**Issue by Malshurafaa** [transistorsoft/cordova-plugin-background-fetch#166]
## Your Environment
* Plugin version:7.0.3
* Platform:  Android
* OS version:11
* Device manufacturer / model:samsung sm-a127f,
* Cordova version (`cordova -v`):10.0.0
* Cordova platform version (`cordova platform ls`):andriod 9.1.0
* Plugin config:

```javascript
 async initializeBackgroundFetchForAndroid() {
        let taskIdAndroid = 'AndroidFetch1';
        let status = await BackgroundFetch.configure({
            minimumFetchInterval: 5,
            forceAlarmManager: true,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless:true
          }, async (taskIdAndroid) => {            
            await BackgroundGeolocation.getCurrentPosition({
                maximumAge: 9000,
                timeout: 45,
                extras: { backgroundFetch: true },
                persist:true
            }, lcoation => {
                this.location = {
                    latitude: lcoation.coords.latitude,
                    longitude: lcoation.coords.longitude,
                    accuracy:lcoation.coords.accuracy
                }
                BackgroundFetch.finish(taskIdAndroid);
            }, (error: LocationError) => {
                BackgroundFetch.finish(taskIdAndroid);
          });
          }, async (taskId) => {
                BackgroundFetch.finish(taskIdAndroid);
          });      
    }
```
## Expected Behavior

background fetch implemented in android every 5 minutes. But after being stationary and phone locked for 3-4 hours, then location update is not happening regularly. Then location update happens only after unlocking the phone or moving a small distance.

## Actual Behavior
location should be send every 5 min even phone stationary or not moving or locked

## Steps to Reproduce

1.
2.
3.
4.

## Context
We are using Background cordova-geolocation-lt plugin and started to get location update every 1 minute. At the same time background-fetch is implemented every 5 minutes. We have also implemented enableheadless true and have written java code to fetch location update even when app killed. The application sends location update using background fetch when killed/background for 1-2 hours(phone stationary and locked) easily and then location update stops

## Debug logs
Check logs from 25 Oct 00:27 till 25 Oct 09:32
[background-geolocation-25Oct-github.log](https://github.com/transistorsoft/cordova-plugin-background-fetch/files/9857547/background-geolocation-25Oct-github.log)

-->

**Comment by christocracy** [comment]
```javascript
await BackgroundGeolocation.getCurrentPosition({
                maximumAge: 9000,
                timeout: 45,
                extras: { backgroundFetch: true },
                persist:true
            }, lcoation => {
                this.location = {
                    latitude: lcoation.coords.latitude,
                    longitude: lcoation.coords.longitude,
                    accuracy:lcoation.coords.accuracy
                }
                BackgroundFetch.finish(taskIdAndroid);
            }, (error: LocationError) => {
                BackgroundFetch.finish(taskIdAndroid);
          });
```

This is *not* how you use the `Promise` API.  You're mixing the old api (ie: callback api) + `Promise` api.

it's like this:

```javascript
let location = await BackgroundGeolocation.getCurrentPosition({
  maximumAge: 9000,
  timeout: 45,
  extras: { backgroundFetch: true },
  persist:true
});
// do your work with location...
BackgroundFetch.finish(taskIdAndroid);
```
