### ISSUE TITLE
Headless task no longer executed since upgrade

### ISSUE THREAD

**Issue by felicienfrancois** [transistorsoft/cordova-plugin-background-fetch#167]
## Your Environment
* Plugin version: 7.1.2
* Platform: Android
* OS version: 13
* Device manufacturer / model: Google Pixel 5
* Cordova version (`cordova -v`): 12.0.0
* Cordova platform version (`cordova platform ls`): android 12.0.0
* Plugin config
```javascript
{
  minimumFetchInterval: 15,
  stopOnTerminate: false,
  startOnBoot: true,
  enableHeadless: true,
  requiredNetworkType: BackgroundFetch.NETWORK_TYPE_ANY,
}
```

BackgroundFetchHeadlessTask.java (same as default implementation, but fixed taskId => task.getTaskId())
```java
package com.transistorsoft.cordova.backgroundfetch;
import android.content.Context;
import android.util.Log;
import com.transistorsoft.tsbackgroundfetch.BackgroundFetch;
import com.transistorsoft.tsbackgroundfetch.BGTask;

public class BackgroundFetchHeadlessTask implements HeadlessTask {
    @Override
    public void onFetch(Context context, BGTask task) {
        Log.d(BackgroundFetch.TAG, "BackgroundFetchHeadlessTask onFetch: taskId: " + task.getTaskId() + ", timeout: " + task.getTimedOut() + "-- DEFAULT IMPLEMENTATION");
        BackgroundFetch.getInstance(context).finish(task.getTaskId());
    }
}
```

config.xml
```xml
<preference name="AndroidLaunchMode" value="singleTask" />
<preference name="AndroidXEnabled" value="true" />
<preference name="android-targetSdkVersion" value="33" />
<resource-file src="BackgroundFetchHeadlessTask.java" target="app/src/main/java/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java" />
```

## Expected Behavior

When app is killed, headless java task should execute when triggered (either by OS scheduler or using adb) and we should see  "BackgroundFetchHeadlessTask onFetch ..." in adb logcat

## Actual Behavior

When app is killed background fetch event is received but it finally timeouts without executing task

## Steps to Reproduce

1. Start background fetch task using enableHeadless: true
2. Kill app
3. Trigger background fetch using `adb shell cmd jobscheduler run -f <your.application.id> 999`

## Context

It was working one year ago but since I upgraded cordova, cordova-android and most plugin version, it no longer works.
Parameters have not changed.

## Debug logs

adb logcat -s TSBackgroundFetch
```
D TSBackgroundFetch: - configure
D TSBackgroundFetch: - start
D TSBackgroundFetch: - registerTask: cordova-background-fetch
D TSBackgroundFetch: {
D TSBackgroundFetch:   "taskId": "cordova-background-fetch",
D TSBackgroundFetch:   "isFetchTask": true,
D TSBackgroundFetch:   "minimumFetchInterval": 15,
D TSBackgroundFetch:   "stopOnTerminate": false,
D TSBackgroundFetch:   "requiredNetworkType": 1,
D TSBackgroundFetch:   "requiresBatteryNotLow": false,
D TSBackgroundFetch:   "requiresCharging": false,
D TSBackgroundFetch:   "requiresDeviceIdle": false,
D TSBackgroundFetch:   "requiresStorageNotLow": false,
D TSBackgroundFetch:   "startOnBoot": true,
D TSBackgroundFetch:   "jobService": "com.transistorsoft.cordova.backgroundfetch.BackgroundFetchHeadlessTask",
D TSBackgroundFetch:   "forceAlarmManager": false,
D TSBackgroundFetch:   "periodic": true,
D TSBackgroundFetch:   "delay": -1
D TSBackgroundFetch: }
D TSBackgroundFetch: [CDVBackgroundFetch] status()
D TSBackgroundFetch: ☯️  onPause
D TSBackgroundFetch: ☯️  onStop
D TSBackgroundFetch: - Background Fetch event received: cordova-background-fetch
D TSBackgroundFetch: [BGTask] timeout: cordova-background-fetch
```

**Comment by felicienfrancois** [comment]
When looking at full logcat at the moment i trigger fetch event i saw the following exception:
```
07-07 16:25:50.601 19985 19985 D TSBackgroundFetch: - Background Fetch event received: cordova-background-fetch
07-07 16:25:50.603 19985 19985 W cr_AwContents: Application attempted to call on a destroyed WebView
07-07 16:25:50.603 19985 19985 W cr_AwContents: java.lang.Throwable
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at org.chromium.android_webview.AwContents.m(chromium-TrichromeWebViewGoogle6432.aab-stable-573519633:10)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at org.chromium.android_webview.AwContents.h(chromium-TrichromeWebViewGoogle6432.aab-stable-573519633:2)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(chromium-TrichromeWebViewGoogle6432.aab-stable-573519633:37)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at android.webkit.WebView.evaluateJavascript(WebView.java:893)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at org.apache.cordova.engine.SystemWebViewEngine.evaluateJavascript(SystemWebViewEngine.java:327)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at org.apache.cordova.NativeToJsMessageQueue$EvalBridgeMode$1.run(NativeToJsMessageQueue.java:378)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at android.app.Activity.runOnUiThread(Activity.java:7368)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at org.apache.cordova.NativeToJsMessageQueue$EvalBridgeMode.onNativeToJsMessageAvailable(NativeToJsMessageQueue.java:374)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at org.apache.cordova.NativeToJsMessageQueue.enqueueMessage(NativeToJsMessageQueue.java:259)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at org.apache.cordova.NativeToJsMessageQueue.addPluginResult(NativeToJsMessageQueue.java:248)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at org.apache.cordova.CordovaWebViewImpl.sendPluginResult(CordovaWebViewImpl.java:358)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at org.apache.cordova.CallbackContext.sendPluginResult(CallbackContext.java:61)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at com.transistorsoft.cordova.backgroundfetch.CDVBackgroundFetch$1.onFetch(CDVBackgroundFetch.java:63)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at com.transistorsoft.tsbackgroundfetch.BackgroundFetch.doFetch(BackgroundFetch.java:263)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at com.transistorsoft.tsbackgroundfetch.BackgroundFetch.onFetch(BackgroundFetch.java:236)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at com.transistorsoft.tsbackgroundfetch.FetchJobService.onStartJob(FetchJobService.java:36)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at android.app.job.JobService$1.onStartJob(JobService.java:68)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:105)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at android.os.Handler.dispatchMessage(Handler.java:106)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at android.os.Looper.loopOnce(Looper.java:201)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at android.os.Looper.loop(Looper.java:288)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at android.app.ActivityThread.main(ActivityThread.java:7918)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at java.lang.reflect.Method.invoke(Native Method)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-07 16:25:50.603 19985 19985 W cr_AwContents:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by christocracy** [comment]
I cannot reproduce this.

```
07-07 10:43:08.176 10683 10683 D TSBackgroundFetch: - Background Fetch event received: com.transistorsoft.customtask
07-07 10:43:08.179 10683 10683 D TSBackgroundFetch: ☯️  onCreate
07-07 10:43:08.192 10683 10683 D TSBackgroundFetch: BackgroundFetchHeadlessTask onFetch -- CUSTOM IMPLEMENTATION
07-07 10:43:08.192 10683 10683 D TSBackgroundFetch: - finish: com.transistorsoft.customtask
07-07 10:43:08.193 10683 10683 D TSBackgroundFetch: - FetchAlarmReceiver finish
07-07 10:43:08.231 10683 10683 D TSBackgroundFetch: ☯️  HeadlessMode? true
07-07 10:43:10.123 10683 10683 D TSBackgroundFetch: - Background Fetch event received: cordova-background-fetch
07-07 10:43:10.124 10683 10683 D TSBackgroundFetch: BackgroundFetchHeadlessTask onFetch -- CUSTOM IMPLEMENTATION
07-07 10:43:10.124 10683 10683 D TSBackgroundFetch: - finish: cordova-background-fetch
07-07 10:43:10.124 10683 10683 D TSBackgroundFetch: - jobFinished
```

```
cordova-plugin-background-fetch 7.1.2 "CDVBackgroundFetch"
```

```
$ cordova platform
Installed platforms:
  android 12.0.0
  ios 6.2.0
```

Create for me a simple *HelloWorld* which reproduces this.  Post to a public Github repo and share it with me.

**Comment by felicienfrancois** [comment]
OK, it seems that the cause is headless detection not working properly in my case.

```
at com.transistorsoft.tsbackgroundfetch.BackgroundFetch.doFetch(BackgroundFetch.java:263)
```
[BackgroundFetch.java#L263](https://github.com/transistorsoft/transistor-background-fetch/blob/b331a4999a7223e0c6247f3f9a84c37041098d14/android/tsbackgroundfetch/src/main/java/com/transistorsoft/tsbackgroundfetch/BackgroundFetch.java#L263)

The cordova head (webview) is killed but the test `LifecycleManager.getInstance().isHeadless()` return false

This may be due to the fact that i have another plugin which hold a background service and a permanent notification.
The webview head is killed but there is another java service running.

The previous headless detection method was working (it was refactored in [this commit](https://github.com/transistorsoft/transistor-background-fetch/commit/b331a4999a7223e0c6247f3f9a84c37041098d14#diff-808628af1999c92b60c46d3a4a1c5fb0035eea3abae64aa65f860e96676734aeR263)

**Comment by christocracy** [comment]
Create for me a simple *HelloWorld* which reproduces the problem.

**Comment by felicienfrancois** [comment]
I'll try.

**Comment by felicienfrancois** [comment]
@christocracy here is a working reproduction using a plugin which starts another background task (pedometer): 

https://github.com/felicienfrancois/cordova-background-fetch-issue-reproduction

Unfortunatelly it cannot run in emulator because of pedometer requirement and you'll need a device to run it.

**Comment by felicienfrancois** [comment]
After some more investigation on my usecase (where there is another task running in the background),
the issue come from [LifecycleManager.onDestroy](https://github.com/transistorsoft/transistor-background-fetch/blob/b331a4999a7223e0c6247f3f9a84c37041098d14/android/tsbackgroundfetch/src/main/java/com/transistorsoft/tsbackgroundfetch/LifecycleManager.java#L161) not being called when killing the App.
Currently the LifecycleManager seems to be bound to [Looper.getMainLooper()](https://github.com/transistorsoft/transistor-background-fetch/blob/b331a4999a7223e0c6247f3f9a84c37041098d14/android/tsbackgroundfetch/src/main/java/com/transistorsoft/tsbackgroundfetch/BackgroundFetch.java#L48).

This does not seems to work properly with cordova.
I added some logs to [CDVBackgroundFetch.java](https://github.com/felicienfrancois/cordova-background-fetch-issue-reproduction/blob/main/CDVBackgroundFetch.java#L44), the cordova entry point and here what I see in logs:
```
07-07 18:47:06.536 29716 29716 D TSBackgroundFetch: [CDVBackgroundFetch] onStop
07-07 18:47:06.536 29716 29716 D TSBackgroundFetch: [CDVBackgroundFetch] onSaveInstanceState
07-07 18:47:06.599 29716 29716 D TSBackgroundFetch: [CDVBackgroundFetch] onDestroy
07-07 18:47:07.199 29716 29716 D TSBackgroundFetch: ☯️  onPause
07-07 18:47:07.199 29716 29716 D TSBackgroundFetch: ☯️  onStop
```

*CDVBackgroundFetch.onDestroy* is correctly called on app kill (and not on switch to background).

**Comment by christocracy** [comment]
try this:  edit the file `platforms/android/app/src/main/java/com/transistorsoft/cordova/backgroundfetch/CDVBackgroundFetch.java`.

Add the following lines of code:

- At top of file:
```diff
import com.transistorsoft.tsbackgroundfetch.BackgroundFetch;
import com.transistorsoft.tsbackgroundfetch.BackgroundFetchConfig;
+import com.transistorsoft.tsbackgroundfetch.LifecycleManager;
```

- At bottom of file, add the following function:
```java
    @Override
    public void onDestroy() {
        LifecycleManager.getInstance().setHeadless(true);
        super.onDestroy();
    }
```

**Comment by felicienfrancois** [comment]
@christocracy I confirm that it works

It fix the issue with cordova plugin.

Then, I don't know if there may be similar issues with other plugins which use the backgroundfetch library (capacitor, react native, ...).
Maybe it worth to investigate further the binding of the LifecycleManager on a more appropriate event source.

**Comment by christocracy** [comment]
>Maybe it worth to investigate further the binding of the LifecycleManager on a more appropriate event source

I can't.  The lib `tslocationmanager.aar` is dealing with `ApplicationContext`, not `Activity`.  The other frameworks already have similar code to handle this case ([for example](https://github.com/transistorsoft/flutter_background_fetch/blob/d4669d32561a3bb0683eb1bc3262a779e569674e/android/src/main/java/com/transistorsoft/flutter/backgroundfetch/BackgroundFetchModule.java#L84-L86))

This will be released later today as `7.1.3`.

**Comment by felicienfrancois** [comment]
ok, understood.

Thank you for the prompt reply and fix.

**Comment by christocracy** [comment]
`v7.1.3` is published.
