### ISSUE TITLE
In Headless Mode, how to request current location within Java?

### ISSUE THREAD

**Issue by japeacock** [transistorsoft/cordova-plugin-background-fetch#169]
## Your Environment
* Plugin version: 7.1.2
* Platform: Android
* OS version: macOS Sonoma Version 14.2.1
* Device manufacturer / model: Samsung SM-T220
* Cordova version (`cordova -v`): 12.0.0 (cordova-lib@12.0.1)
* Cordova platform version (`cordova platform ls`): android 12.0.0
* Plugin config

`// 1.  Listen to events
var bgGeo = window.BackgroundGeolocation;

            // 2. Execute #ready method:
            bgGeo.ready({
                    reset: true,
                    debug: true,
                    logLevel: bgGeo.LOG_LEVEL_VERBOSE, // LOG_LEVEL_OFF
                    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
                    distanceFilter: 50, // 50 meters
                    allowIdenticalLocations: true,
                    elasticityMultiplier: 3, 
                    // url: '', // temp removed
                    autoSync: true,
                    batchSync: false, // true reduces battery life
                    maxBatchSize: 50,
                    autoSyncThreshold: 50,
                    stopOnTerminate: false,
                    startOnBoot: true,
                    disableLocationAuthorizationAlert: "Always",
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    extras: {
                        imei: localStorage.getItem('imei'),
                        battery: localStorage.getItem('battery'),
                    },
                    locationsOrderDirection: "DESC",
                    locationAuthorizationAlert: {
                        titleWhenNotEnabled: "Location services are not enabled",
                        titleWhenOff: "Location services are off",
                        instructions: "To use location tracking, you must enable 'Always' in the Location Service settings",
                        cancelButton: "Cancel",
                        settingsButton: "Settings"
                    },
                    backgroundPermissionRationale: {
                        title: "Allow App to access to this device's location in the background?",
                        message: "In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission",
                        positiveAction: "Change to {backgroundPermissionOptionLabel}",
                        negativeAction: "Cancel"
                    }
                }, 
                function(state) {

                    // 3.  Start tracking
                    console.log('BackgroundGeolocation is configured and ready to use');
                    if (!state.enabled) {
                        toggleGPSPermission(false);

                        bgGeo.start().then(function() {
                            console.log('- BackgroundGeolocation tracking started');
                            toggleGPSPermission(true);

                            console.log('[BackgroundFetch] configure status: ', status);

                            var location = bgGeo.getCurrentPosition({
                                timeout: 15,          // 15 second timeout to fetch location
                                maximumAge: 5000,     // Accept the last-known-location if not older than 5000 ms.
                                desiredAccuracy: 10,  // Try to fetch a location with an accuracy of `10` meters.
                                samples: 3,           // How many location samples to attempt.
                                extras: {             // Custom meta-data.
                                    imei: localStorage.getItem('imei'),
                                    battery: localStorage.getItem('battery'),
                                }
                            });
                            console.log('[getCurrentPosition]', location);

                        }, function(error) {
                            console.log("Error: "+error);
                            toggleGPSPermission(false);
                        });
                    }
                },
                function(error) {
                    console.log("Error: "+error);
                    toggleGPSPermission(false);
                }
            );

            // background location 
            var BackgroundFetch = window.BackgroundFetch;

            // Your BackgroundFetch event handler.
            var onEvent = async function(taskId) {
                console.log('[BackgroundFetch] event received: ', taskId);

                var location = bgGeo.getCurrentPosition({
                    timeout: 15,          // 15 second timeout to fetch location
                    maximumAge: 5000,     // Accept the last-known-location if not older than 5000 ms.
                    desiredAccuracy: 10,  // Try to fetch a location with an accuracy of `10` meters.
                    samples: 3,           // How many location samples to attempt.
                    extras: {             // Custom meta-data.
                        imei: localStorage.getItem('imei'),
                        battery: localStorage.getItem('battery'),
                    }
                });
                console.log('[getLocation]', location);

                // Required: Signal completion of your task to native code
                // If you fail to do this, the OS can terminate your app
                // or assign battery-blame for consuming too much background-time
                BackgroundFetch.finish(taskId);
            };

            // Timeout callback is executed when your Task has exceeded its allowed running-time.
            // You must stop what you're doing immediately BackgroundFetch.finish(taskId)
            var onTimeout = async function(taskId) {
                console.log('[BackgroundFetch] TIMEOUT: ', taskId);
                BackgroundFetch.finish(taskId);
            };

            var status = BackgroundFetch.configure({
                minimumFetchInterval: 15,
                startOnBoot: true,
                stopOnTerminate: false,
                enableHeadless: true
            }, onEvent, onTimeout);`

## My Java File - BackgroundFetchHeadlessTask.java
`package com.transistorsoft.cordova.backgroundfetch;

import android.content.Context;
import android.util.Log;

import com.transistorsoft.tsbackgroundfetch.BackgroundFetch;
import com.transistorsoft.tsbackgroundfetch.BGTask;

public class BackgroundFetchHeadlessTask implements HeadlessTask {
    @Override
    public void onFetch(Context context, BGTask task) {
        String taskId = task.getTaskId();
        boolean isTimeout = task.getTimedOut();
        if (isTimeout) {
          Log.d(BackgroundFetch.TAG, "My BackgroundFetchHeadlessTask TIMEOUT: " + taskId);
          BackgroundFetch.getInstance(context).finish(taskId);
          return;
        }
        Log.d(BackgroundFetch.TAG, "My BackgroundFetchHeadlessTask:  onFetch: " + taskId);
        
        // How do I request location here??

        // Just as in Javascript callback, you must signal #finish
        BackgroundFetch.getInstance(context).finish(taskId);
    }
}`

## Expected Behavior
Trigger current location request within Headless mode in Java file.

## Actual Behavior
Background fetch is working when running `adb shell cmd jobscheduler run  <application.id> 999` and file is all hooked up in confirm.xml and copied over the build folder.

## Steps to Reproduce

1. Run `adb shell cmd jobscheduler run  <application.id> 999 `to simulate backgroundFetch

## Context
In Headless Mode, I want to request the users current location within the Java file.

## Debug logs
06-04 19:42:37.492  2818  2974 D TSBackgroundFetch: [CDVBackgroundFetch] configure()
06-04 19:42:37.497  2818  2974 D TSBackgroundFetch: - configure
06-04 19:42:37.497  2818  2974 D TSBackgroundFetch: - start
06-04 19:42:37.500  2818  2974 D TSBackgroundFetch: - registerTask: cordova-background-fetch
06-04 19:42:37.504  2818  2818 D TSBackgroundFetch: ☯️  onCreate
06-04 19:42:37.504  2818  2818 D TSBackgroundFetch: ☯️  onStart
06-04 19:42:37.505  2818  2818 D TSBackgroundFetch: ☯️  onResume
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch: {
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "taskId": "cordova-background-fetch",
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "isFetchTask": true,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "minimumFetchInterval": 15,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "stopOnTerminate": false,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "requiredNetworkType": 0,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "requiresCharging": false,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "requiresDeviceIdle": false,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "requiresStorageNotLow": false,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "startOnBoot": true,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "jobService": "com.transistorsoft.cordova.backgroundfetch.BackgroundFetchHeadlessTask",
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "forceAlarmManager": false,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "periodic": true,
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch:   "delay": -1
06-04 19:42:37.529  2818  2974 D TSBackgroundFetch: }
06-04 19:42:37.542  2818  2974 D TSBackgroundFetch: [CDVBackgroundFetch] status()
06-04 19:42:54.007  2818  2818 D TSBackgroundFetch: ☯️  onPause
06-04 19:42:54.010  2818  2818 D TSBackgroundFetch: ☯️  onStop
06-05 10:26:47.548 24264 24264 D TSBackgroundFetch: - Background Fetch event received: cordova-background-fetch
06-05 10:26:47.564 24264 24391 D TSBackgroundFetch: [CDVBackgroundFetch] finish()
06-05 10:26:47.565 24264 24391 D TSBackgroundFetch: - finish: cordova-background-fetch
06-05 10:26:47.565 24264 24391 D TSBackgroundFetch: - jobFinished

**Comment by japeacock** [comment]
Great thanks, just to clarify will the background fetch when it runs automatically request the location? Or do we actually need to request the location within the headless function?

**Comment by christocracy** [comment]
Background Fetch has nothing at all to do with "location".
