### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cr1t** [transistorsoft/cordova-plugin-background-fetch#26]
We are sending push notifications to the app, that have no alert part, only tell the app to complete some task.

It seems that if the user does not interact with the app for some time the Javascript call back does not execute.

If we used this would this plugin do you think the background push notification will get delivered in that time to the app?

**Comment by christocracy** [comment]
in your Push, are you setting the flag `content-available: 1` ?

**Comment by cr1t** [comment]
Hi 

Yes we did. Is this normal for iOS do you know? Maybe I should post the question on the push plugin forum.
