### ISSUE TITLE
[TOOL] cordova-diagnostic-plugin

### ISSUE THREAD

**Issue by roblav96** [transistorsoft/cordova-plugin-background-fetch#35]
A recent update was made to [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) allowing you to diagnose wether the user has enabled background fetch in settings.

I thought this could be helpful. Maybe add it to the readme.md?

https://github.com/dpa99c/cordova-diagnostic-plugin/commit/e433772acef223c2b75bd03193dd514453cb962a

**Comment by christocracy** [comment]
That would be helpful, thanks.  Why don't you implement it and give me a PR?

**Comment by roblav96** [comment]
Done.
