### ISSUE TITLE
cordova not initialized when app launched via background fetch

### ISSUE THREAD

**Issue by jpittner** [transistorsoft/cordova-plugin-background-fetch#4]
Two ways background fetch can be triggered - we can simulate one in Xcode, or we can pretend like the app hasn't been loaded in iOS yet (or say was unloaded after no use for a while) and edit the scheme so that the app loads via a backgroundfetch event by the OS. (in Xcode, under Product -> Edit Scheme -> launch due to a background fetch event). 

When you do this, and be quick about opening up Safari, you'll see that the deviceReady call from Cordova doesn't happen (you'll see the error in the console). As such, the app never loads in javascript land and then the background fetch call never completes.

Granted, it's 11:30pm at night and I've been working all day, so I might be doing something completely wrong here but I can't see it. Did you run into this at all?

edit- another thing I just found. Looking at https://github.com/edewit/cordova-background-plugin he's got a method in there to tell the OS if new data was available or not, this doesn't seem to be implemented in your plugin?

edit2 - trying this more, and it seems to work some of the time, while others it just dies and fails to fire device ready in 5s. hm.

edit3 - well, past few attempts it seems to be loading. I'm going to chalk it up to some sorta xcode fluke for now. Debugging this stuff is a PITA.

**Comment by CookieCookson** [comment]
I had this issue too which was causing the App to hang in alot of scenarios. To fix this I removed:

//if (!self.fetchCallbackId) {
        //return;
    //}

from onFetch in CDVBackgroundFetch.m as I always had a configuration set by the time the javascript was executed

**Comment by derDeno** [comment]
Still not fixing it for me. It just produces a new error in the console in xcode
