### ISSUE TITLE
configure and start / stop

### ISSUE THREAD

**Issue by tverilytt** [transistorsoft/cordova-plugin-background-fetch#48]
Hi!
Thanks for great plugin, I switched from the background-mode plugin because that one was rejected by App Store.

I experience at some occasions, when putting the app in background, background fetch never seems to fire, other times it works well firing about every 15 minutes.

I am considering trying to explicitly call the start() method on pause event, and then stop() method on resume event. Will that work? Do one have to call configure() after stop()?

Cheers
-jo

**Comment by christocracy** [comment]
Won't work.  Apple has a secret algorithm for fetch but is based on device usage patterns and time of day.

Monkeying with the API by calling #start/#stop is pointless.

You have no control over the frequency.  Sometimes it comes every 15, sometimes not.  You have to live with it

**Comment by tverilytt** [comment]
Yes I have understood that one cannot control the frequency.
I just started to wonder if the background fetcher was enabled or not. Which it was, so no worries.
I like the concept of just configuring the plugin once and then let it do its job :-)

**Comment by tverilytt** [comment]
Also, in my case, the user can choose whether to enable background fetch. That was why I thought of using the start and stop methods. If not, I would have to deregister the fetch in some way, maybe config(null, null) will do?

Cheers
-jo2

**Comment by kosssi** [comment]
it's a good question.

**Comment by tverilytt** [comment]
Hi!
After a period of testing, it seemed like when putting the app in background first time, fetch runs well. Bringing the app to foreground, and then again to background, no fetch seems to run.
I therefore added a start() in resume event method, and rhen fetch runs on next background period.
App iser can toggle background on and off, and then start() and stop() is called too. 
So now fetch seems to run very well :-)

Cheers
-jo2

**Comment by christocracy** [comment]
@tverilytt Your theory of `#stop` / `#start` would be hokey if true.

Ultimately, both `#stop` and `#start` execute the method [`setMinimumBackgroundFetchInterval`](https://developer.apple.com/reference/uikit/uiapplication/1623100-setminimumbackgroundfetchinterva?language=objc) upon `CLLocationManager`.

`#stop` sends a constant meaning "None".
`#start` sends a constant meaning "Often as possible".

**Comment by mherb63** [comment]
@tverilytt What version of Cordova are you using?  My pause/resume methods never fire and I'm using 6.4.0 (the latest).

```
function mobilePunchAppPause() {
  console.log("MobilePunchApp paused");
}
function mobilePunchAppResume() {
  console.log("MobilePunchApp resumed");
}
function mobilePunchAppDeviceReady() {
  console.log("MobilePunchApp deviceready");

  document.addEventListener('pause', mobilePunchAppPause, false);
  document.addEventListener('resume', mobilePunchAppResume, false);

```

**Comment by christocracy** [comment]
Are you booting this on a device or simulator?

Are you sure your `deviceready` is firing?

**Comment by tverilytt** [comment]
@mherb63  I am on the same Cordova version as you, 6.4.0, and Ionic 2.1.17.

I do register the listeners first thing in the $ionicPlatform.ready method:
      document.addEventListener("pause", onPause, false);
      document.addEventListener("resume", onResume, false);
      document.addEventListener("resign", onResign, false);

**Comment by mherb63** [comment]
Wow, thanks for the quick responses guys.

I have done from simulator, and XCode connected to my phone.  My app gives a login page and once the user is validated, it does a redirect to another page and I think that is causing the issue.

I just checked and the pause/resume does work for the initial login page.

Do I need to reload plugins when I navigate to another page? 

I just started using Cordova like 2 days ago so I'm probably doing something wrong here.

Thanks,

Mike

**Comment by tverilytt** [comment]
@mherb63  I use Ionic and Angular, so the handling of plugins happens "automagically" AFAIK.

**Comment by mherb63** [comment]
@tverilytt Thanks.  I got it working, just needed to copy the ios www code onto my webserver and pull from there.

Now, the pause/resume and background fetch is working.  The background fetch is not consistent though.  Sometimes its 15-20 minutes, I've see once it was over an hour.  I have no other tasks running on my phone so I don't understand why IOS would be stingy with waking me up from background mode.

**Comment by tverilytt** [comment]
Cool :-)
I have experienced similar behavior, the interval is not predictable, like has been explained and discussed here in other threads.
I initially used another background mode plugin, which can be controlled, and worked well. But that was not accepted by AppStore review (it uses background audio to stay alive), so had to remove it (still using it for Android though).
This was the plugin I sed for IOS (now only Android):
https://github.com/katzer/cordova-plugin-background-mode

**Comment by christocracy** [comment]
It totally depends on app usage, how often you use the app.  You can't *bank* on *exactly* 15 minutes.

@tverilytt `background-mode` is **TOXIC** and 100% guaranteed to [get you rejected](https://github.com/katzer/cordova-plugin-background-mode#bangbang-store-compliance-bangbang).  I've been telling people that for 2 years.  Search its issues for ["apple"](https://github.com/katzer/cordova-plugin-background-mode/issues?utf8=%E2%9C%93&q=apple) -- nothing but tears.

**Comment by mherb63** [comment]
@christocracy yea I saw that repo before I found this one.  I was definitely steered away by the "Store Compliance" message.
