### ISSUE TITLE
Is the plugin phonegap build ready?

### ISSUE THREAD

**Issue by JuanCAlpizar** [transistorsoft/cordova-plugin-background-fetch#5]
I tried to use this plugin in phonegap build 3.3, since it wasn't in read me I took a look into the plugin xml and made the following plugin tag, according to PGB specs:

```
<gap:plugin name="org.transistorsoft.cordova.plugin.background.fetch" version="2.0.0" />
```

However when I tried to update code it threw the following error:

```
Unable to create app: plugin unsupported: org.transistorsoft.cordova.plugin.background.fetch @ 2.0.0
```

am I doing something wrong, is there any plans to upgrading to PGB?

**Comment by mnadler** [comment]
It appears that the plugin is registered on PGB https://build.phonegap.com/plugins/955
and links to an older branch of the repo https://github.com/christocracy/cordova-plugin-background-fetch/tree/b499860.

I have narrowed the problem to both window.BackgroundFetch and window.plugins.backgroundFetch (from the current and branch docs respectively) return undefined.

**Comment by christocracy** [comment]
I don't submit updates to pgb anymore.

On Wednesday, September 30, 2015, mnadler <notifications@github.com> wrote:

> It appears that the plugin is registered on PGB
> https://build.phonegap.com/plugins/955
> and links to an older branch of the repo
> https://github.com/christocracy/cordova-plugin-background-fetch/tree/b499860
> .
>
> I have narrowed the problem to both window.BackgroundFetch and
> window.plugins.backgroundFetch (from the current and branch docs
> respectively) return undefined.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/5#issuecomment-144543192>
> .
>


-- 
Snet form Gmail Mobile

**Comment by mnadler** [comment]
Does the existing legacy plugin on PGB work?  If so can you please point to a reference for it?

**Comment by christocracy** [comment]
You can install your own private plugins on PGB now.  Fork the plugin and
rename the id with your company id.  Google "PhoneGap private plugins"

On Wednesday, September 30, 2015, mnadler <notifications@github.com> wrote:

> Does the existing legacy plugin on PGB work? If so can you please point to
> a reference for it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/5#issuecomment-144548189>
> .
>


-- 
Snet form Gmail Mobile
