### ISSUE TITLE
Documentation on determining if user has allowed background app refresh

### ISSUE THREAD

**Issue by BenjaminConant** [transistorsoft/cordova-plugin-background-fetch#53]
On IOS at least, the user can toggle on or off background app refresh for a specific application. 

In my case, I want to use background app refresh as the primary way to call for new data from our API.

However, if background app refresh is toggled off by the user, I want to load new data when the user opens the app. 

How can I programmatically tell, when a user has opened the app and the app is loading, if background app refresh is available so that I can either call for new data from the API if I need to and not call for new data if I don't. Or alternatively, when the app notices that a user has turned off background app refresh, prompt them to turn it on. 

The workaround I have come up with is to check how old the data stored locally is and infer if background app refresh is doing its thing. If the data is old I call for new data, if not I do nothing.

**Comment by christocracy** [comment]
Nobody has asked about this before.  I'll look into seeing if there's a way to detect this.

**Comment by christocracy** [comment]
Yes, [seems possible](http://stackoverflow.com/a/19138393/2509892).

I guess I'll probably implement this as an event `authorizationchanged`.  Will probably take a few weeks to get around to.

**Comment by BenjaminConant** [comment]
Great! 

For me, it would be really awesome if it was provided as a method on `window.BackgroundFetch` something like `window.BackgroundFetch.fetchEnabled(succFunction, failFailFunction)` ... or even better, as a completely different boolean property on the window `window.BackgroundFetchEnabled`

that way I could just check on demand instead of having to create my own state

Either way, it would be a very helpful enhancement!

**Comment by christocracy** [comment]
This has been implemented with new `#status(callback)` method.

See [`STATUS_` constants.](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/www/BackgroundFetch.js#L27)
