### ISSUE TITLE
In simulator OK,  crash on iPhone

### ISSUE THREAD

**Issue by lconer** [transistorsoft/cordova-plugin-background-fetch#54]
Hi

I'm trying to use you plugin.
I've tested it on simulator (iOS 10.2) and work ok, try to test it on iPhone (6, iOS 10.2) and I;ve that error in xCode:

```
libsystem_kernel.dylib`mach_msg_trap:
    0x180625180 <+0>: movn   x16, #0x1e
    0x180625184 <+4>: svc    #0x80
->  0x180625188 <+8>: ret   
``` 

I've create new cordova project only with your plugin, fetchCallback function has got only console.log() to do.

Any suggestions what's wrong?
Let me know if you need more details.

Thanks

**Comment by christocracy** [comment]
Sorry, missed this issue.  I really don't know what causes this, but it only occurs in the simulator.  Just click the `[|>]` button and it continues happily along.
![](https://www.dropbox.com/s/twliqhdigyvvmrr/Screenshot%202017-01-23%2017.11.38.png?dl=1)
