### ISSUE TITLE
getCurrentLocation function doesnot call success callback with location coordinates if user turn off the location services and then turn On location services

### ISSUE THREAD

**Issue by amritmatharu** [transistorsoft/cordova-plugin-background-fetch#56]
Please find the following scenarios for replicating issue:

- I turn on the location service and open my app
- I configured the plugin and start tracking 
- I called getCurrentLocation function and I got user current location in its success callback
- Now, I turned off the location service and called getCurrentLocation function and now its error callback function is called with error code 1
- Now, I turned on the location service but now its not calling its success callback with user's current location and going in error callback with same error

Please suggest how can we resolve this issue. I have been using this plugin in my project.

**Comment by christocracy** [comment]
Wrong repo.
