### ISSUE TITLE
Background fetch not working with multiple html files in XCode

### ISSUE THREAD

**Issue by satvindermann** [transistorsoft/cordova-plugin-background-fetch#58]
Hi,

I have an app with  multiple html files, I want to configure the backgoundfetch so that if I run Xcode-> Background fetch from any of the files, the callback function is called. I have tried calling the same function from each of the files, but once configured it does not reconfigure. But at the same time, when I say background fetch from the second html file, it does not call the callback function. Please help, I am literally stuck here.

**Comment by christocracy** [comment]
Are you new to Cordova and mobile development?

**Comment by satvindermann** [comment]
No, the plugin was working fine in the earlier version of Xcode, it is just that when I upgraded the OS and the XCode, this is broken now.

**Comment by christocracy** [comment]
That's not what I asked.  

I'm asking about you.  How much experience do **you** have with Cordova / mobile development?

**Comment by satvindermann** [comment]
I have been developing the app for some time now, have good handle of jquery. Have developed i for both Android and IOS.

**Comment by christocracy** [comment]
Why do you talk of "HTML files"?

Obviously you should have a single common "app.js" file loaded by all HTML entry-points.  

This is not an issue related to the plugin.

This is a general Cordova application architecture issue.
