### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by vinicri** [transistorsoft/cordova-plugin-background-fetch#60]
Chris, 

I'm trying to do an Android version, is it possible to publish the code of TSBackgroundFetch.framework to get a better understand of how the fetch is managed?

Thanks

**Comment by christocracy** [comment]
How do you propose to do an Android version?

**Comment by vinicri** [comment]
First idea is to implement it as a service. But studying other ways or particularities to consider to make it robust.

**Comment by vinicri** [comment]
I see you already have published it. :)

**Comment by epetre** [comment]
Couldn't it be a background service that gets scheduled every X minutes just to fetch an  info from the server and then shut down while rescheduling for X minutes later?

**Comment by christocracy** [comment]
If I were doing this, I'd like use [`AlarmManager#setRepeating`](https://developer.android.com/reference/android/app/AlarmManager.html#setRepeating(int,%20long,%20long,%20android.app.PendingIntent)) from a service.

**Comment by tdulcet** [comment]
What about using an [Android Sync Adapter](https://developer.android.com/training/sync-adapters/index.html)? It is the most similar to iOS background fetch, as Android also regulates when the sync takes place. It has already been implemented for React Native: https://github.com/ferrannp/react-native-sync-adapter, so it should not be too hard to do for Cordova.

**Comment by christocracy** [comment]
@tdulcet That looks interesting, I'll research that.

**Comment by debevv** [comment]
Hi, I'm currently working on a version for Android, but I've hit a wall and I can't go on: it's impossible to execute Javascript code outside a CordovaWebView. So I'm unable to execute the user callback either from a simple Service or a SyncAdapter class.
I was about to make a pull request, but looks like I'm forced to write native code for fetching data in my app.

**Comment by tdulcet** [comment]
@debevv Did you try any of these Javascript engines for Android:
- https://github.com/eclipsesource/J2V8
- https://github.com/square/duktape-android
- https://github.com/ericwlange/AndroidJSCore
- https://github.com/evgenyneu/js-evaluator-for-android

The React Native Sync Adapter uses the [Headless JS](https://facebook.github.io/react-native/docs/headless-js-android.html) Javascript engine, so it seems that a JS engine is necessary for Cordova too.

**Comment by christocracy** [comment]
If Cordova has some kind of Headless JS mechanism, I'll be all over that.

I've implemented headless js for my React-native-background-Geolocation plugin

**Comment by tdulcet** [comment]
Any of those Javascript engines should work for executing the user callback from a Sync Adapter, just as Headless JS does for React Native. This comparison: https://medium.com/tech-quizlet/comparison-shopping-searching-for-javascript-engines-for-android-bdc656538f2e says the J2V8 is the best in terms of speed and reliability.

**Comment by christocracy** [comment]
Android implemented in `5.2.0`.

Uses [`JobScheduler`](https://developer.android.com/reference/android/app/job/JobScheduler.html) where Build SDK > 21.  [`AlarmManager`](https://developer.android.com/reference/android/app/AlarmManager.html) otherwise.
