### ISSUE TITLE
Meaning of status method

### ISSUE THREAD

**Issue by dukhanov** [transistorsoft/cordova-plugin-background-fetch#61]
Hello, 
Could you please specify what does the status method mean?

I've requested status and received **2**, but I do not know what is means.

**Comment by christocracy** [comment]
Cordova docs need to be updated.  See the [React Native](https://github.com/transistorsoft/react-native-background-fetch#methods) version.

**Comment by dukhanov** [comment]
Thanks
```
- 0: Restricted
- 1: Denied 
- 2: Available
```

**Comment by christocracy** [comment]
[`STATUS_` constants](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/www/BackgroundFetch.js#L27) added in `5.2.0`
