### ISSUE TITLE
Background fetch not working after page reload

### ISSUE THREAD

**Issue by joeychong** [transistorsoft/cordova-plugin-background-fetch#63]
Hi,

Thank for providing the good plugin. I had used this plugin for my project and everything work fine. However, I found that whenever I reload my cordova page (Either i refresh via Safari during remote debugging or my app called location.reload() for some reason), the plugin will stop working after that. From log, when I reload, due to it will `call Fetcher.configure` again, it showed that:
`- CDVBackgroundFetch already configured`

When I perform "Simulate background fetch", it showed:
```
CDVBackgroundFetch AppDelegate received fetch event
- TSBackgroundFetch performFetchWithCompletionHandler
Warning: Application delegate received call to -application:performFetchWithCompletionHandler: but the completion handler was never called.
- CDVBackgroundFetch Rx Fetch Event
```

The plugin triggered but it seems like it lost reference to the javascript call back and the call back will not called. Btw, is there a way to re-register the javascript callback?

**Comment by christocracy** [comment]
Fetch isn't really that important in development mode like this.  I'll keep an eye out for this.

**Comment by joeychong** [comment]
Thank. It is important to me as I had a "Refresh" button in the app to let user to hard reload all the information in the case that data out of sync.

**Comment by Mehuge** [comment]
I also have a refresh button in the app, mainly to deal with situations where things have gone wrong in the app on site, and need to get things going again for the user by reloading. It's not a big issue though, would just be nice if it worked after refresh.

**Comment by Mehuge** [comment]
I may have a simple fix for it, you can perhaps let me know if there are any problems with this fix.

In `CDVBackgroundFetch.m` method `-(void)configure` remove the code

```
    if (configured) {
        NSLog(@"- %@ already configured", TAG);
        return;
    }
```

And add `[fetchManager removeListener:TAG];` just before the call to `[fetchManager addListener:TAG handler:handler];`.

What I am not sure about is if calling `[fetchManager start]` more than once is going to cause problems.

**Comment by christocracy** [comment]
Fix for what?  Nothing is broken.

**Comment by Mehuge** [comment]
Nothing is broken?  Ofc it is broken, as described by the OP.

location.reload() breaks it

There is a use case for using location.reload()

Looks like I will just have to fork and fix it myself.

**Comment by christocracy** [comment]
Feel free to fix it if it's broken for you.  This is an open-source project.

**Comment by Mehuge** [comment]
Indeed it is, which is why I gave you the code for the fix, in the true spirit of open source.

**Comment by christocracy** [comment]
Send a pull request

**Comment by joeychong** [comment]
Many thank. I will give it a try later.

**Comment by christocracy** [comment]
Removed `if (configured)` in latest version `5.0.0`, in addition to new config param `minimumFetchInterval`.

See #69
