### ISSUE TITLE
Error: exec proxy not found for :: BackgroundFetch :: configure

### ISSUE THREAD

**Issue by bhagaym** [transistorsoft/cordova-plugin-background-fetch#68]
Hello..

I trying to install this awesome plugin in my cordova project but when I write down the code like here: 
[https://github.com/transistorsoft/cordova-plugin-background-fetch#example](url) I got error like this:
`Error: exec proxy not found for :: BackgroundFetch :: configure`
I try to build on android and this is nothing happen.
How to resolve this error?
thank you in advance.

------------------------------------
this is my code
`
var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    onDeviceReady: function() {
        this.receivedEvent('deviceready');

        var Fetcher = window.BackgroundFetch;

        // Your background-fetch handler.
        var fetchCallback = function() {
            console.log('[js] BackgroundFetch initiated');
        };
        var failureCallback = function(error) {
            console.log('- BackgroundFetch failed', error);
        };
        Fetcher.configure(fetchCallback, failureCallback, {
            stopOnTerminate: true  // <-- true is default
        });
    },

};

app.initialize();
`

**Comment by christocracy** [comment]
This is an iOS only plugin.

**Comment by bhagaym** [comment]
Opss.. sorry I don't know it..
thanks
