### ISSUE TITLE
package.json version vs config.xml version

### ISSUE THREAD

**Issue by dpa99c** [transistorsoft/cordova-plugin-background-fetch#72]
Currently the [version in package.json](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/package.json#L3) is `5.1.0` while the [version in plugin.xml](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/plugin.xml#L6) is `5.0.0`.

This is enough to cause `cordova@7` to cry because it installs the plugin to both `node_modules/` using `npm install` and via its legacy install method to `plugins/`, particularly because [cordova-background-geolocation](https://github.com/transistorsoft/cordova-background-geolocation) now [depends on v5.1.0](https://github.com/transistorsoft/cordova-background-geolocation/blob/master/plugin.xml#L17)

**Comment by christocracy** [comment]
Crap.  Will have to release 5.1.1

**Comment by christocracy** [comment]
Ok, `cordova-plugin-background-fetch@5.1.1` is released.

I re-tagged `2.8.4` with `cordova-plugin-background-fetch` dependency @ `5.1.1`.

Un-install / re-install `background-geolocation`

**Comment by christocracy** [comment]
Actually, it was a mistake to re-tag `2.8.4`.  I released `2.8.5` today.  Things are hectic with iOS 11 / Android 8, Cordova + React Native.

**Comment by Eolus** [comment]
master is reporting 5.1.1, but I don't see a 5.1.1 tag on anything here.
I use Telerik AppBuilder, and their most recent release has a problem where they are ignoring the version restriction.  Their proposed workaround to get iOS to build until they get their problem fixed is to use the tag like:

<dependency id="cordova-plugin-background-fetch@~5.1.1" version="~5.1.1" />

**Comment by christocracy** [comment]
I forgot to tag it, but more important, it’s published to npm

**Comment by christocracy** [comment]
There:  [5.1.1](https://github.com/transistorsoft/cordova-plugin-background-fetch/tree/5.1.1)

**Comment by Eolus** [comment]
Thanks! As you surmised, the version tagging was just a red herring.  Telerik actually has two problems: the failure to observe version restrictions and they have not yet updated their build servers from XCode 8.1 to XCode 9 (hence missing support for IOSurface in iOS 11 SDK).

**Comment by christocracy** [comment]
Is this issue closed then?

**Comment by Eolus** [comment]
My part of this issue is closed.
I do not know whether dpa99c's original issue is closed.

**Comment by christocracy** [comment]
@dpa99c?  Is this issue closed?
