### ISSUE TITLE
ld: framework not found IOSurface for architecture arm64

### ISSUE THREAD

**Issue by pagano** [transistorsoft/cordova-plugin-background-fetch#73]
Hi Chris, I'm having this error trying to build the project

ld: framework not found IOSurface for architecture arm64

MacOS 10.12.1
Xcode 8.3.3
Cordova 7.1.0
cordova-plugin-background-fetch 5.1.1

I've disabled "Link Frameworks Automatically" according to https://mmmag.appsee.com/2014/09/22/xcode-new-link-frameworks-automatically-fix-framework-not-found-metal-for-architecture-armv7/ with the same result

Thanks!

**Comment by christocracy** [comment]
Upgrade to latest XCode 9.
