### ISSUE TITLE
Trying in Android for scheduling  but not getting callback 

### ISSUE THREAD

**Issue by Deepankerchaudhary** [transistorsoft/cordova-plugin-background-fetch#75]
Hi christocracy,
I tried your plugins for android. I have to use for iOS as well.
But first i am trying for android. I have to call background callback in every 1 hour. It should be called in exact time.
I am using ionic1. Inside app.js i am putting code like this:
                
        document.addEventListener('deviceready', function () {

           var Fetcher = window.BackgroundFetch;
        
        // Your background-fetch handler.
        var fetchCallback = function() {
            console.log('[js] BackgroundFetch event received');
         
          Fetcher.finish();
        
        
        }
        var failureCallback = function(error) {
            console.log('- BackgroundFetch failed', error);
        };
        Fetcher.configure(fetchCallback, failureCallback, {
            minimumFetchInterval: 15, // <-- default is 15
            stopOnTerminate: false,   // <-- Android only
            startOnBoot: true,        // <-- Android only
            forceReload: true         // <-- Android only
        });

        }, false);

It gives a  weird behavior. as i install app it calls suddenly but it should be called after 15 minutes. after that it is never calling. Please help if it possible through your plugin.

**Comment by christocracy** [comment]
```
$ adb logcat -s TSBackgroundFetch
```

**Comment by Deepankerchaudhary** [comment]
Continuously I am checking logcat inside Android studio but I am not getting callback.
My Cordova version is 7.1.5.
Only got a callback during installation.

**Comment by christocracy** [comment]
From your terminal:

$ adb logcat -s TSBackgroundFetch

**Comment by Deepankerchaudhary** [comment]
Nothing getting called after once:
from terminal:
rtOnBoot":true,"forceReload":true}
01-19 03:43:40.808 18023 18228 D TSBackgroundFetch: - start
01-19 03:43:41.087 18023 18023 D TSBackgroundFetch: - onStopJob
01-19 03:43:58.981 18416 18530 D TSBackgroundFetch: - configure: {"minimumFetchInterval":15,"stopOnTerminate":false,"startOnBoot":true,"forceReload":true}
01-19 03:43:58.985 18416 18530 D TSBackgroundFetch: - start
01-19 03:55:58.660 23190 23317 D TSBackgroundFetch: - configure: {"minimumFetchInterval":15,"stopOnTerminate":false,"startOnBoot":true,"forceReload":true}
01-19 03:55:58.665 23190 23317 D TSBackgroundFetch: - start

**Comment by christocracy** [comment]
With `<your.app.id>`, execute the following command to for a fetch event:
```
$ adb shell cmd jobscheduler run -f <your.app.id> 999
```

**Comment by Deepankerchaudhary** [comment]
Thank for the suggestion but I think you are not getting my point. I have to fetch event automatically in ionic app which is not coming through your code as I described the behaviour above. I am still stuck on the same :(

**Comment by christocracy** [comment]
I just created the Android implementation *this week*.  I need you to follow instructions exactly.

What Android os and build sdk?

**Comment by Deepankerchaudhary** [comment]
I am running it on Android M 6.1.
I am using SDK API level 24.
Thanks

**Comment by petemcwilliams** [comment]
I'm also working with Android release from ionic... 

I'm testing using the following which seems to be working @(I've taken out significant chunks so not tested exactly the code below... might help you find the correct direction though).
```
import { Injectable } from '@angular/core';
import { Platform } from 'ionic-angular';

@Injectable()
export class IonicBackgroundFetchService {
    private _fetcher = (window as any).BackgroundFetch;

    constructor(private _platform: Platform) {}

    public init() {
        this._platform.ready().then(() => {
            console.log('BACKGROUND FETCH INIT');
            this._fetcher.configure(this._fetchCallback.bind(this), this._failureCallback.bind(this), {
                minimumFetchInterval: 15,
                startOnBoot: true,
                stopOnTerminate: false,
            });
        });
    }

    private _fetchCallback = () => {
        console.log('BACKGROUND FETCH running');
        this._fetcher.finish();
    };

    private _failureCallback = error => {
        console.log('BACKGROUND FETCH failed', error);
        this._fetcher.finish();
    };
}
```

```
ionic info

cli packages: 

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

```

**Comment by christocracy** [comment]
Thanks @petemcwilliams.  I wasn’t aware they’d wrapped my plugin.  I pissed a few people off over at Ionic and they once told me “we’ll never use your plugins in @ionic/native”.

**Comment by ninexus** [comment]
we have a same issue coming , the background fetch function gets called everytime app is loaded. where as it should be called after 15 minutes. it happens only in android not in ios.
