### ISSUE TITLE
Fetch code no longer succesfully run when Android OS kills app

### ISSUE THREAD

**Issue by FPeters84** [transistorsoft/cordova-plugin-background-fetch#77]
Hi,

First of all, again my thanks for this plugin and all the effort you did for making an android implementation.

In my app I would always like to run the fetch code every 15 minutes, no matter what happens.
At this moment the fetch code in my app is succesfully executed in the following scenario's:
- user does not open the app for a long time: fetch code keeps being executed
- user terminates app from task list: app is restarted: fetch code keeps being executed
- device is restarted: fetch code keeps being executed

However in this scenario, the fetch code is no longer executed:
- Android OS kills app (for example because device memory is full, and your app is targeted to be closed)

Am I correct that in this scenario the app does not auto reload in the same way as when the user terminates the app via the task list?
Note that my fetch code uses cordova functionalities (so in other words: my fetch code needs cordova to be initialized).
This is the config I use for fetch (I assume because of 'stopOnTerminate: false', the expected behaviour is the fetch code is also executed when the Android OS kills the app):

    Fetcher.configure(fetchCallback, failureCallback, {
        minimumFetchInterval: 15, // <-- default is 15
        stopOnTerminate: false,   // <-- Android only
        startOnBoot: true,        // <-- Android only
        forceReload: true        // <-- Android only
    });

Thanks in advance for any help!
Kind regards,
Frank

**Comment by christocracy** [comment]
In my testing, the fetch events continue to fire after I terminate the Android app (with `stopOnTerminate: false`).  If I configure `forceReload: true`, the app reboots (and immediately minimizes).

Provide **Device model, OS and logs**:
```
$ adb logcat
```

**Comment by FPeters84** [comment]
Hi,

My phone: Samsung A5 2017 edition
Android version: 7.0
My android-minSdkVersion in my config.xml is 21

I'm sorry to say I never use Android studio. I build everything with Phonegap build and debug with Gapdebug. Not sure how to get the logcat logs you are referring too, sorry for my noobness.

However you say if you terminate the Android app it keeps working. This is also the case for me if I manually terminate the app (via the task window). However if the OS kills the apps, it looks like the forcereload is not working.
Sorry again about not being able to provide the logs.

Kind regards,
Michiel

**Comment by christocracy** [comment]
["How can I get a logcat"](https://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat)

**Comment by nasserghiasi** [comment]
the app can't restart with ```forceReload: true``` Android OS killed our app after a while.
