### ISSUE TITLE
App not running in background

### ISSUE THREAD

**Issue by Smartronic2017** [transistorsoft/cordova-plugin-background-fetch#79]
Hello. I've installed this plugin and tried it. 
But when I close my app, the fetchCallback doesn't run.
This is my code:
` initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {

        var Fetcher = window.BackgroundFetch;
        
        // Your background-fetch handler.
        var fetchCallback = function() {
            console.log('[js] BackgroundFetch event received');
            // write data to my server
           Fetcher.finish();
        }

        var failureCallback = function(error) {
            console.log('- BackgroundFetch failed', error);
        };
        Fetcher.configure(fetchCallback, failureCallback, {
            minimumFetchInterval: 15, // <-- default is 15
            stopOnTerminate: false,   // <-- Android only
            startOnBoot: true        // <-- Android only
            //forceReload: false         // <-- Android only
        });

        this.receivedEvent('deviceready');
    }
`

The only way to make it always run is setting `forceReload:true`, but i don't want my app shows itself (even if just for less than 1 second).

How can i solve this?
Possibile workaround: Is there a way to use forceReload:true without showing app?

**Comment by christocracy** [comment]
Imagine your Android app is a chalkboard.  Your javascript is written with the chalk.

When your app is terminated, the chalkboard is completely erased.  Your Javascript no longer exists.

If you're hoping to run code while your app is terminated, you're going to need to write native Android code.  See the new [`@config enableHeadless`](https://github.com/transistorsoft/cordova-plugin-background-fetch#config-boolean-enableheadless-false) in version `5.2.1` released today.

If you want to run *Javascript* code after app is terminated, you **MUST** use `forceReload: true`.

**Comment by Smartronic2017** [comment]
Is there a way to use forceReload:true without showing app?

**Comment by christocracy** [comment]
>Is there a way to use forceReload:true without showing app?

If there were, I would've done it.  There is not.
