### ISSUE TITLE
Trying in IOS for scheduling but not getting callback

### ISSUE THREAD

**Issue by amitvikram1985** [transistorsoft/cordova-plugin-background-fetch#80]
Hi christocracy,
I tried your plugins for IOS.
I have to call background callback in every 1 hour. 
It should be called in exact time.
I am using ionic1. Inside app.js i am putting code like this:

    document.addEventListener('deviceready', function () {

       var Fetcher = window.BackgroundFetch;
    
    // Your background-fetch handler.
    var fetchCallback = function() {
        console.log('[js] BackgroundFetch event received');
     
      Fetcher.finish();
    
    
    }
    var failureCallback = function(error) {
        console.log('- BackgroundFetch failed', error);
    };
    Fetcher.configure(fetchCallback, failureCallback, {
        minimumFetchInterval: 15, // <-- default is 15
        stopOnTerminate: false,   // <-- Android only
        startOnBoot: true,        // <-- Android only
        forceReload: true         // <-- Android only
    });

    }, false);

It gives a weird behavior. as I have install app it calls suddenly but it should be called after 15 minutes. after that it is never calling. Please help if it possible through your plugin.

It is urgent,Please help us.

**Comment by rgolea** [comment]
@amitvikram1985 here is a text pasted from the ionic documentation:
```
There is no way to increase the rate which a fetch-event occurs and this plugin sets the rate to the most frequent possible value of UIApplicationBackgroundFetchIntervalMinimum -- iOS determines the rate automatically based upon device usage and time-of-day (ie: fetch-rate is about ~15min during prime-time hours; less frequently when the user is presumed to be sleeping, at 3am for example)
```
See [docs](https://ionicframework.com/docs/native/background-fetch)

**Comment by christocracy** [comment]
This plugin isn’t a clock.  Event will be throttled by the iOS depending on user behavior.  Eg, if the user doesn’t use their device for a long period of time, event might not occur at all until they unlock the device and open your app.
