### ISSUE TITLE
Never getting callback neither in android nor in iOS within the specific interval

### ISSUE THREAD

**Issue by Deepankerchaudhary** [transistorsoft/cordova-plugin-background-fetch#81]
Hi Crist,
Thanks for your effort but sorry to say that i am not able to execute these plugins neither in android nor in iOS.
There is no callback within the interval inside the following code:
var fetchCallback = function() {
    console.log('[js] BackgroundFetch event received');

    //Never getting callback.
    BackgroundFetch.finish();
  };
I am using iOS 10 for the testing. I am using your plugin for ionic1.

Your help would be appreciated.

Thanks

**Comment by christocracy** [comment]
https://github.com/transistorsoft/cordova-plugin-background-fetch#debugging

**Comment by Deepankerchaudhary** [comment]
I did the same thing as mentioned in above link. By Debug > Simulate background fetch but i am not able to get background logs.:(

**Comment by christocracy** [comment]
Observe XCode logs when you Simulate Background fetch.  post them here.

**Comment by rgolea** [comment]
Hey @christocracy ! The same thing happens to me.
I am using ionic 4 with the example on the docs and I'm getting this in the debugger when I start:
```
To Native Cordova ->  BackgroundFetch configure BackgroundFetch355565311 ["options": [{
    forceReload = 1;
    minimumFetchInterval = 15;
    startOnBoot = 1;
    stopOnTerminate = 0;
}]]
2019-04-08 12:41:29.289382+0200 App[9595:2303803] [TSBackgroundFetch configure]: {
    forceReload = 1;
    minimumFetchInterval = 15;
    startOnBoot = 1;
    stopOnTerminate = 0;
}
```
I am using capacitor with a cordova plugin but they are compatible ([see here](https://capacitor.ionicframework.com/docs/basics/cordova)).
So it seems that it does get triggered in cordova and added to ios. But when I click on `Simulate Background Fetch` I only get `APP INACTIVE`.
I thought I needed to wait a while to trigger but it seems that after 5 minutes, it doesn't trigger.

Any ideas?

**Comment by rgolea** [comment]
#108 Seems to have the same problem

**Comment by christocracy** [comment]
No idea.  I don’t use Capacitor.

**Comment by mogery** [comment]
Hi, sorry to comment on such an old issue but I’m currently hitting the same issue, with Capacitor as well. Has there been any solution found?

**Comment by christocracy** [comment]
This issue is far too old to have any correlation.  Post a new issue.
