### ISSUE TITLE
Feature request for Android: only do forceReload when device is locked

### ISSUE THREAD

**Issue by MichielJ87** [transistorsoft/cordova-plugin-background-fetch#83]
Dear Christocracy,

First of all thank you for this plugin!

I am using this plugin for Android an I am really excited with it. At this moment I have forceReload set to true. As documented in the readme, now and then you shortly see the app in the foreground.  I understand this is a consequence of restarting the app.

However I was wondering: might it be possible to add a configuration for Android to only force reload the app when the device is locked? 
When the device is locked, the user will not notice the app coming to the foreground anyway. So this way you have an (almost) constant background fetch going on, without the user noticing anything.

I myself am using this plugin to check if the device is locked, and this seems to work on my 2 phones (https://www.npmjs.com/package/cordova-plugin-lock-info).

Thanks in advance for your possible consideration of this idea!
Michiel

**Comment by christocracy** [comment]
Could probably be made optional.

**Comment by webglisten** [comment]
Is there any way to not let the app run on foreground and just run a piece of code when the fetch event occurs so that  we can do the tasks in that piece of code itself and not let the app run continuously in foreground.???

**Comment by christocracy** [comment]
@webglisten I don't understand what you're saying.

This plugin does not "make the app run on foreground".  It's awakened only periodically by the OS.

**Comment by MichielJ87** [comment]
Hi @christocracy ,

Sorry to bother you again with this topic.
Just for me to know: is this currently somewhere on your roadmap?

Many thanks in advance for your reply, and all the effort you already put in this pluging!
Michiel
