### ISSUE TITLE
Andoird Build: no versions of com.transistorsoft:tsbackgroundfetch are available

### ISSUE THREAD

**Issue by sebastianhelbig** [transistorsoft/cordova-plugin-background-fetch#86]
* Plugin version: 5.3.0
* Platform: Android
* OS version: OS X
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0

```
EmberCordovaError: EmberCordovaError: /Users/sh/Developer/teendate/mobileapp/corber/cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
  Searched in the following locations:
      file:/Users/sh/Library/Android/sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/sh/Library/Android/sdk/extras/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/Users/sh/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/sh/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tsbackgroundfetch/
      file:/Users/sh/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/sh/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tsbackgroundfetch/
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tsbackgroundfetch/
      https://repo1.maven.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      https://repo1.maven.org/maven2/com/transistorsoft/tsbackgroundfetch/
      file:/Users/sh/Developer/teendate/mobileapp/corber/cordova/platforms/android/app/src/android/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
      file:/Users/sh/Developer/teendate/mobileapp/corber/cordova/platforms/android/app/src/android/libs/com/transistorsoft/tsbackgroundfetch/
  Required by:
      project :app
```

**Comment by nimeso** [comment]
@christocracy dude we pay good money for your product and now we have other versions of packages that require Cordova 8! Using Cordova 6 is not a option for us. Stop closing issues when they are not solved! Your product is two versions behind now. Sorry to sound angry but I am! I'd understand if it was open source but it's not so you need to provide updates.

**Comment by christocracy** [comment]
This is an open source project.  

Feel free to dive-in and issue a pull-request.

**Comment by nimeso** [comment]
@christocracy that is not really the response I want to hear. I'm just a manager and am not going to (and can't) spend money on developers to do your job. We paid for this.

**Comment by christocracy** [comment]
You did **not** pay for the background-fetch plugin.

I provide this plugin free and open source.

**Comment by nimeso** [comment]
background-geolocation has dependency on background-fetch.

**Comment by christocracy** [comment]
If you have an issue with background-geolocation, perhaps you should redirect yourself over there.

**Comment by nimeso** [comment]
This is pointless and wasting my time. Are you going to do anything about this issue or not? Maybe you need to 'redirect' yourself to fixing the issue instead of writing unhelpful git posts when we paid for your product? Sorry bro, just getting sick of all the issues we have had with your background-geolocation product. Can you give me a time frame when background-geolocation will work with 7? Thanks.
