### ISSUE TITLE
Running headless

### ISSUE THREAD

**Issue by arjunmenon** [transistorsoft/cordova-plugin-background-fetch#88]
Hey
I have a simple native cordova app running a web server which listens to incoming requests and serves a requested file.

So to run this server as long as the user do not explicitly close app or swipe the app from multitasker, do I have to port the entire java to this headless class?

But starting/stopping the server is done through JS.

**Comment by christocracy** [comment]
To what do you expect to serve this file to when your app is terminated?

**Comment by arjunmenon** [comment]
Ohh. It will serve music files from sdcard over the network. An external device would periodically fetch files from the phone.

**Comment by christocracy** [comment]
well, if you're hoping to perform your work in the Javascript layer, your Javascript dies when the app is terminated.  No more work will be done until the the app is rebooted or you migrate that work to the plugin's Headless Java receiver.

**Comment by christocracy** [comment]
you may configure `forceReload` and the plugin reboot your Cordova app (and Javascript) when a fetch event determines your app was terminated.

**Comment by arjunmenon** [comment]
From what I can gather, `forcereload` will bring the app for a brief moment to the user and then minimize it, right?
That would be one way.

Otherwise, if the headless can manage all my java code, which has dependencies, that would be better.
If that is the case, I can also delegate certain JS functionality to android?
Think of it as a music player. Can it talk to JS, when active. And queue it, when the JS is terminated. So the next time user opens the app, it displays those messages?

How does callbacks work in the headless context?

**Comment by christocracy** [comment]
See Wiki Android Headless Support for more info.

Headless only receives events while your app is headless.  You would need to create your own custom 
Cordova plugin which implement your Core functionality in a generic class.  Both your Cordova plugin and your Headless task provided by this plugin would interact with this Library you create.

If you’re familiar with Cordova plugin and Android development, a relatively simple task.

**Comment by arjunmenon** [comment]
There is no wiki for this plugin?

**Comment by christocracy** [comment]
Oh, right.  I came up with an idea in my [cordova-background-geolocation](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode) plugin for allowing one to provide their own custom Java class to handle Headless events by I see I haven’t implemented it here yet.

**Comment by arjunmenon** [comment]
Thanks. I will give it a try.
