### ISSUE TITLE
Documentation question for iOS configure failure function

### ISSUE THREAD

**Issue by craig-at-rsg** [transistorsoft/cordova-plugin-background-fetch#89]
This projects README.md file says, when describing the configure method:

> The failureFn will be called if the device doesn't support background-fetch.

I see this failureFn getting called on lots of devices that I would think would support background fetch. Could this have multiple causes, like Apple code decides not to run the background fetch, or the user turned off background fetch? My first thought was to call stop() inside this failureFn, but I wasn't sure if background fetch might become available again after this function is triggered.

**Comment by christocracy** [comment]
Probably means user has disabled Fetch via Settings are you disabled the Background Fetch capability:
![](https://dl.dropboxusercontent.com/s/ywc2zo9vb5mrvxf/Screenshot%202018-03-07%2010.45.39.png?dl=1)
