### ISSUE TITLE
background-fetch update for cordova 7.x

### ISSUE THREAD

**Issue by webquali** [transistorsoft/cordova-plugin-background-fetch#90]
Hi, there is some hope that you will update background-fetch for cordova-android 7.x?

**Comment by webquali** [comment]
Maybe you share changes with me and I will change manual on my side?

**Comment by HenrikWild** [comment]
Any news on this?

**Comment by christocracy** [comment]
See the [CHANGELOG](https://github.com/transistorsoft/cordova-plugin-background-fetch/blob/master/CHANGELOG.md#540--2018-05-16)
