### ISSUE TITLE
I want to execute function even app is closed.

### ISSUE THREAD

**Issue by aaronharper123** [transistorsoft/cordova-plugin-background-fetch#92]
I want to execute one xyz function even user closed the app. This function should run 24*7 days.

In below code, for example, i want to get local notification every 3 seconds after user closed the app.
But when i execute below method nothing happens..

onDeviceReady() {
        let BackgroundFetch = (<any>window).BackgroundFetch;

        // Your background-fetch handler.
        let fetchCallback = function() {
            console.log('[js] BackgroundFetch event received');
            setInterval(()=> {
                    let bb ={
                      id: 200,
                     title: 'Ttile',
                     text: 'Text',
                     sound: 'file://assets/sound/alert_gps.mp3'
                   }
                  cordova.plugins.notification.local.schedule(bb);
                },3000);

            BackgroundFetch.finish();
        }
        let failureCallback = function(error) {
            console.log('- BackgroundFetch failed', error);
        };
        BackgroundFetch.configure(fetchCallback, failureCallback, {
            minimumFetchInterval: 15, // <-- default is 15
            stopOnTerminate: false,   // <-- Android only
            startOnBoot: true,        // <-- Android only
            forceReload: true         // <-- Android only
        });

    }

My Environment: 

1. Plugin version: ^5.4.0
2. Platform: Android
3. OS version: Android Naugat 7.0
4. Device manufacturer / model: Motorola Moto g4
5. Cordova version: 8.0.0
6. Cordova platform version: 
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

Please give me answer with possible solution.

**Comment by christocracy** [comment]
You're not giving me any information:

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************

  Provide a general summary of the issue in the Title above 
-->
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by aaronharper123** [comment]
Please i update my question , please look at

**Comment by christocracy** [comment]
There's no guarantee the fetch event will be executed.  It all depends upon how often the user opens the device.

If the device is sitting stationary, unplugged from power and the device is not being opened, the operating system's power manager will throttle events.

See the README to see how to  simulate a fetch event for Android.  If that simulated event fires, that's all you can do.

**Comment by christocracy** [comment]
Also you **cannot** do a `setInterval` in the `fetchCallback`.

The `fetchCallback` will be executed *at most* every 15 minutes.

**Comment by aaronharper123** [comment]
But i want to call fetchCallback at every 15 seconds even 24*7 days then is it possible ?

**Comment by christocracy** [comment]
>every 15 seconds even 24*7

**Impossible**.

The best you’ll get is every 15 minutes.

**Comment by christocracy** [comment]
And what are you trying to do *every 15 seconds* on a mobile device, anyway?

**Comment by aaronharper123** [comment]
I want to do two activities , 
First: I want to check gps status (i.e. gps is on or off?)
Second: I want to check current time with my web service time if they matches then i will perform another activity.
