### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by sunnymtl** [transistorsoft/cordova-plugin-background-fetch#93]
I'm trying to install this plugin for iOS platform in an empty ionic project, but failed to build. Other plugins worked fine in the same environment. I have tried to install cordova-background-geolocation-lt plugin as well, got the same error message. 

**Here is the ionic info:**
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2
global packages:
    cordova (Cordova CLI) : 7.0.1
local packages:
    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
System:
    ios-deploy : 1.9.2
    Node       : v6.11.2
    npm        : 3.10.10
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

**Below is the error message:**
The following build commands failed:
        Check dependencies
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/smac/ionic/testProj2/platforms/ios/cordova/build-debug.xcconfig,-workspace,MyApp.xcworkspace,-scheme,MyApp,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,MyApp.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/smac/ionic/testProj2/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/smac/ionic/testProj2/platforms/ios/build/sharedpch
[ERROR] An error occurred while running cordova run ios (exit code 1).
Here is the ionic info:

**and xCode shows this error:**
error: linker command failed with exit code 1 (use -v to see invocation)

Thanks for any help!

**Comment by christocracy** [comment]
Upgrade XCode.  You *must* use version 9.

**Comment by christocracy** [comment]
You're from Montreal (ie: "mtl")?  I am.

**Comment by sunnymtl** [comment]
Thank you Chris for the quick response,  I will upgrade the XCode and give it a try!
Yes I'm from Montreal, glad to hear we are in the same city : )
