### ISSUE TITLE
Android issues

### ISSUE THREAD

**Issue by sunnymtl** [transistorsoft/cordova-plugin-background-fetch#95]
Hi Chris,

I'm testing this plugin for Android, and observed two issues.

Here is my environment:
   @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : 8.0.0
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 4.1.0
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    Node              : v6.10.3
    npm               : 6.1.0
    OS                : Windows 10
Environment Variables:
    ANDROID_HOME : C:\Users\zzz\AppData\Local\Android\sdk
Misc:
    backend : pro

1. If I manually terminate my app (swipe close from the app list), the plugin works basically fine (see another issue below). But if the system kills my app (after open many other apps and games), my app cannot be normally relaunched in the background. In this case I can see my app is running with a help of a software (Simple system monitor), but it's not functioning and seems just loaded partially. My ionic app usually takes up more than 100M memory, but now it just takes up less than 10M. I have tested with Android 6.0 and 7.0 mobile and got the same result. Below is the logcat:

--------- beginning of crash
--------- beginning of system
--------- beginning of main
06-18 13:06:03.146 29968 30132 D TSBackgroundFetch: - configure: {
06-18 13:06:03.146 29968 30132 D TSBackgroundFetch:   "minimumFetchInterval": 15,
06-18 13:06:03.146 29968 30132 D TSBackgroundFetch:   "stopOnTerminate": false,
06-18 13:06:03.146 29968 30132 D TSBackgroundFetch:   "startOnBoot": true,
06-18 13:06:03.146 29968 30132 D TSBackgroundFetch:   "forceReload": true
06-18 13:06:03.146 29968 30132 D TSBackgroundFetch: }
06-18 13:06:03.148 29968 30132 D TSBackgroundFetch: - start
06-18 13:21:05.296 29968 29968 D TSBackgroundFetch: - Background Fetch event received
06-18 13:21:30.362 29968 30132 D TSBackgroundFetch: - finish
06-18 13:21:30.362 29968 30132 D TSBackgroundFetch: - jobFinished
….
06-18 15:27:57.956 29968 29968 D TSBackgroundFetch: - Background Fetch event received
06-18 15:28:23.044 29968 30132 D TSBackgroundFetch: - finish
06-18 15:28:23.044 29968 30132 D TSBackgroundFetch: - jobFinished
(*****here my app is manually terminated)
06-18 15:54:07.305 14851 14851 D TSBackgroundFetch: - MainActivity is inactive
06-18 15:54:07.305 14851 14851 I TSBackgroundFetch: - Forcing MainActivity reload
06-18 15:54:14.823 14851 14938 D TSBackgroundFetch: - configure: {
06-18 15:54:14.823 14851 14938 D TSBackgroundFetch:   "minimumFetchInterval": 15,
06-18 15:54:14.823 14851 14938 D TSBackgroundFetch:   "stopOnTerminate": false,
06-18 15:54:14.823 14851 14938 D TSBackgroundFetch:   "startOnBoot": true,
06-18 15:54:14.823 14851 14938 D TSBackgroundFetch:   "forceReload": true
06-18 15:54:14.823 14851 14938 D TSBackgroundFetch: }
06-18 15:54:14.824 14851 14938 D TSBackgroundFetch: - start
06-18 15:54:14.848 14851 14851 D TSBackgroundFetch: - onStopJob
....
(*****here my app is killed by system)
06-18 17:19:23.301 25940 25940 D TSBackgroundFetch: - Background Fetch event received
06-18 17:29:23.330 25940 25940 D TSBackgroundFetch: - onStopJob
06-18 17:29:23.389 25940 25940 D TSBackgroundFetch: - Background Fetch event received
06-18 17:29:53.261 25940 25940 D TSBackgroundFetch: - onStopJob
...

2. Sometimes the Background Fetch event is received too frequent (less than 1 minute between events), if I don't stop it, it will continue like this. The battery consumption increase dramatically in this case. See logcat below:

--------- beginning of crash
--------- beginning of system
--------- beginning of main
06-18 09:40:02.939 28275 28364 D TSBackgroundFetch: - finish
06-18 09:40:02.939 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:40:07.845 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:40:32.850 28275 28364 D TSBackgroundFetch: - finish
06-18 09:40:32.850 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:40:37.835 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:41:02.844 28275 28364 D TSBackgroundFetch: - finish
06-18 09:41:02.844 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:41:08.063 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:41:33.073 28275 28364 D TSBackgroundFetch: - finish
06-18 09:41:33.073 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:41:33.163 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:41:58.172 28275 28364 D TSBackgroundFetch: - finish
06-18 09:41:58.173 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:42:46.842 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:43:11.851 28275 28364 D TSBackgroundFetch: - finish
06-18 09:43:11.851 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:43:16.740 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:43:41.756 28275 28364 D TSBackgroundFetch: - finish
06-18 09:43:41.756 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:44:03.808 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:44:28.817 28275 28364 D TSBackgroundFetch: - finish
06-18 09:44:28.817 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:44:33.884 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:44:58.893 28275 28364 D TSBackgroundFetch: - finish
06-18 09:44:58.893 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:45:00.058 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:45:25.067 28275 28364 D TSBackgroundFetch: - finish
06-18 09:45:25.067 28275 28364 D TSBackgroundFetch: - jobFinished
06-18 09:45:38.980 28275 28275 D TSBackgroundFetch: - Background Fetch event received
06-18 09:46:04.007 28275 28364 D TSBackgroundFetch: - finish
06-18 09:46:04.007 28275 28364 D TSBackgroundFetch: - jobFinished
...

Is there any way to fix above issues? Apart from that, it works fine!

Thanks a lot!

**Comment by christocracy** [comment]
> My ionic app usually takes up more than 100M memory, but now it just takes up less than 10M. 

Are you talking about your Ionic app *launched* (ie: `MainActivity` is launched) or running "Headless", where only the plugin's service is running (ie: your Ionic Javascript app is terminated)?

**Comment by sunnymtl** [comment]
I'm talking about the whole Ionic app, since I'm not using "Headless".  I didn't touch  "enableHeadless" in configure and I need the Ionic app to be launched after the OS kills the app...

**Comment by christocracy** [comment]
"Headless" doesn't strictly mean `enableHeadless`.  Your app is headless when you terminate your app with `stopOnTerminate: true`, where your `MainActivity` (where your Ionic Javascript lives) is terminated and only the plugin's background-service is running, "headless".

You will of course see a lower memory footprint when only the background-service is running.

**Comment by sunnymtl** [comment]
Thanks for the answer Chris! As you can see from the logcat, the app was actually terminated with stopOnTerminate: false, how to make the MainActivity reload after the OS kills the app, instead of a headless service?

**Comment by christocracy** [comment]
>how to make the MainActivity reload after the OS kills the app

See docs for `forceReload` (eg: `forceReloadOnMotionChange: true`)

**Comment by sunnymtl** [comment]
Got it! So when OS kills the app, the forceReload (MainActivity) function is actually not included in this plugin, but only available in cordova-background-geolocation-lt plugin? Since it says [there](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#config-boolean-forcereloadonmotionchange-false): "To "force reload" your application, set any of the following options to true: ...".

**Comment by christocracy** [comment]
Sorry, I'm mixed up between the two plugins.

Yes, for background-fetch, just `forceReload: true`

**Comment by sunnymtl** [comment]
: D   Yes I set forceReload: true (see logcat above), but when the OS kills my app, it still running in headless mode, the MainActivity was not loaded. Only the app is manually terminated, the MainActivity will be loaded normally.  Is this a bug?

**Comment by christocracy** [comment]
```
06-18 15:54:07.305 14851 14851 I TSBackgroundFetch: - Forcing MainActivity reload
```
This says it *tried* to force mainactivity reload.  Are you sure it's not reloaded?  The plugin will launch then immediately *minimize* it.

**Comment by sunnymtl** [comment]
I know the "Forcing MainActivity reload" fired after I MANUALLY terminated my app (slide out from the app list). But after the OS killed my app, I'm sure my app was not reloaded, only the headless service was running in the background, since I tested this for many times and got the same result.

**Comment by sunnymtl** [comment]
Hi Chris, is there a solution to above issues? since in most cases, we want the app to be reloaded when the OS terminates it, now the app is only reloaded when it's manually terminated. I also tested you Android app for cordova-background-geolocation-lt plugin, looks like the forceReload functions are not implemented there? Thanks a million!

**Comment by bod1ka** [comment]
Have anybody managed to find a workaround for this? 
No issues observed when app is killed manually by user (it's then restarted and minimized when next fetch event happens), but if it's killed by OS due to lack of RAM, etc. then background fetch stops working even if you use set true to 'enableHeadless' option and write custom java handler for it.

**Comment by faldunate** [comment]
I have same issue, @bod1ka  did you find some workaround?
