### ISSUE TITLE
Background fetch not getting callback every 15 minutes 

### ISSUE THREAD

**Issue by shrashwin** [transistorsoft/cordova-plugin-background-fetch#98]
## Your Environment
* Plugin version: 5.3.0
* Platform: iOS or Android Both
* OS version: Any
* Device manufacturer / model: Any
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):  Android->6.3.0 and Ios: 4.5.4

## Expected Behavior
Background fetch should fall in callback every 15 minutes

## Actual Behavior
The plugin was initialized successfully but there was never a callback.

## Context
Trying to get call back every 15 minutes, where i would call getcurrentposition.

I have my background fetch configured but still, when i check my logs, there is no successful callback

2018-07-26 17:01:42.309139+0545 Doc and Track[801:167586] [TSBackgroundFetch start]
ℹ️+[LocationAuthorization run:] status: 3
🎾-[TSLocationManager startMonitoringBackgroundFetch] BackgroundFetch: ON
2018-07-26 17:01:42.341257+0545 Doc and Track[801:167586] [TSBackgroundFetch addListener]: TSLocationManager
2018-07-26 17:01:42.341291+0545 Doc and Track[801:167586] [TSBackgroundFetch start]

Any idea?

Also, i see this in log,

🔵-[BackgroundTaskManager startPreventSuspendTimer:] BG time remaining: 36
I tried to find but could not find information about this.

Thanks..

**Comment by christocracy** [comment]
Duplicate #70
